[package]
name = "genesis"
version = "0.0.7-pre-alpha"
edition = "2021"
description = "[WIP] Generates data for galaxies, sectors, solar systems, planets and their inhabitants."
license = "MIT"

[workspace]
members = [
    "crates/cosmos",
    "crates/world",
    "crates/life",
    "crates/crafting",
]

[dependencies]
cosmos = { path = "crates/cosmos" }
world = { path = "crates/world" }
life = { path = "crates/life" }
crafting = { path = "crates/crafting" }
