[package]
name = "genesis"
version = "0.1.0"
edition = "2021"
description = "[WIP] Generates data for galaxies, sectors, solar systems, planets and their inhabitants."
license = "MIT"

[workspace]
members = [
    "crates/cosmos",
    "crates/world",
]

[dependencies]
cosmos = { path = "crates/cosmos" }
world = { path = "crates/world" }
life = { path = "../vitaeis" }
seeded_dice_roller = "1.0"
