#![allow(dead_code)]
use super::substance::Substance as S;
use super::types::*;

pub static ADVANCED_MATERIAL_RECIPES: &[Recipe] = &[
    // ===== RARE EARTH PRODUCTS =====
    Recipe {
        id: 1410,
        name: "NdFeB Permanent Magnet",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Neodymium, 0.3), (S::Iron, 0.65), (S::Boron, 0.05)],
        outputs: &[(S::NdFeBMagnet, 1.0)],
        byproducts: &[],
        min_temp_c: 1100,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 4.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 1411,
        name: "SmCo Permanent Magnet",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Samarium, 0.35), (S::Cobalt, 0.65)],
        outputs: &[(S::SmCoMagnet, 1.0)],
        byproducts: &[],
        min_temp_c: 1200,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 5.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 1412,
        name: "REE Phosphor (Eu/Tb/Y blend)",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Europium, 0.1), (S::Gadolinium, 0.1), (S::Yttrium, 0.3)],
        outputs: &[(S::REEPhosphor, 0.5)],
        byproducts: &[],
        min_temp_c: 800,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 3.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 1413,
        name: "Aluminium-Scandium Aerospace Alloy",
        category: RecipeCategory::Alloying,
        inputs: &[(S::Aluminum, 0.98), (S::Scandium, 0.02)],
        outputs: &[(S::AlScAlloy, 1.0)],
        byproducts: &[],
        min_temp_c: 700,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 2.0,
        cross_recipe_group: None,
    },
    // ===== PGM PRODUCTS =====
    Recipe {
        id: 1430,
        name: "Three-Way Catalytic Converter",
        category: RecipeCategory::Manufacturing,
        inputs: &[
            (S::Platinum, 0.01),
            (S::Palladium, 0.02),
            (S::Rhodium, 0.005),
        ],
        outputs: &[(S::CatalyticConverter, 1.0)],
        byproducts: &[],
        min_temp_c: 800,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 2.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 1431,
        name: "PEM Fuel Cell Membrane",
        category: RecipeCategory::Manufacturing,
        inputs: &[
            (S::Platinum, 0.05),
            (S::Carbon, 0.2),
            (S::Polyethylene, 0.3),
        ],
        outputs: &[(S::FuelCellMembrane, 1.0)],
        byproducts: &[],
        min_temp_c: 200,
        pressure_atm: 5.0,
        catalyst: None,
        duration_hours: 6.0,
        cross_recipe_group: None,
    },
    // ===== SUPERALLOY / REFRACTORY PRODUCTS =====
    Recipe {
        id: 1480,
        name: "Single-Crystal Turbine Blade (Ni-Re-Hf superalloy)",
        category: RecipeCategory::Manufacturing,
        inputs: &[
            (S::Nickel, 0.70),
            (S::Rhenium, 0.06),
            (S::Hafnium, 0.02),
            (S::Chromium, 0.15),
            (S::Aluminum, 0.07),
        ],
        outputs: &[(S::TurbineBlade, 1.0)],
        byproducts: &[],
        min_temp_c: 1500,
        pressure_atm: 0.001,
        catalyst: None,
        duration_hours: 48.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 1481,
        name: "NbTi Superconducting Wire",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Niobium, 0.47), (S::Titanium, 0.47), (S::Copper, 0.06)],
        outputs: &[(S::SuperconductingWire, 1.0)],
        byproducts: &[],
        min_temp_c: 2000,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 24.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 1482,
        name: "Cemented Carbide Cutting Tool (WC-Co)",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::TungstenCarbide, 0.85), (S::Cobalt, 0.15)],
        outputs: &[(S::CementedCarbideTool, 1.0)],
        byproducts: &[],
        min_temp_c: 1400,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 6.0,
        cross_recipe_group: None,
    },
    // ===== BATTERY MANUFACTURING =====
    Recipe {
        id: 1450,
        name: "NMC Cathode (Li + Ni + Mn + Co oxide)",
        category: RecipeCategory::Manufacturing,
        inputs: &[
            (S::LithiumCarbonate, 0.4),
            (S::Nickel, 0.3),
            (S::Manganese, 0.15),
            (S::Cobalt, 0.15),
        ],
        outputs: &[(S::NMCCathodeRaw, 1.0)],
        byproducts: &[(S::CarbonDioxide, 0.1)],
        min_temp_c: 900,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 8.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 1451,
        name: "Graphite Anode Preparation",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Graphite, 0.8), (S::Copper, 0.1)],
        outputs: &[(S::GraphiteAnode, 1.0)],
        byproducts: &[],
        min_temp_c: 200,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 2.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 1452,
        name: "Battery Electrolyte",
        category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::LithiumCarbonate, 0.3), (S::Ethanol, 0.5)],
        outputs: &[(S::BatteryElectrolyte, 1.0)],
        byproducts: &[],
        min_temp_c: 50,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 1.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 1453,
        name: "Li-ion Battery Cell Assembly",
        category: RecipeCategory::Manufacturing,
        inputs: &[
            (S::NMCCathodeRaw, 1.0),
            (S::GraphiteAnode, 1.0),
            (S::BatteryElectrolyte, 0.5),
            (S::Aluminum, 0.1),
        ],
        outputs: &[(S::BatteryCell, 1.0)],
        byproducts: &[],
        min_temp_c: 25,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 4.0,
        cross_recipe_group: None,
    },
    // ===== NANOMATERIALS =====
    Recipe {
        id: 2000,
        name: "Carbon Nanotubes (CVD)",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Methane, 0.5), (S::Iron, 0.01)],
        outputs: &[(S::CarbonNanotube, 0.3)],
        byproducts: &[(S::HydrogenGas, 0.1), (S::Carbon, 0.05)],
        min_temp_c: 850,
        pressure_atm: 1.0,
        catalyst: Some(S::Iron),
        duration_hours: 2.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2001,
        name: "Graphene (CVD on Copper)",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Methane, 0.4), (S::Copper, 0.1)],
        outputs: &[(S::Graphene, 0.2)],
        byproducts: &[(S::HydrogenGas, 0.1)],
        min_temp_c: 1000,
        pressure_atm: 0.1,
        catalyst: None,
        duration_hours: 1.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2002,
        name: "Fullerene C60 (Arc Discharge)",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Carbon, 1.0)],
        outputs: &[(S::Fullerene, 0.15)],
        byproducts: &[(S::Carbon, 0.6)],
        min_temp_c: 3000,
        pressure_atm: 0.5,
        catalyst: None,
        duration_hours: 0.5,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2003,
        name: "CdSe Quantum Dots (Hot Injection)",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Zinc, 0.3), (S::Sulfur, 0.2)],
        outputs: &[(S::QuantumDot, 0.1)],
        byproducts: &[],
        min_temp_c: 300,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 0.5,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2004,
        name: "Silver Nanoparticles (Citrate Reduction)",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Silver, 0.1), (S::Water, 1.0)],
        outputs: &[(S::SilverNanoparticle, 0.08)],
        byproducts: &[(S::Water, 0.9)],
        min_temp_c: 100,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 1.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2005,
        name: "Gold Nanoparticles (Turkevich Method)",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Gold, 0.05), (S::Water, 1.0)],
        outputs: &[(S::GoldNanoparticle, 0.04)],
        byproducts: &[(S::Water, 0.9)],
        min_temp_c: 100,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 0.5,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2006,
        name: "TiO2 Nanoparticles (Sol-Gel)",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Titanium, 0.3), (S::Ethanol, 0.5)],
        outputs: &[(S::TiO2Nano, 0.25)],
        byproducts: &[(S::Water, 0.3), (S::Ethanol, 0.1)],
        min_temp_c: 500,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 4.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2007,
        name: "Iron Oxide Nanoparticles (Co-precipitation)",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Iron, 0.3), (S::SodiumHydroxide, 0.4)],
        outputs: &[(S::IronOxideNano, 0.2)],
        byproducts: &[(S::Water, 0.3)],
        min_temp_c: 60,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 2.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2008,
        name: "Silica Nanoparticles (Stober Process)",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::SilicaSand, 0.3), (S::Ethanol, 0.5), (S::Ammonia, 0.1)],
        outputs: &[(S::SilicaNano, 0.2)],
        byproducts: &[(S::Water, 0.4), (S::Ethanol, 0.2)],
        min_temp_c: 50,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 6.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2009,
        name: "Nanocellulose (Acid Hydrolysis)",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Cellulose, 1.0), (S::SulfuricAcid, 0.5)],
        outputs: &[(S::Nanocellulose, 0.5)],
        byproducts: &[(S::Water, 0.5), (S::Glucose, 0.2)],
        min_temp_c: 45,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 2.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2010,
        name: "Aerogel (Supercritical Drying)",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::SilicaSand, 0.5), (S::Methanol, 0.8)],
        outputs: &[(S::Aerogel, 0.3)],
        byproducts: &[(S::Methanol, 0.5)],
        min_temp_c: 31,
        pressure_atm: 74.0,
        catalyst: None,
        duration_hours: 12.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2011,
        name: "Metal-Organic Framework (Solvothermal)",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Zinc, 0.3), (S::Formaldehyde, 0.5)],
        outputs: &[(S::MOF, 0.4)],
        byproducts: &[(S::Water, 0.2)],
        min_temp_c: 140,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 24.0,
        cross_recipe_group: None,
    },
    // ===== SUPERCONDUCTORS =====
    Recipe {
        id: 2020,
        name: "YBCO Superconductor (Solid-State)",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Calcium, 0.3), (S::Copper, 0.4), (S::Cobalt, 0.3)],
        outputs: &[(S::YBCO, 0.8)],
        byproducts: &[(S::CarbonDioxide, 0.1)],
        min_temp_c: 950,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 24.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2021,
        name: "MgB2 Superconductor (Powder-in-Tube)",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Magnesium, 0.5), (S::Silicon, 0.3)],
        outputs: &[(S::MgB2Superconductor, 0.7)],
        byproducts: &[],
        min_temp_c: 850,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 4.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2022,
        name: "NbTi Superconducting Wire",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Tungsten, 0.5), (S::Titanium, 0.5)],
        outputs: &[(S::NbTi, 0.9)],
        byproducts: &[],
        min_temp_c: 2500,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 8.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2023,
        name: "Nb3Sn (Bronze Route)",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Tungsten, 0.4), (S::Tin, 0.3), (S::Copper, 0.3)],
        outputs: &[(S::NbTi, 0.8)],
        byproducts: &[(S::Copper, 0.1)],
        min_temp_c: 680,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 200.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2024,
        name: "BSCCO (Powder-in-Tube)",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Silver, 0.3), (S::Copper, 0.3), (S::Calcium, 0.3)],
        outputs: &[(S::YBCO, 0.7)],
        byproducts: &[(S::CarbonDioxide, 0.1)],
        min_temp_c: 840,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 48.0,
        cross_recipe_group: None,
    },
    // ===== SEMICONDUCTORS =====
    Recipe {
        id: 2040,
        name: "GaAs (Czochralski Growth)",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Gallium, 0.5), (S::Arsenic, 0.5)],
        outputs: &[(S::GalliumArsenide, 0.9)],
        byproducts: &[],
        min_temp_c: 1238,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 24.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2041,
        name: "GaN (MOCVD)",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Gallium, 0.4), (S::Ammonia, 0.6)],
        outputs: &[(S::GalliumNitride, 0.5)],
        byproducts: &[(S::HydrogenGas, 0.3)],
        min_temp_c: 1050,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 4.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2042,
        name: "SiC (Physical Vapor Transport)",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Silicon, 0.5), (S::Carbon, 0.5)],
        outputs: &[(S::SiliconCarbideSemi, 0.8)],
        byproducts: &[],
        min_temp_c: 2300,
        pressure_atm: 0.01,
        catalyst: None,
        duration_hours: 72.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2043,
        name: "InP (LEC Growth)",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Tin, 0.5), (S::Phosphorus, 0.5)],
        outputs: &[(S::IndiuPhosphide, 0.8)],
        byproducts: &[],
        min_temp_c: 1062,
        pressure_atm: 60.0,
        catalyst: None,
        duration_hours: 24.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2044,
        name: "CdTe Solar Cell (CSS)",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Zinc, 0.5), (S::Sulfur, 0.5)],
        outputs: &[(S::CdTeSolar, 0.8)],
        byproducts: &[],
        min_temp_c: 620,
        pressure_atm: 0.01,
        catalyst: None,
        duration_hours: 1.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2045,
        name: "CIGS Solar Cell (Co-evaporation)",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Copper, 0.3), (S::Tin, 0.3), (S::Sulfur, 0.4)],
        outputs: &[(S::CIGSSolar, 0.7)],
        byproducts: &[],
        min_temp_c: 550,
        pressure_atm: 0.001,
        catalyst: None,
        duration_hours: 2.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2046,
        name: "Perovskite Solar Cell (Spin Coating)",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Lead, 0.3), (S::Methanol, 0.7)],
        outputs: &[(S::PerovskiteSolar, 0.5)],
        byproducts: &[(S::Methanol, 0.3)],
        min_temp_c: 100,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 1.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2047,
        name: "Ge Zone Refining",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Silicon, 1.0)],
        outputs: &[(S::Silicon, 0.95)],
        byproducts: &[(S::Slag, 0.05)],
        min_temp_c: 938,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 8.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2048,
        name: "Si Wafer Slicing",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Silicon, 1.0)],
        outputs: &[(S::Silicon, 0.6)],
        byproducts: &[(S::SilicaSand, 0.35)],
        min_temp_c: 20,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 0.5,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2049,
        name: "Photoresist Lithography",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Silicon, 0.5), (S::Formaldehyde, 0.3)],
        outputs: &[(S::Silicon, 0.5)],
        byproducts: &[(S::Formaldehyde, 0.1)],
        min_temp_c: 115,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 0.1,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2050,
        name: "CVD Silicon Epitaxy",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Silicon, 0.3), (S::HydrogenGas, 0.5)],
        outputs: &[(S::Silicon, 0.4)],
        byproducts: &[(S::HydrogenGas, 0.2)],
        min_temp_c: 1100,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 2.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2051,
        name: "ALD Al2O3 Deposition",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Aluminum, 0.2), (S::Water, 0.3)],
        outputs: &[(S::Alumina, 0.3)],
        byproducts: &[(S::Methane, 0.1)],
        min_temp_c: 200,
        pressure_atm: 0.01,
        catalyst: None,
        duration_hours: 4.0,
        cross_recipe_group: None,
    },
    // ===== ADVANCED CERAMICS =====
    Recipe {
        id: 2060,
        name: "Si3N4 Hot Pressing",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Silicon, 0.6), (S::Nitrogen, 0.4)],
        outputs: &[(S::SiliconNitrideCeramic, 0.9)],
        byproducts: &[],
        min_temp_c: 1750,
        pressure_atm: 200.0,
        catalyst: None,
        duration_hours: 4.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2061,
        name: "B4C Carbothermic Reduction",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Carbon, 0.5), (S::Silicon, 0.5)],
        outputs: &[(S::BoronCarbide, 0.7)],
        byproducts: &[(S::CarbonDioxide, 0.2)],
        min_temp_c: 2300,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 6.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2062,
        name: "AlN Carbothermal Reduction",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Alumina, 0.5), (S::Carbon, 0.3), (S::Nitrogen, 0.3)],
        outputs: &[(S::AluminumNitride, 0.7)],
        byproducts: &[(S::CarbonDioxide, 0.2)],
        min_temp_c: 1700,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 4.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2063,
        name: "YSZ Sintering",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::SilicaSand, 0.6), (S::Calcium, 0.4)],
        outputs: &[(S::YSZ, 0.8)],
        byproducts: &[],
        min_temp_c: 1450,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 8.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2064,
        name: "PZT Piezoelectric Ceramic",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Lead, 0.4), (S::Titanium, 0.3), (S::SilicaSand, 0.3)],
        outputs: &[(S::PZT, 0.8)],
        byproducts: &[(S::CarbonDioxide, 0.1)],
        min_temp_c: 1250,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 6.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2065,
        name: "Barium Ferrite Magnets",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Iron, 0.6), (S::Calcium, 0.4)],
        outputs: &[(S::BariumFerrite, 0.8)],
        byproducts: &[(S::CarbonDioxide, 0.1)],
        min_temp_c: 1200,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 4.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2066,
        name: "Sapphire (Verneuil Process)",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Alumina, 1.0)],
        outputs: &[(S::Sapphire, 0.9)],
        byproducts: &[],
        min_temp_c: 2050,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 6.0,
        cross_recipe_group: None,
    },
    // ===== COMPOSITES =====
    Recipe {
        id: 2080,
        name: "Carbon Fiber (PAN Precursor)",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::NylonResin, 1.0)],
        outputs: &[(S::CarbonFiber, 0.5)],
        byproducts: &[(S::HydrogenCyanide, 0.1), (S::Nitrogen, 0.1)],
        min_temp_c: 1500,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 2.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2081,
        name: "CFRP (Autoclave Cure)",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::CarbonFiber, 0.6), (S::NylonResin, 0.4)],
        outputs: &[(S::CFRP, 1.0)],
        byproducts: &[],
        min_temp_c: 180,
        pressure_atm: 7.0,
        catalyst: None,
        duration_hours: 4.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2082,
        name: "Kevlar (Dry-Jet Wet Spinning)",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Aniline, 0.5), (S::TerephthalicAcid, 0.5)],
        outputs: &[(S::Kevlar, 0.8)],
        byproducts: &[(S::Water, 0.1), (S::HydrochloricAcid, 0.05)],
        min_temp_c: 80,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 1.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2083,
        name: "UHMWPE (Gel Spinning)",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Polyethylene, 1.0)],
        outputs: &[(S::UHMWPE, 0.9)],
        byproducts: &[],
        min_temp_c: 150,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 2.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2084,
        name: "Fiber Reinforced Concrete",
        category: RecipeCategory::Construction,
        inputs: &[(S::Concrete, 0.9), (S::LowCarbonSteel, 0.1)],
        outputs: &[(S::ReinforcedConcrete, 1.0)],
        byproducts: &[],
        min_temp_c: 20,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 24.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2085,
        name: "WC-Co Cermet (Sintering)",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Tungsten, 0.5), (S::Carbon, 0.3), (S::Cobalt, 0.2)],
        outputs: &[(S::TungstenCarbide, 0.9)],
        byproducts: &[],
        min_temp_c: 1400,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 4.0,
        cross_recipe_group: None,
    },
    // ===== BIOMATERIALS =====
    Recipe {
        id: 2100,
        name: "Hydroxyapatite (Precipitation)",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Calcium, 0.4), (S::Phosphorus, 0.3), (S::Water, 0.3)],
        outputs: &[(S::Hydroxyapatite, 0.7)],
        byproducts: &[(S::Water, 0.2)],
        min_temp_c: 80,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 4.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2101,
        name: "Bioactive Glass 45S5 (Melt-Quench)",
        category: RecipeCategory::Manufacturing,
        inputs: &[
            (S::SilicaSand, 0.45),
            (S::SodaAsh, 0.25),
            (S::Calcium, 0.2),
            (S::Phosphorus, 0.1),
        ],
        outputs: &[(S::BioactiveGlass, 0.9)],
        byproducts: &[(S::CarbonDioxide, 0.1)],
        min_temp_c: 1380,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 2.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2102,
        name: "PLA from Lactic Acid (Ring-Opening)",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Glucose, 0.8), (S::Tin, 0.01)],
        outputs: &[(S::PLA, 0.6)],
        byproducts: &[(S::Water, 0.15)],
        min_temp_c: 180,
        pressure_atm: 1.0,
        catalyst: Some(S::Tin),
        duration_hours: 12.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2103,
        name: "Chitosan (Deacetylation)",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Chitin, 0.7), (S::SodiumHydroxide, 0.5)],
        outputs: &[(S::Chitosan, 0.6)],
        byproducts: &[(S::AceticAcid, 0.2), (S::Water, 0.2)],
        min_temp_c: 120,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 6.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2104,
        name: "Collagen Extraction (Acid-Soluble)",
        category: RecipeCategory::BiologicalMaterial,
        inputs: &[(S::Water, 0.8), (S::AceticAcid, 0.2)],
        outputs: &[(S::Gelatin, 0.3)],
        byproducts: &[(S::Water, 0.5)],
        min_temp_c: 4,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 48.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2105,
        name: "PGA Sutures (Polycondensation)",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Glucose, 0.8), (S::Tin, 0.01)],
        outputs: &[(S::PLA, 0.55)],
        byproducts: &[(S::Water, 0.2)],
        min_temp_c: 220,
        pressure_atm: 1.0,
        catalyst: Some(S::Tin),
        duration_hours: 8.0,
        cross_recipe_group: None,
    },
    // ===== ENERGY MATERIALS =====
    Recipe {
        id: 2120,
        name: "Si Solar Cell (PERC Process)",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Silicon, 1.0)],
        outputs: &[(S::SiliconSolarCell, 0.9)],
        byproducts: &[(S::SilicaSand, 0.05)],
        min_temp_c: 850,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 6.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2121,
        name: "LFP Cathode (Solid-State)",
        category: RecipeCategory::Manufacturing,
        inputs: &[
            (S::Lithium, 0.2),
            (S::Iron, 0.3),
            (S::Phosphorus, 0.2),
            (S::Carbon, 0.1),
        ],
        outputs: &[(S::NMCCathode, 0.7)],
        byproducts: &[(S::CarbonDioxide, 0.05)],
        min_temp_c: 720,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 12.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2122,
        name: "NMC 811 Cathode (Co-precipitation)",
        category: RecipeCategory::Manufacturing,
        inputs: &[
            (S::Lithium, 0.15),
            (S::Nickel, 0.4),
            (S::Manganese, 0.1),
            (S::Cobalt, 0.05),
        ],
        outputs: &[(S::NMCCathode, 0.6)],
        byproducts: &[(S::Water, 0.05)],
        min_temp_c: 780,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 16.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2123,
        name: "LLZO Solid Electrolyte (Sintering)",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Lithium, 0.3), (S::Calcium, 0.3), (S::SilicaSand, 0.4)],
        outputs: &[(S::SolidElectrolyte, 0.8)],
        byproducts: &[(S::CarbonDioxide, 0.1)],
        min_temp_c: 1180,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 12.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2124,
        name: "LaNi5 Metal Hydride (Arc Melt)",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Calcium, 0.4), (S::Nickel, 0.6)],
        outputs: &[(S::MetalHydride, 0.9)],
        byproducts: &[],
        min_temp_c: 1000,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 2.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2125,
        name: "Bi2Te3 Thermoelectric (Bridgman)",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Lead, 0.3), (S::Sulfur, 0.3), (S::Tin, 0.3)],
        outputs: &[(S::BiTe, 0.7)],
        byproducts: &[],
        min_temp_c: 450,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 24.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2126,
        name: "Optical Fiber (MCVD)",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::SilicaSand, 0.7), (S::Chloroform, 0.3)],
        outputs: &[(S::OpticalFiber, 0.6)],
        byproducts: &[(S::HydrochloricAcid, 0.1), (S::CarbonDioxide, 0.05)],
        min_temp_c: 2000,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 8.0,
        cross_recipe_group: None,
    },
    // ===== SURFACE TREATMENTS =====
    Recipe {
        id: 2140,
        name: "Ion Implantation Doping",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Silicon, 0.9), (S::Phosphorus, 0.1)],
        outputs: &[(S::Silicon, 0.95)],
        byproducts: &[],
        min_temp_c: 1000,
        pressure_atm: 0.001,
        catalyst: None,
        duration_hours: 0.5,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2141,
        name: "Thermal Oxidation SiO2",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Silicon, 0.8), (S::Oxygen, 0.2)],
        outputs: &[(S::SilicaSand, 0.9)],
        byproducts: &[],
        min_temp_c: 1000,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 2.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2142,
        name: "PVD Sputtering (Metal Coating)",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Titanium, 0.3), (S::Nitrogen, 0.2), (S::Argon, 0.5)],
        outputs: &[(S::Titanium, 0.25)],
        byproducts: &[(S::Argon, 0.45)],
        min_temp_c: 300,
        pressure_atm: 0.001,
        catalyst: None,
        duration_hours: 1.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2143,
        name: "Electroless Nickel Plating",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Nickel, 0.4), (S::Phosphorus, 0.1)],
        outputs: &[(S::NickelPlating, 0.4)],
        byproducts: &[(S::HydrogenGas, 0.05)],
        min_temp_c: 90,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 2.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2144,
        name: "Shot Peening",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::LowCarbonSteel, 1.0)],
        outputs: &[(S::LowCarbonSteel, 1.0)],
        byproducts: &[],
        min_temp_c: 20,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 0.5,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2145,
        name: "Phosphating (Iron Phosphate)",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Iron, 0.8), (S::PhosphoricAcid, 0.3)],
        outputs: &[(S::Iron, 0.85)],
        byproducts: &[(S::HydrogenGas, 0.05), (S::Water, 0.1)],
        min_temp_c: 70,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 0.5,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2146,
        name: "Black Oxide Coating",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Iron, 0.8), (S::SodiumHydroxide, 0.3)],
        outputs: &[(S::Iron, 0.85)],
        byproducts: &[(S::Water, 0.1)],
        min_temp_c: 140,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 0.5,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2147,
        name: "Plasma Nitriding",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::LowCarbonSteel, 0.9), (S::Nitrogen, 0.2)],
        outputs: &[(S::LowCarbonSteel, 0.95)],
        byproducts: &[(S::HydrogenGas, 0.05)],
        min_temp_c: 500,
        pressure_atm: 0.01,
        catalyst: None,
        duration_hours: 12.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2148,
        name: "DLC Coating (PECVD)",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Carbon, 0.3), (S::HydrogenGas, 0.3)],
        outputs: &[(S::Carbon, 0.25)],
        byproducts: &[(S::HydrogenGas, 0.15)],
        min_temp_c: 200,
        pressure_atm: 0.01,
        catalyst: None,
        duration_hours: 2.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 2149,
        name: "Thermal Barrier Coating YSZ (Plasma Spray)",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::SilicaSand, 0.5), (S::Calcium, 0.3)],
        outputs: &[(S::YSZ, 0.6)],
        byproducts: &[],
        min_temp_c: 10000,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 0.1,
        cross_recipe_group: None,
    },
];
