#![allow(dead_code)]
use super::types::*;
use super::substance::Substance as S;

const CRG_SULFURIC_ACID: u32 = 100;
const CRG_HYDROGEN: u32 = 11;
const CRG_ETHANOL: u32 = 102;
const CRG_SOAP: u32 = 103;

pub static CHEMISTRY_RECIPES: &[Recipe] = &[
    // ===== MAJOR INDUSTRIAL PROCESSES =====
    Recipe { id: 300, name: "Haber-Bosch (Ammonia)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Nitrogen, 0.82), (S::HydrogenGas, 0.18)],
        outputs: &[(S::Ammonia, 1.0)],
        byproducts: &[],
        min_temp_c: 450, pressure_atm: 200.0, catalyst: Some(S::Iron), duration_hours: 0.5,
        cross_recipe_group: None },
    Recipe { id: 301, name: "Contact Process (Sulfuric Acid from S)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Sulfur, 0.33), (S::Oxygen, 0.49), (S::Water, 0.18)],
        outputs: &[(S::SulfuricAcid, 1.0)],
        byproducts: &[],
        min_temp_c: 450, pressure_atm: 2.0, catalyst: Some(S::Vanadium), duration_hours: 2.0,
        cross_recipe_group: Some(CRG_SULFURIC_ACID) },
    Recipe { id: 302, name: "Sulfuric Acid from Pyrite Roast Gas", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::PyriteOre, 1.0), (S::Oxygen, 0.5), (S::Water, 0.2)],
        outputs: &[(S::SulfuricAcid, 0.8)],
        byproducts: &[(S::Hematite, 0.5)],
        min_temp_c: 450, pressure_atm: 2.0, catalyst: Some(S::Vanadium), duration_hours: 4.0,
        cross_recipe_group: Some(CRG_SULFURIC_ACID) },
    Recipe { id: 303, name: "Ostwald Process (Nitric Acid)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Ammonia, 0.26), (S::Oxygen, 0.61), (S::Water, 0.13)],
        outputs: &[(S::NitricAcid, 1.0)],
        byproducts: &[],
        min_temp_c: 900, pressure_atm: 8.0, catalyst: Some(S::Platinum), duration_hours: 1.0,
        cross_recipe_group: None },
    Recipe { id: 304, name: "Solvay Process (Soda Ash)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Salt, 1.2), (S::Limestone, 1.0), (S::Ammonia, 0.01)],
        outputs: &[(S::SodaAsh, 1.0)],
        byproducts: &[(S::Calcium, 0.5)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 12.0,
        cross_recipe_group: None },
    Recipe { id: 305, name: "Chloralkali (NaOH + Cl2)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Salt, 1.2), (S::Water, 0.4)],
        outputs: &[(S::SodiumHydroxide, 0.8), (S::ChlorineGas, 0.7), (S::HydrogenGas, 0.02)],
        byproducts: &[],
        min_temp_c: 80, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0,
        cross_recipe_group: None },
    Recipe { id: 306, name: "Fischer-Tropsch (Syngas → Fuel)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::SynGas, 2.5)],
        outputs: &[(S::Diesel, 1.0)],
        byproducts: &[(S::Water, 0.8)],
        min_temp_c: 220, pressure_atm: 25.0, catalyst: Some(S::Cobalt), duration_hours: 8.0,
        cross_recipe_group: None },
    Recipe { id: 307, name: "Steam Methane Reforming (Syngas)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::NaturalGas, 0.6), (S::Steam, 0.4)],
        outputs: &[(S::SynGas, 1.0)],
        byproducts: &[],
        min_temp_c: 850, pressure_atm: 25.0, catalyst: Some(S::Nickel), duration_hours: 1.0,
        cross_recipe_group: None },

    // ===== HYDROGEN (3 paths) =====
    Recipe { id: 310, name: "Water Electrolysis (Hydrogen)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Water, 9.0)],
        outputs: &[(S::HydrogenGas, 1.0), (S::Oxygen, 8.0)],
        byproducts: &[],
        min_temp_c: 70, pressure_atm: 1.0, catalyst: None, duration_hours: 2.0,
        cross_recipe_group: Some(CRG_HYDROGEN) },
    Recipe { id: 311, name: "Steam Reforming (Hydrogen)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::NaturalGas, 3.0), (S::Steam, 6.0)],
        outputs: &[(S::HydrogenGas, 1.0)],
        byproducts: &[(S::Carbon, 2.5)],
        min_temp_c: 850, pressure_atm: 25.0, catalyst: Some(S::Nickel), duration_hours: 1.0,
        cross_recipe_group: Some(CRG_HYDROGEN) },

    // ===== POLYMERS =====
    Recipe { id: 320, name: "Polyethylene (LDPE)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::NaturalGas, 1.2)],
        outputs: &[(S::Polyethylene, 1.0)],
        byproducts: &[],
        min_temp_c: 200, pressure_atm: 2000.0, catalyst: None, duration_hours: 2.0,
        cross_recipe_group: None },
    Recipe { id: 321, name: "Nylon 6,6", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::CrudeOil, 2.0), (S::Ammonia, 0.3)],
        outputs: &[(S::NylonResin, 1.0)],
        byproducts: &[(S::Water, 0.5)],
        min_temp_c: 280, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0,
        cross_recipe_group: None },
    Recipe { id: 322, name: "PVC", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::CrudeOil, 0.6), (S::ChlorineGas, 0.4)],
        outputs: &[(S::PVC, 1.0)],
        byproducts: &[],
        min_temp_c: 55, pressure_atm: 1.0, catalyst: None, duration_hours: 6.0,
        cross_recipe_group: None },
    Recipe { id: 323, name: "Synthetic Rubber (SBR)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::CrudeOil, 1.5), (S::Sulfur, 0.05)],
        outputs: &[(S::SyntheticRubber, 1.0)],
        byproducts: &[],
        min_temp_c: 50, pressure_atm: 1.0, catalyst: None, duration_hours: 8.0,
        cross_recipe_group: None },

    // ===== EXPLOSIVES =====
    Recipe { id: 330, name: "Gunpowder", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Salt, 0.75), (S::Charcoal, 0.15), (S::Sulfur, 0.10)],
        outputs: &[(S::Gunpowder, 1.0)],
        byproducts: &[],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 2.0,
        cross_recipe_group: None },
    Recipe { id: 331, name: "Nitroglycerin", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Glycerol, 0.4), (S::NitricAcid, 0.5), (S::SulfuricAcid, 0.3)],
        outputs: &[(S::Nitroglycerin, 1.0)],
        byproducts: &[(S::Water, 0.2)],
        min_temp_c: 5, pressure_atm: 1.0, catalyst: None, duration_hours: 1.0,
        cross_recipe_group: None },
    Recipe { id: 332, name: "Dynamite", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Nitroglycerin, 0.75), (S::DiatomaceousEarth, 0.25)],
        outputs: &[(S::Dynamite, 1.0)],
        byproducts: &[],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.5,
        cross_recipe_group: None },
    Recipe { id: 333, name: "TNT", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Toluene, 0.4), (S::NitricAcid, 0.4), (S::SulfuricAcid, 0.3)],
        outputs: &[(S::TNT, 1.0)],
        byproducts: &[(S::Water, 0.2)],
        min_temp_c: 80, pressure_atm: 1.0, catalyst: None, duration_hours: 6.0,
        cross_recipe_group: None },
    Recipe { id: 334, name: "Ammonium Nitrate", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Ammonia, 0.21), (S::NitricAcid, 0.79)],
        outputs: &[(S::AmmoniumNitrate, 1.0)],
        byproducts: &[],
        min_temp_c: 50, pressure_atm: 1.0, catalyst: None, duration_hours: 1.0,
        cross_recipe_group: None },
    Recipe { id: 335, name: "Urea", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Ammonia, 0.57), (S::Carbon, 0.20)],
        outputs: &[(S::Urea, 1.0)],
        byproducts: &[(S::Water, 0.3)],
        min_temp_c: 180, pressure_atm: 200.0, catalyst: None, duration_hours: 2.0,
        cross_recipe_group: None },

    // ===== OTHER CHEMICALS =====
    Recipe { id: 340, name: "Calcium Carbide", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Quicklite, 0.9), (S::Coke, 0.6)],
        outputs: &[(S::CalciumCarbide, 1.0)],
        byproducts: &[],
        min_temp_c: 2000, pressure_atm: 1.0, catalyst: None, duration_hours: 2.0,
        cross_recipe_group: None },
    Recipe { id: 341, name: "Acetylene from Carbide", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::CalciumCarbide, 1.0), (S::Water, 0.6)],
        outputs: &[(S::Acetylene, 0.4)],
        byproducts: &[(S::SlakedLite, 1.2)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.1,
        cross_recipe_group: None },
    Recipe { id: 342, name: "Bleach (Sodium Hypochlorite)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::ChlorineGas, 0.5), (S::SodiumHydroxide, 0.6)],
        outputs: &[(S::BleachSolution, 1.0)],
        byproducts: &[(S::Salt, 0.08)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.2,
        cross_recipe_group: None },
    Recipe { id: 343, name: "Phosphoric Acid (Wet Process)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::PhosphateRock, 1.5), (S::SulfuricAcid, 1.5)],
        outputs: &[(S::PhosphoricAcid, 1.0)],
        byproducts: &[(S::Calcium, 1.0)],
        min_temp_c: 80, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0,
        cross_recipe_group: None },
    Recipe { id: 344, name: "Hydrochloric Acid", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::ChlorineGas, 0.7), (S::HydrogenGas, 0.03)],
        outputs: &[(S::HydrochloricAcid, 1.0)],
        byproducts: &[],
        min_temp_c: 200, pressure_atm: 1.0, catalyst: None, duration_hours: 0.5,
        cross_recipe_group: None },
    Recipe { id: 345, name: "Hydrogen Peroxide", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::HydrogenGas, 0.06), (S::Oxygen, 0.94)],
        outputs: &[(S::HydrogenPeroxide, 1.0)],
        byproducts: &[],
        min_temp_c: 40, pressure_atm: 3.0, catalyst: Some(S::Nickel), duration_hours: 4.0,
        cross_recipe_group: None },
    Recipe { id: 346, name: "Formaldehyde", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Methanol, 0.9), (S::Oxygen, 0.1)],
        outputs: &[(S::Formaldehyde, 1.0)],
        byproducts: &[(S::Water, 0.2)],
        min_temp_c: 600, pressure_atm: 1.0, catalyst: Some(S::Silver), duration_hours: 0.5,
        cross_recipe_group: None },

    // ===== SOAP (2 paths) =====
    Recipe { id: 350, name: "Soap (Cold Process)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::OliveOil, 0.8), (S::SodiumHydroxide, 0.12), (S::Water, 0.2)],
        outputs: &[(S::SoapProduct, 1.0)],
        byproducts: &[(S::Glycerol, 0.1)],
        min_temp_c: 40, pressure_atm: 1.0, catalyst: None, duration_hours: 1008.0,
        cross_recipe_group: Some(CRG_SOAP) },
    Recipe { id: 351, name: "Soap (Hot Process)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::OliveOil, 0.8), (S::SodiumHydroxide, 0.12), (S::Water, 0.2)],
        outputs: &[(S::SoapProduct, 1.0)],
        byproducts: &[(S::Glycerol, 0.1)],
        min_temp_c: 75, pressure_atm: 1.0, catalyst: None, duration_hours: 3.0,
        cross_recipe_group: Some(CRG_SOAP) },

    // ===== VULCANIZATION =====
    Recipe { id: 355, name: "Rubber Vulcanization", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::NaturalRubber, 0.95), (S::Sulfur, 0.03), (S::Zinc, 0.02)],
        outputs: &[(S::VulcanizedRubber, 1.0)],
        byproducts: &[],
        min_temp_c: 150, pressure_atm: 3.0, catalyst: None, duration_hours: 0.5,
        cross_recipe_group: None },

    // ===== MORE POLYMERS =====
    Recipe { id: 360, name: "Polyester (PET)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::CrudeOil, 1.5)],
        outputs: &[(S::PolyesterFiber, 1.0)],
        byproducts: &[(S::Water, 0.3)],
        min_temp_c: 280, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: None },
    Recipe { id: 361, name: "Polypropylene", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::CrudeOil, 1.3)],
        outputs: &[(S::Polyethylene, 1.0)], // PP placeholder
        byproducts: &[],
        min_temp_c: 70, pressure_atm: 30.0, catalyst: Some(S::Titanium), duration_hours: 3.0, cross_recipe_group: None },
    Recipe { id: 362, name: "Polystyrene", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Benzene, 0.6), (S::CrudeOil, 0.5)],
        outputs: &[(S::Polyethylene, 1.0)], // PS placeholder
        byproducts: &[],
        min_temp_c: 120, pressure_atm: 1.0, catalyst: None, duration_hours: 6.0, cross_recipe_group: None },
    Recipe { id: 363, name: "Acrylic Fiber", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::CrudeOil, 1.2), (S::Ammonia, 0.2)],
        outputs: &[(S::NylonFiber, 1.0)], // acrylic placeholder
        byproducts: &[],
        min_temp_c: 55, pressure_atm: 1.0, catalyst: None, duration_hours: 8.0, cross_recipe_group: None },

    // ===== PHARMACEUTICAL =====
    Recipe { id: 370, name: "Aspirin Synthesis", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::CrudeOil, 0.5), (S::SulfuricAcid, 0.1)],
        outputs: &[(S::SoapProduct, 0.9)], // aspirin placeholder
        byproducts: &[(S::Water, 0.1)],
        min_temp_c: 90, pressure_atm: 1.0, catalyst: Some(S::PhosphoricAcid), duration_hours: 0.5, cross_recipe_group: None },
    Recipe { id: 371, name: "Penicillin Fermentation", category: RecipeCategory::FoodBiological,
        inputs: &[(S::Sugar, 2.0), (S::Water, 10.0)],
        outputs: &[(S::SoapProduct, 0.04)], // penicillin placeholder
        byproducts: &[(S::Water, 10.0)],
        min_temp_c: 26, pressure_atm: 1.0, catalyst: None, duration_hours: 168.0, cross_recipe_group: None },

    // ===== SEMICONDUCTOR =====
    Recipe { id: 375, name: "Trichlorosilane (for Siemens)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Silicon, 1.0), (S::HydrochloricAcid, 3.5)],
        outputs: &[(S::TitaniumTetrachloride, 1.0)], // SiHCl3 placeholder
        byproducts: &[(S::HydrogenGas, 0.1)],
        min_temp_c: 320, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: None },

    // ===== WATER TREATMENT =====
    Recipe { id: 380, name: "Potable Water (Chlorination)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Water, 1000.0), (S::ChlorineGas, 0.002)],
        outputs: &[(S::Water, 1000.0)],
        byproducts: &[],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.5, cross_recipe_group: None },
    Recipe { id: 381, name: "Distilled Water", category: RecipeCategory::Refining,
        inputs: &[(S::Water, 1.2)],
        outputs: &[(S::Water, 1.0)],
        byproducts: &[(S::Salt, 0.04)],
        min_temp_c: 100, pressure_atm: 1.0, catalyst: None, duration_hours: 2.0, cross_recipe_group: None },

    // ===== METHANOL =====
    Recipe { id: 385, name: "Methanol from Syngas", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::SynGas, 1.5)],
        outputs: &[(S::Methanol, 1.0)],
        byproducts: &[(S::Water, 0.3)],
        min_temp_c: 250, pressure_atm: 80.0, catalyst: Some(S::Copper), duration_hours: 2.0, cross_recipe_group: None },

    // ===== ACETONE =====
    Recipe { id: 386, name: "Acetone (Cumene Process)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Benzene, 0.5), (S::CrudeOil, 0.5)],
        outputs: &[(S::Acetone, 0.4)],
        byproducts: &[(S::SoapProduct, 0.6)], // phenol byproduct
        min_temp_c: 90, pressure_atm: 1.0, catalyst: Some(S::SulfuricAcid), duration_hours: 3.0, cross_recipe_group: None },

    // ===== TOLUENE =====
    Recipe { id: 387, name: "Toluene (Catalytic Reforming)", category: RecipeCategory::Refining,
        inputs: &[(S::CrudeOil, 1.5)],
        outputs: &[(S::Toluene, 1.0)],
        byproducts: &[(S::HydrogenGas, 0.05)],
        min_temp_c: 500, pressure_atm: 25.0, catalyst: Some(S::Platinum), duration_hours: 2.0, cross_recipe_group: None },

    // ===== BENZENE =====
    Recipe { id: 388, name: "Benzene (Catalytic Reforming)", category: RecipeCategory::Refining,
        inputs: &[(S::CrudeOil, 1.5)],
        outputs: &[(S::Benzene, 1.0)],
        byproducts: &[(S::HydrogenGas, 0.05)],
        min_temp_c: 500, pressure_atm: 25.0, catalyst: Some(S::Platinum), duration_hours: 2.0, cross_recipe_group: None },

    // ===== GLYCEROL =====
    Recipe { id: 389, name: "Glycerol (from Biodiesel)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::OliveOil, 1.0), (S::Methanol, 0.15)],
        outputs: &[(S::Biodiesel, 1.0), (S::Glycerol, 0.1)],
        byproducts: &[],
        min_temp_c: 55, pressure_atm: 1.0, catalyst: Some(S::SodiumHydroxide), duration_hours: 2.0, cross_recipe_group: None },

    // ===== SALTPETER =====
    Recipe { id: 390, name: "Saltpeter (Niter Bed)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::StrawFiber, 5.0), (S::Water, 10.0), (S::Charcoal, 1.0)],
        outputs: &[(S::Salt, 0.5)], // KNO3 placeholder
        byproducts: &[(S::Water, 8.0)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 8760.0, cross_recipe_group: None },

    // ===== ESSENTIAL OIL =====
    Recipe { id: 391, name: "Essential Oil (Steam Distillation)", category: RecipeCategory::Refining,
        inputs: &[(S::StrawFiber, 50.0), (S::Steam, 20.0)],
        outputs: &[(S::OliveOil, 1.0)], // essential oil placeholder
        byproducts: &[(S::Water, 60.0)],
        min_temp_c: 100, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: None },

    // ===== SMOKELESS POWDER =====
    Recipe { id: 392, name: "Smokeless Powder (Nitrocellulose)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::CottonFiber, 0.5), (S::NitricAcid, 1.0), (S::SulfuricAcid, 1.0)],
        outputs: &[(S::Gunpowder, 0.8)], // smokeless powder placeholder
        byproducts: &[(S::Water, 1.0)],
        min_temp_c: 30, pressure_atm: 1.0, catalyst: None, duration_hours: 2.0, cross_recipe_group: None },

    // ===== PHOTOGRAPHIC =====
    Recipe { id: 393, name: "Silver Nitrate", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Silver, 0.63), (S::NitricAcid, 0.37)],
        outputs: &[(S::Silver, 1.0)], // AgNO3 placeholder
        byproducts: &[(S::Water, 0.1)],
        min_temp_c: 70, pressure_atm: 1.0, catalyst: None, duration_hours: 1.0, cross_recipe_group: None },

    // ===== INDUSTRIAL CHEMICAL PROCESSES =====
    Recipe { id: 2500, name: "Water-Gas Shift (CO+H2O→CO2+H2)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::SynGas, 0.6), (S::Steam, 0.4)],
        outputs: &[(S::CarbonDioxide, 0.5), (S::HydrogenGas, 0.5)],
        byproducts: &[],
        min_temp_c: 350, pressure_atm: 25.0, catalyst: Some(S::Iron), duration_hours: 1.0, cross_recipe_group: None },
    Recipe { id: 2501, name: "Sabatier Reaction (CO2+H2→CH4)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::CarbonDioxide, 0.55), (S::HydrogenGas, 0.45)],
        outputs: &[(S::Methane, 0.6)],
        byproducts: &[(S::Water, 0.4)],
        min_temp_c: 400, pressure_atm: 20.0, catalyst: Some(S::Nickel), duration_hours: 2.0, cross_recipe_group: None },
    Recipe { id: 2502, name: "Kolbe-Schmitt (Phenol→Salicylic Acid)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Phenol, 0.6), (S::CarbonDioxide, 0.3), (S::SodiumHydroxide, 0.1)],
        outputs: &[(S::SalicylicAcid, 0.9)],
        byproducts: &[(S::Water, 0.1)],
        min_temp_c: 125, pressure_atm: 5.0, catalyst: None, duration_hours: 6.0, cross_recipe_group: None },
    Recipe { id: 2503, name: "Grignard Reagent Formation (Mg+RBr→RMgBr)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Magnesium, 0.4), (S::DiethylEther, 0.6)],
        outputs: &[(S::Magnesium, 0.9)], // RMgBr placeholder
        byproducts: &[],
        min_temp_c: 35, pressure_atm: 1.0, catalyst: None, duration_hours: 2.0, cross_recipe_group: None },
    Recipe { id: 2504, name: "Friedel-Crafts Alkylation", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Benzene, 0.6), (S::ChlorineGas, 0.2)],
        outputs: &[(S::Toluene, 0.8)], // alkylbenzene placeholder
        byproducts: &[(S::HydrochloricAcid, 0.2)],
        min_temp_c: 50, pressure_atm: 1.0, catalyst: Some(S::Aluminum), duration_hours: 4.0, cross_recipe_group: None },
    Recipe { id: 2505, name: "Friedel-Crafts Acylation", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Benzene, 0.5), (S::ChlorineGas, 0.2), (S::CrudeOil, 0.3)],
        outputs: &[(S::Acetone, 0.8)], // aryl ketone placeholder
        byproducts: &[(S::HydrochloricAcid, 0.2)],
        min_temp_c: 50, pressure_atm: 1.0, catalyst: Some(S::Aluminum), duration_hours: 4.0, cross_recipe_group: None },
    Recipe { id: 2506, name: "Cannizzaro Reaction (2HCHO→MeOH+HCOOH)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Formaldehyde, 0.7), (S::SodiumHydroxide, 0.3)],
        outputs: &[(S::Methanol, 0.4), (S::SodiumFormate, 0.5)],
        byproducts: &[(S::Water, 0.1)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 2.0, cross_recipe_group: None },
    Recipe { id: 2507, name: "Aldol Condensation (Acetaldehyde→Crotonaldehyde)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Acetaldehyde, 0.8), (S::SodiumHydroxide, 0.1)],
        outputs: &[(S::Crotonaldehyde, 0.7)],
        byproducts: &[(S::Water, 0.2)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: None },
    Recipe { id: 2508, name: "Beckmann Rearrangement (Oxime→Amide)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Cyclohexanone, 0.6), (S::SulfuricAcid, 0.3), (S::Ammonia, 0.1)],
        outputs: &[(S::Caprolactam, 0.8)],
        byproducts: &[(S::Water, 0.2)],
        min_temp_c: 130, pressure_atm: 1.0, catalyst: None, duration_hours: 2.0, cross_recipe_group: None },
    Recipe { id: 2509, name: "Hofmann Degradation (Amide→Amine)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Urea, 0.5), (S::SodiumHydroxide, 0.3), (S::ChlorineGas, 0.2)],
        outputs: &[(S::Aniline, 0.6)], // amine placeholder
        byproducts: &[(S::SodiumChloride, 0.2), (S::Water, 0.2)],
        min_temp_c: 70, pressure_atm: 1.0, catalyst: None, duration_hours: 3.0, cross_recipe_group: None },
    Recipe { id: 2510, name: "Diels-Alder (Butadiene+Ethylene→Cyclohexene)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Butadiene, 0.6), (S::Ethylene, 0.4)],
        outputs: &[(S::Cyclohexene, 1.0)],
        byproducts: &[],
        min_temp_c: 200, pressure_atm: 50.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: None },
    Recipe { id: 2511, name: "Hydroformylation (Alkene+CO+H2→Aldehyde)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Propylene, 0.5), (S::SynGas, 0.5)],
        outputs: &[(S::Butanol, 0.9)], // butanal → butanol placeholder
        byproducts: &[(S::Water, 0.1)],
        min_temp_c: 150, pressure_atm: 30.0, catalyst: Some(S::Cobalt), duration_hours: 3.0, cross_recipe_group: None },
    Recipe { id: 2512, name: "Olefin Metathesis (2 Propylene→Ethylene+Butene)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Propylene, 1.0)],
        outputs: &[(S::Ethylene, 0.5), (S::Butadiene, 0.5)],
        byproducts: &[],
        min_temp_c: 50, pressure_atm: 5.0, catalyst: Some(S::Tungsten), duration_hours: 2.0, cross_recipe_group: None },
    Recipe { id: 2513, name: "Ziegler-Natta Polymerization (Ethylene→HDPE)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Ethylene, 1.0)],
        outputs: &[(S::HDPE, 1.0)],
        byproducts: &[],
        min_temp_c: 70, pressure_atm: 30.0, catalyst: Some(S::Titanium), duration_hours: 3.0, cross_recipe_group: None },
    Recipe { id: 2514, name: "Emulsion Polymerization (SBR Latex)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Styrene, 0.3), (S::Butadiene, 0.6), (S::Water, 0.1)],
        outputs: &[(S::SBRLatex, 1.0)],
        byproducts: &[],
        min_temp_c: 50, pressure_atm: 5.0, catalyst: None, duration_hours: 8.0, cross_recipe_group: None },
    Recipe { id: 2515, name: "Suspension Polymerization (PVC Beads)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::VinylChloride, 0.9), (S::Water, 0.1)],
        outputs: &[(S::PVCBeads, 1.0)],
        byproducts: &[],
        min_temp_c: 55, pressure_atm: 10.0, catalyst: None, duration_hours: 6.0, cross_recipe_group: None },
    Recipe { id: 2516, name: "Condensation Polymerization (Diacid+Diamine→Polyamide)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::AdipicAcid, 0.5), (S::Caprolactam, 0.5)],
        outputs: &[(S::Polyamide, 1.0)],
        byproducts: &[(S::Water, 0.2)],
        min_temp_c: 280, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: None },
    Recipe { id: 2517, name: "Addition Polymerization (Monomer→Polymer)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Ethylene, 1.0)],
        outputs: &[(S::Polyethylene, 1.0)],
        byproducts: &[],
        min_temp_c: 200, pressure_atm: 1500.0, catalyst: None, duration_hours: 2.0, cross_recipe_group: None },
    Recipe { id: 2518, name: "Epoxidation (Alkene+Peracid→Epoxide)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Propylene, 0.6), (S::HydrogenPeroxide, 0.4)],
        outputs: &[(S::PropyleneOxide, 0.8)],
        byproducts: &[(S::Water, 0.2)],
        min_temp_c: 40, pressure_atm: 3.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: None },
    Recipe { id: 2519, name: "Hydroboration-Oxidation (Alkene→Alcohol)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Propylene, 0.5), (S::HydrogenPeroxide, 0.3), (S::SodiumHydroxide, 0.2)],
        outputs: &[(S::Isopropanol, 0.8)],
        byproducts: &[(S::Water, 0.2)],
        min_temp_c: 0, pressure_atm: 1.0, catalyst: None, duration_hours: 3.0, cross_recipe_group: None },
    Recipe { id: 2520, name: "Ozonolysis (Alkene+O3→Carbonyl)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Ethylene, 0.5), (S::Ozone, 0.5)],
        outputs: &[(S::Formaldehyde, 0.8)],
        byproducts: &[(S::Water, 0.2)],
        min_temp_c: -78, pressure_atm: 1.0, catalyst: None, duration_hours: 1.0, cross_recipe_group: None },
    Recipe { id: 2521, name: "LiAlH4 Reduction (Ester→Alcohol)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::EthylAcetate, 0.7), (S::Lithium, 0.2), (S::Aluminum, 0.1)],
        outputs: &[(S::Ethanol, 0.6), (S::Methanol, 0.2)],
        byproducts: &[(S::Alumina, 0.2)],
        min_temp_c: 0, pressure_atm: 1.0, catalyst: None, duration_hours: 2.0, cross_recipe_group: None },
    Recipe { id: 2522, name: "NaBH4 Reduction (Ketone→Alcohol)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Acetone, 0.7), (S::Sodium, 0.2), (S::Methanol, 0.1)],
        outputs: &[(S::Isopropanol, 0.8)],
        byproducts: &[(S::Water, 0.2)],
        min_temp_c: 0, pressure_atm: 1.0, catalyst: None, duration_hours: 1.0, cross_recipe_group: None },
    Recipe { id: 2523, name: "Jones Oxidation (Alcohol→Ketone)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Isopropanol, 0.6), (S::Chromium, 0.2), (S::SulfuricAcid, 0.2)],
        outputs: &[(S::Acetone, 0.7)],
        byproducts: &[(S::ChromeGreen, 0.2), (S::Water, 0.1)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 1.0, cross_recipe_group: None },
    Recipe { id: 2524, name: "Swern Oxidation (Alcohol→Aldehyde)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Ethanol, 0.5), (S::OxalicAcid, 0.3), (S::ChlorineGas, 0.2)],
        outputs: &[(S::Acetaldehyde, 0.7)],
        byproducts: &[(S::CarbonDioxide, 0.1), (S::SodiumChloride, 0.2)],
        min_temp_c: -78, pressure_atm: 1.0, catalyst: None, duration_hours: 1.0, cross_recipe_group: None },
    Recipe { id: 2525, name: "Claisen Condensation (2 Esters→Beta-Keto Ester)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::EthylAcetate, 0.8), (S::Sodium, 0.1), (S::Ethanol, 0.1)],
        outputs: &[(S::MethylEthylKetone, 0.7)], // beta-keto ester placeholder
        byproducts: &[(S::Ethanol, 0.3)],
        min_temp_c: 78, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: None },
    Recipe { id: 2526, name: "Michael Addition (Enolate+Conjugated Carbonyl)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::MethylEthylKetone, 0.5), (S::AcrylicAcid, 0.4), (S::SodiumHydroxide, 0.1)],
        outputs: &[(S::AdipicAcid, 0.8)], // 1,5-dicarbonyl placeholder
        byproducts: &[(S::Water, 0.2)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 6.0, cross_recipe_group: None },
    Recipe { id: 2527, name: "Wittig Reaction (Aldehyde+Ylide→Alkene)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Acetaldehyde, 0.5), (S::Phosphorus, 0.3), (S::Benzene, 0.2)],
        outputs: &[(S::Styrene, 0.7)], // substituted alkene placeholder
        byproducts: &[(S::PhosphoricAcid, 0.3)],
        min_temp_c: 0, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: None },
    Recipe { id: 2528, name: "Suzuki Coupling (ArX+ArB(OH)2→Biaryl)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Benzene, 0.5), (S::ChlorineGas, 0.2), (S::SodiumHydroxide, 0.1)],
        outputs: &[(S::Naphthalene, 0.7)], // biaryl placeholder
        byproducts: &[(S::SodiumChloride, 0.2), (S::Water, 0.1)],
        min_temp_c: 80, pressure_atm: 1.0, catalyst: Some(S::Platinum), duration_hours: 12.0, cross_recipe_group: None },
    Recipe { id: 2529, name: "Heck Reaction (ArX+Alkene→Substituted Alkene)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Benzene, 0.4), (S::Ethylene, 0.3), (S::ChlorineGas, 0.1)],
        outputs: &[(S::Styrene, 0.7)],
        byproducts: &[(S::HydrochloricAcid, 0.2)],
        min_temp_c: 120, pressure_atm: 1.0, catalyst: Some(S::Platinum), duration_hours: 8.0, cross_recipe_group: None },
    Recipe { id: 2530, name: "Sonogashira Coupling (ArX+Alkyne)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Benzene, 0.4), (S::Acetylene, 0.3), (S::ChlorineGas, 0.1)],
        outputs: &[(S::Naphthalene, 0.6)], // aryl alkyne placeholder
        byproducts: &[(S::HydrochloricAcid, 0.2)],
        min_temp_c: 60, pressure_atm: 1.0, catalyst: Some(S::Copper), duration_hours: 12.0, cross_recipe_group: None },
    Recipe { id: 2531, name: "Click Chemistry CuAAC (Azide+Alkyne→Triazole)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Acetylene, 0.4), (S::SodiumCyanide, 0.4), (S::Water, 0.2)],
        outputs: &[(S::Triazole, 0.9)],
        byproducts: &[(S::Water, 0.1)],
        min_temp_c: 25, pressure_atm: 1.0, catalyst: Some(S::Copper), duration_hours: 2.0, cross_recipe_group: None },
    Recipe { id: 2532, name: "Ring-Closing Metathesis (Diene→Cyclic Alkene)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Butadiene, 0.9), (S::Ethylene, 0.1)],
        outputs: &[(S::Cyclohexene, 0.8)],
        byproducts: &[(S::Ethylene, 0.2)],
        min_temp_c: 40, pressure_atm: 1.0, catalyst: Some(S::Tungsten), duration_hours: 6.0, cross_recipe_group: None },
    Recipe { id: 2533, name: "Hydrosilylation (Alkene+HSiR3→Alkylsilane)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Ethylene, 0.5), (S::Silicon, 0.5)],
        outputs: &[(S::Silicon, 0.9)], // alkylsilane placeholder
        byproducts: &[(S::HydrogenGas, 0.1)],
        min_temp_c: 80, pressure_atm: 1.0, catalyst: Some(S::Platinum), duration_hours: 4.0, cross_recipe_group: None },
    Recipe { id: 2534, name: "Sol-Gel (TEOS→SiO2)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Silicon, 0.4), (S::Ethanol, 0.4), (S::Water, 0.2)],
        outputs: &[(S::SilicaGelProduct, 0.8)],
        byproducts: &[(S::Ethanol, 0.2)],
        min_temp_c: 60, pressure_atm: 1.0, catalyst: Some(S::HydrochloricAcid), duration_hours: 24.0, cross_recipe_group: None },
    Recipe { id: 2535, name: "Silanization (Surface Functionalization)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Glass, 0.8), (S::Silicon, 0.15), (S::Ethanol, 0.05)],
        outputs: &[(S::Glass, 1.0)], // functionalized glass
        byproducts: &[],
        min_temp_c: 110, pressure_atm: 1.0, catalyst: None, duration_hours: 2.0, cross_recipe_group: None },
    Recipe { id: 2536, name: "Electrochemical CO2 Reduction (CO2→CO)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::CarbonDioxide, 0.6), (S::Water, 0.4)],
        outputs: &[(S::SynGas, 0.5)],
        byproducts: &[(S::Oxygen, 0.3), (S::Water, 0.2)],
        min_temp_c: 25, pressure_atm: 1.0, catalyst: Some(S::Copper), duration_hours: 8.0, cross_recipe_group: None },
    Recipe { id: 2537, name: "Photocatalytic Water Splitting (H2O→H2+O2)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Water, 1.0)],
        outputs: &[(S::HydrogenGas, 0.11), (S::Oxygen, 0.89)],
        byproducts: &[],
        min_temp_c: 25, pressure_atm: 1.0, catalyst: Some(S::Titanium), duration_hours: 12.0, cross_recipe_group: Some(CRG_HYDROGEN) },
    Recipe { id: 2538, name: "Biocatalysis (Enzyme+Substrate→Product)", category: RecipeCategory::FoodBiological,
        inputs: &[(S::Glucose, 0.8), (S::Water, 0.2)],
        outputs: &[(S::Ethanol, 0.5)],
        byproducts: &[(S::CarbonDioxide, 0.3), (S::Water, 0.2)],
        min_temp_c: 37, pressure_atm: 1.0, catalyst: None, duration_hours: 24.0, cross_recipe_group: None },
    Recipe { id: 2539, name: "Enzymatic Hydrolysis (Cellulose→Glucose)", category: RecipeCategory::FoodBiological,
        inputs: &[(S::Cellulose, 0.9), (S::Water, 0.1)],
        outputs: &[(S::Glucose, 0.85)],
        byproducts: &[(S::Water, 0.15)],
        min_temp_c: 50, pressure_atm: 1.0, catalyst: None, duration_hours: 48.0, cross_recipe_group: None },
];
