#![allow(dead_code)]
use super::substance::Substance as S;
use super::types::*;

pub static ELECTROCHEMISTRY_RECIPES: &[Recipe] = &[
    // ===== BATTERIES =====
    Recipe {
        id: 950,
        name: "Lead-Acid Battery (Discharge)",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Lead, 0.5), (S::SulfuricAcid, 0.5)],
        outputs: &[(S::LeadAcidBattery, 1.0)],
        byproducts: &[(S::Water, 0.2)],
        min_temp_c: 20,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 4.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 951,
        name: "Li-ion Battery (Assembly)",
        category: RecipeCategory::Manufacturing,
        inputs: &[
            (S::Lithium, 0.1),
            (S::Cobalt, 0.2),
            (S::Carbon, 0.1),
            (S::Copper, 0.1),
        ],
        outputs: &[(S::LithiumIonBattery, 1.0)],
        byproducts: &[],
        min_temp_c: 20,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 8.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 952,
        name: "Zinc-Carbon Battery",
        category: RecipeCategory::Manufacturing,
        inputs: &[
            (S::Zinc, 0.3),
            (S::Manganese, 0.4),
            (S::Carbon, 0.1),
            (S::Salt, 0.2),
        ],
        outputs: &[(S::ZincCarbonBattery, 1.0)],
        byproducts: &[],
        min_temp_c: 20,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 2.0,
        cross_recipe_group: None,
    },
    // ===== ELECTROPLATING =====
    Recipe {
        id: 960,
        name: "Chrome Plating",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Chromium, 0.01), (S::SulfuricAcid, 0.1), (S::Water, 1.0)],
        outputs: &[(S::ChromePlating, 0.01)],
        byproducts: &[(S::HydrogenGas, 0.005)],
        min_temp_c: 50,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 2.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 961,
        name: "Gold Plating",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Gold, 0.005), (S::SodiumCyanide, 0.01), (S::Water, 1.0)],
        outputs: &[(S::GoldPlating, 0.005)],
        byproducts: &[],
        min_temp_c: 55,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 1.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 962,
        name: "Nickel Plating (Watts Bath)",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Nickel, 0.02), (S::SulfuricAcid, 0.05), (S::Water, 1.0)],
        outputs: &[(S::NickelPlating, 0.02)],
        byproducts: &[],
        min_temp_c: 55,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 3.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 963,
        name: "Zinc Galvanizing",
        category: RecipeCategory::Manufacturing,
        inputs: &[
            (S::Zinc, 0.03),
            (S::HydrochloricAcid, 0.05),
            (S::Water, 1.0),
        ],
        outputs: &[(S::ZincPlating, 0.03)],
        byproducts: &[],
        min_temp_c: 30,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 2.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 964,
        name: "Anodizing Aluminum",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Aluminum, 1.0), (S::SulfuricAcid, 0.3), (S::Water, 2.0)],
        outputs: &[(S::Alumina, 0.05)],
        byproducts: &[(S::HydrogenGas, 0.01)],
        min_temp_c: 20,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 1.0,
        cross_recipe_group: None,
    },
    // ===== NUCLEAR FISSION =====
    Recipe {
        id: 970,
        name: "U-235 Fission",
        category: RecipeCategory::PhaseChange,
        inputs: &[(S::Uranium, 0.001)],
        outputs: &[(S::Steam, 100.0)],
        byproducts: &[(S::Slag, 0.001)], // fission products
        min_temp_c: 300,
        pressure_atm: 150.0,
        catalyst: None,
        duration_hours: 8760.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 971,
        name: "Pu-239 Breeding (from U-238)",
        category: RecipeCategory::PhaseChange,
        inputs: &[(S::Uranium, 1.0)],
        outputs: &[(S::Plutonium, 0.6)],
        byproducts: &[],
        min_temp_c: 500,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 8760.0,
        cross_recipe_group: None,
    },
    // ===== NUCLEAR FUSION =====
    Recipe {
        id: 975,
        name: "D-T Fusion",
        category: RecipeCategory::PhaseChange,
        inputs: &[(S::HydrogenGas, 0.005)], // D+T
        outputs: &[(S::Steam, 500.0)],      // enormous energy
        byproducts: &[],
        min_temp_c: i32::MAX,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 0.001,
        cross_recipe_group: None,
    },
    Recipe {
        id: 976,
        name: "Stellar pp Chain (H → He)",
        category: RecipeCategory::PhaseChange,
        inputs: &[(S::HydrogenGas, 4.0)],
        outputs: &[(S::Steam, 1000.0)], // placeholder for He+energy
        byproducts: &[],
        min_temp_c: i32::MAX,
        pressure_atm: 1000000.0,
        catalyst: None,
        duration_hours: 8760000000.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 977,
        name: "Triple-Alpha (He → C)",
        category: RecipeCategory::PhaseChange,
        inputs: &[(S::Steam, 3.0)], // 3 He-4 placeholder
        outputs: &[(S::Carbon, 1.0)],
        byproducts: &[],
        min_temp_c: i32::MAX,
        pressure_atm: 100000.0,
        catalyst: None,
        duration_hours: 1000000.0,
        cross_recipe_group: None,
    },
    // ===== NUCLEOSYNTHESIS =====
    Recipe {
        id: 980,
        name: "Silicon Burning → Iron Peak",
        category: RecipeCategory::PhaseChange,
        inputs: &[(S::Silicon, 1.0)],
        outputs: &[(S::Iron, 1.0)],
        byproducts: &[],
        min_temp_c: i32::MAX,
        pressure_atm: 10000000.0,
        catalyst: None,
        duration_hours: 24.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 981,
        name: "r-Process (Neutron Star Merger → Gold)",
        category: RecipeCategory::PhaseChange,
        inputs: &[(S::Iron, 1.0)],
        outputs: &[(S::Gold, 0.001), (S::Platinum, 0.001), (S::Uranium, 0.0001)],
        byproducts: &[(S::Iron, 0.99)],
        min_temp_c: i32::MAX,
        pressure_atm: 100000.0,
        catalyst: None,
        duration_hours: 0.001,
        cross_recipe_group: None,
    },
    // ===== BATTERIES (continued) =====
    Recipe {
        id: 982,
        name: "NiMH Battery Assembly",
        category: RecipeCategory::Manufacturing,
        inputs: &[
            (S::Nickel, 0.4),
            (S::Magnesium, 0.3),
            (S::SodiumHydroxide, 0.3),
        ],
        outputs: &[(S::NiMHBattery, 1.0)],
        byproducts: &[],
        min_temp_c: 20,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 6.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 983,
        name: "Zinc-Air Battery",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Zinc, 0.6), (S::Oxygen, 0.4)],
        outputs: &[(S::ZincWhite, 1.0)],
        byproducts: &[],
        min_temp_c: 20,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 4.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 984,
        name: "Na-S Battery",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Sodium, 0.5), (S::Sulfur, 0.5)],
        outputs: &[(S::SodiumSulfurBattery, 1.0)],
        byproducts: &[],
        min_temp_c: 320,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 4.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 985,
        name: "Fe-Air Battery",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Iron, 0.7), (S::Oxygen, 0.3)],
        outputs: &[(S::IronAirBattery, 1.0)],
        byproducts: &[],
        min_temp_c: 20,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 6.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 986,
        name: "LFP Battery (LiFePO4)",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Lithium, 0.2), (S::Iron, 0.4), (S::Phosphorus, 0.4)],
        outputs: &[(S::LFPBattery, 1.0)],
        byproducts: &[],
        min_temp_c: 20,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 8.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 987,
        name: "Vanadium Flow Battery",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Vanadium, 0.5), (S::SulfuricAcid, 0.5)],
        outputs: &[(S::VanadiumFlowBattery, 1.0)],
        byproducts: &[],
        min_temp_c: 20,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 10.0,
        cross_recipe_group: None,
    },
    // ===== ELECTROPLATING (continued) =====
    Recipe {
        id: 988,
        name: "Silver Plating",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Silver, 0.01), (S::SodiumCyanide, 0.01), (S::Water, 1.0)],
        outputs: &[(S::SilverPlating, 0.01)],
        byproducts: &[],
        min_temp_c: 25,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 1.5,
        cross_recipe_group: None,
    },
    Recipe {
        id: 989,
        name: "Tin Plating",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Tin, 0.02), (S::SulfuricAcid, 0.05), (S::Water, 1.0)],
        outputs: &[(S::TinPlating, 0.02)],
        byproducts: &[],
        min_temp_c: 25,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 2.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 990,
        name: "Copper Plating",
        category: RecipeCategory::Manufacturing,
        inputs: &[(S::Copper, 0.02), (S::SulfuricAcid, 0.05), (S::Water, 1.0)],
        outputs: &[(S::CopperPlating, 0.02)],
        byproducts: &[],
        min_temp_c: 25,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 2.0,
        cross_recipe_group: None,
    },
    // ===== NUCLEAR DECAY =====
    Recipe {
        id: 991,
        name: "U-238 Decay Chain → Pb-206",
        category: RecipeCategory::PhaseChange,
        inputs: &[(S::Uranium, 1.0)],
        outputs: &[(S::Lead, 0.97)],
        byproducts: &[(S::Steam, 0.03)], // decay energy placeholder
        min_temp_c: i32::MAX,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 8760000000.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 992,
        name: "Th-232 Decay Chain → Pb-208",
        category: RecipeCategory::PhaseChange,
        inputs: &[(S::Thorium, 1.0)],
        outputs: &[(S::Lead, 0.97)],
        byproducts: &[(S::Steam, 0.03)],
        min_temp_c: i32::MAX,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 8760000000.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 993,
        name: "K-40 Decay → Ar-40 (Geochronology)",
        category: RecipeCategory::PhaseChange,
        inputs: &[(S::Potassium, 1.0)],
        outputs: &[(S::Argon, 0.99)],
        byproducts: &[],
        min_temp_c: i32::MAX,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 8760000000.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 994,
        name: "C-14 Decay → N-14 (Radiocarbon)",
        category: RecipeCategory::PhaseChange,
        inputs: &[(S::Carbon, 1.0)],
        outputs: &[(S::Nitrogen, 1.0)],
        byproducts: &[],
        min_temp_c: i32::MAX,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 50000.0,
        cross_recipe_group: None,
    },
    // ===== NUCLEAR PRODUCTION =====
    Recipe {
        id: 995,
        name: "Co-60 Production (Neutron Activation)",
        category: RecipeCategory::PhaseChange,
        inputs: &[(S::Cobalt, 1.0)],
        outputs: &[(S::Cobalt, 1.0)], // Co-60 placeholder
        byproducts: &[(S::Steam, 0.01)],
        min_temp_c: 300,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 8760.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 996,
        name: "Mo-99/Tc-99m Production (Fission)",
        category: RecipeCategory::PhaseChange,
        inputs: &[(S::Uranium, 1.0)],
        outputs: &[(S::Molybdenum, 0.03)],
        byproducts: &[(S::Slag, 0.97)], // fission products
        min_temp_c: 300,
        pressure_atm: 1.0,
        catalyst: None,
        duration_hours: 168.0,
        cross_recipe_group: None,
    },
    // ===== STELLAR NUCLEOSYNTHESIS (continued) =====
    Recipe {
        id: 997,
        name: "Carbon Burning (C+C → Na+He)",
        category: RecipeCategory::PhaseChange,
        inputs: &[(S::Carbon, 2.0)],
        outputs: &[(S::Sodium, 1.0)],
        byproducts: &[(S::Steam, 0.5)], // He energy placeholder
        min_temp_c: i32::MAX,
        pressure_atm: 1000000.0,
        catalyst: None,
        duration_hours: 1000.0,
        cross_recipe_group: None,
    },
    Recipe {
        id: 998,
        name: "Oxygen Burning (O+O → Si)",
        category: RecipeCategory::PhaseChange,
        inputs: &[(S::Oxygen, 2.0)],
        outputs: &[(S::Silicon, 1.0)],
        byproducts: &[(S::Steam, 0.5)],
        min_temp_c: i32::MAX,
        pressure_atm: 10000000.0,
        catalyst: None,
        duration_hours: 0.5,
        cross_recipe_group: None,
    },
    Recipe {
        id: 999,
        name: "s-Process Slow Neutron Capture (Fe → Pb)",
        category: RecipeCategory::PhaseChange,
        inputs: &[(S::Iron, 1.0)],
        outputs: &[(S::Lead, 0.5)],
        byproducts: &[(S::Iron, 0.5)],
        min_temp_c: i32::MAX,
        pressure_atm: 100000.0,
        catalyst: None,
        duration_hours: 876000000.0,
        cross_recipe_group: None,
    },
];
