#![allow(dead_code)]
use super::types::*;
use super::substance::Substance as S;

pub static NATURAL_RECIPES: &[Recipe] = &[
    // ===== WEATHERING =====
    Recipe { id: 1000, name: "Feldspar Weathering → Kaolinite", category: RecipeCategory::PhaseChange,
        inputs: &[(S::FeldsparOre, 1.0), (S::Water, 0.5), (S::CarbonDioxide, 0.1)],
        outputs: &[(S::Clay, 0.6)], byproducts: &[(S::Sand, 0.3)],
        min_temp_c: 15, pressure_atm: 1.0, catalyst: None, duration_hours: 87600000.0, cross_recipe_group: None },
    Recipe { id: 1001, name: "Olivine Weathering (CO2 Capture)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Sand, 1.0), (S::CarbonDioxide, 0.5), (S::Water, 0.5)], // olivine as Sand placeholder
        outputs: &[(S::Magnesium, 0.3)], byproducts: &[(S::Sand, 0.5)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 87600000.0, cross_recipe_group: None },
    Recipe { id: 1002, name: "Calcite Dissolution (Cave Formation)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Limestone, 1.0), (S::CarbonDioxide, 0.1), (S::Water, 1.0)],
        outputs: &[(S::CalciumChloride, 0.8)], byproducts: &[(S::Water, 0.5)],
        min_temp_c: 10, pressure_atm: 1.0, catalyst: None, duration_hours: 876000.0, cross_recipe_group: None },
    Recipe { id: 1003, name: "Pyrite Oxidation (Acid Mine Drainage)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::PyriteOre, 1.0), (S::Oxygen, 0.5), (S::Water, 0.5)],
        outputs: &[(S::IronHydroxide, 0.5), (S::SulfuricAcid, 0.4)], byproducts: &[],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 8760.0, cross_recipe_group: None },

    // ===== METAMORPHIC =====
    Recipe { id: 1010, name: "Limestone → Marble", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Limestone, 1.0)], outputs: &[(S::Marble, 1.0)], byproducts: &[],
        min_temp_c: 400, pressure_atm: 2000.0, catalyst: None, duration_hours: 87600000.0, cross_recipe_group: None },
    Recipe { id: 1011, name: "Shale → Slate", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Clay, 1.0)], outputs: &[(S::Slate, 1.0)], byproducts: &[(S::Water, 0.05)],
        min_temp_c: 250, pressure_atm: 1500.0, catalyst: None, duration_hours: 87600000.0, cross_recipe_group: None },
    Recipe { id: 1012, name: "Sandstone → Quartzite", category: RecipeCategory::PhaseChange,
        inputs: &[(S::SilicaSand, 1.0)], outputs: &[(S::Quartzite, 1.0)], byproducts: &[],
        min_temp_c: 400, pressure_atm: 3000.0, catalyst: None, duration_hours: 87600000.0, cross_recipe_group: None },
    Recipe { id: 1013, name: "Serpentinization (Olivine + Water)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Sand, 1.0), (S::Water, 0.5)], // olivine placeholder
        outputs: &[(S::SerpentineMinite, 0.8), (S::HydrogenGas, 0.02)],
        byproducts: &[(S::Magnetite, 0.1)],
        min_temp_c: 300, pressure_atm: 500.0, catalyst: None, duration_hours: 876000.0, cross_recipe_group: None },

    // ===== HYDROTHERMAL =====
    Recipe { id: 1020, name: "Black Smoker Pyrite", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Iron, 0.5), (S::Sulfur, 0.5), (S::Water, 5.0)],
        outputs: &[(S::PyriteOre, 1.0)], byproducts: &[],
        min_temp_c: 350, pressure_atm: 300.0, catalyst: None, duration_hours: 8760.0, cross_recipe_group: None },
    Recipe { id: 1021, name: "Hydrothermal Gold Deposition", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Water, 1000.0), (S::Sulfur, 0.01)],
        outputs: &[(S::Gold, 0.001)], byproducts: &[(S::SilicaSand, 0.5)],
        min_temp_c: 300, pressure_atm: 200.0, catalyst: None, duration_hours: 876000.0, cross_recipe_group: None },
    Recipe { id: 1022, name: "Silica Sinter (Hot Spring)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Water, 100.0), (S::SilicaSand, 0.4)], // dissolved silica
        outputs: &[(S::SilicaSand, 1.0)], byproducts: &[(S::Water, 99.0)],
        min_temp_c: 90, pressure_atm: 1.0, catalyst: None, duration_hours: 87600.0, cross_recipe_group: None },

    // ===== DIAGENESIS =====
    Recipe { id: 1025, name: "Kerogen → Crude Oil (Catagenesis)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Cellulose, 10.0)], // kerogen placeholder
        outputs: &[(S::CrudeOil, 1.0)], byproducts: &[(S::NaturalGas, 0.3), (S::Carbon, 0.5)],
        min_temp_c: 100, pressure_atm: 500.0, catalyst: None, duration_hours: 876000000.0, cross_recipe_group: None },

    // ===== ATMOSPHERIC =====
    Recipe { id: 1030, name: "Ozone Formation (UV)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Oxygen, 1.0)], outputs: &[(S::Ozone, 0.67)], byproducts: &[],
        min_temp_c: -60, pressure_atm: 0.001, catalyst: None, duration_hours: 0.001, cross_recipe_group: None },
    Recipe { id: 1031, name: "Acid Rain (SO2 → H2SO4)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::SulfurDioxide, 0.6), (S::Water, 0.3), (S::Oxygen, 0.1)],
        outputs: &[(S::SulfuricAcid, 1.0)], byproducts: &[],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 168.0, cross_recipe_group: None },
    Recipe { id: 1032, name: "Ocean CO2 Dissolution", category: RecipeCategory::PhaseChange,
        inputs: &[(S::CarbonDioxide, 0.1), (S::Water, 10.0)],
        outputs: &[(S::Water, 10.0)], byproducts: &[], // acidified water
        min_temp_c: 10, pressure_atm: 1.0, catalyst: None, duration_hours: 8760.0, cross_recipe_group: None },

    // ===== BIOCHEMISTRY =====
    Recipe { id: 1040, name: "Oxygenic Photosynthesis", category: RecipeCategory::FoodBiological,
        inputs: &[(S::CarbonDioxide, 0.44), (S::Water, 0.36)],
        outputs: &[(S::Glucose, 0.48), (S::Oxygen, 0.32)], byproducts: &[],
        min_temp_c: 25, pressure_atm: 1.0, catalyst: None, duration_hours: 12.0, cross_recipe_group: None },
    Recipe { id: 1041, name: "Aerobic Respiration", category: RecipeCategory::FoodBiological,
        inputs: &[(S::Glucose, 0.48), (S::Oxygen, 0.32)],
        outputs: &[(S::CarbonDioxide, 0.44), (S::Water, 0.36)], byproducts: &[],
        min_temp_c: 37, pressure_atm: 1.0, catalyst: None, duration_hours: 0.01, cross_recipe_group: None },
    Recipe { id: 1042, name: "Lactic Acid Fermentation", category: RecipeCategory::FoodBiological,
        inputs: &[(S::Glucose, 1.0)], outputs: &[(S::LacticAcid, 1.0)], byproducts: &[],
        min_temp_c: 37, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: None },
    Recipe { id: 1043, name: "Nitrogen Fixation (Biological)", category: RecipeCategory::FoodBiological,
        inputs: &[(S::Nitrogen, 0.82), (S::HydrogenGas, 0.18)],
        outputs: &[(S::Ammonium, 1.0)], byproducts: &[],
        min_temp_c: 25, pressure_atm: 1.0, catalyst: None, duration_hours: 720.0, cross_recipe_group: None },
    Recipe { id: 1044, name: "Methanogenesis (CO2 Reduction)", category: RecipeCategory::FoodBiological,
        inputs: &[(S::CarbonDioxide, 0.6), (S::HydrogenGas, 0.4)],
        outputs: &[(S::Methane, 0.6)], byproducts: &[(S::Water, 0.4)],
        min_temp_c: 35, pressure_atm: 1.0, catalyst: None, duration_hours: 720.0, cross_recipe_group: None },

    // ===== PIGMENTS =====
    Recipe { id: 1050, name: "Yellow Ochre → Red Ochre (Calcination)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::YellowOchre, 1.0)], outputs: &[(S::RedOchre, 0.9)], byproducts: &[(S::Water, 0.1)],
        min_temp_c: 300, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: None },
    Recipe { id: 1051, name: "Raw Umber → Burnt Umber", category: RecipeCategory::PhaseChange,
        inputs: &[(S::RawUmber, 1.0)], outputs: &[(S::BurntUmber, 0.95)], byproducts: &[(S::Water, 0.05)],
        min_temp_c: 400, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: None },
    Recipe { id: 1052, name: "Raw Sienna → Burnt Sienna", category: RecipeCategory::PhaseChange,
        inputs: &[(S::RawSienna, 1.0)], outputs: &[(S::BurntSienna, 0.95)], byproducts: &[(S::Water, 0.05)],
        min_temp_c: 400, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: None },
    Recipe { id: 1053, name: "Carbon Black (Lamp Soot)", category: RecipeCategory::FuelProcessing,
        inputs: &[(S::CrudeOil, 1.5)], outputs: &[(S::CarbonBlack, 1.0)], byproducts: &[(S::CarbonDioxide, 0.3)],
        min_temp_c: 300, pressure_atm: 1.0, catalyst: None, duration_hours: 2.0, cross_recipe_group: None },
    Recipe { id: 1054, name: "Bone Black (Calcined Bones)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Calcium, 1.0)], // bones placeholder
        outputs: &[(S::BoneBlack, 0.8)], byproducts: &[(S::CarbonDioxide, 0.2)],
        min_temp_c: 450, pressure_atm: 1.0, catalyst: None, duration_hours: 6.0, cross_recipe_group: None },
    Recipe { id: 1055, name: "Chrome Yellow (PbCrO4)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Lead, 0.6), (S::Chromium, 0.2), (S::NitricAcid, 0.2)],
        outputs: &[(S::ChromeYellow, 1.0)], byproducts: &[(S::PotassiumNitrate, 0.1)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.5, cross_recipe_group: None },
    Recipe { id: 1056, name: "Chrome Green (Cr2O3)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Chromium, 0.5), (S::Sulfur, 0.3), (S::SodiumHydroxide, 0.2)],
        outputs: &[(S::ChromeGreen, 1.0)], byproducts: &[(S::SodiumSulfate, 0.2)],
        min_temp_c: 500, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: None },
    Recipe { id: 1057, name: "Cadmium Yellow (CdS)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Zinc, 0.5), (S::Sulfur, 0.5)], // Cd placeholder as Zinc
        outputs: &[(S::CadmiumYellow, 1.0)], byproducts: &[],
        min_temp_c: 300, pressure_atm: 1.0, catalyst: None, duration_hours: 2.0, cross_recipe_group: None },
    Recipe { id: 1058, name: "Cobalt Blue (CoAl2O4)", category: RecipeCategory::Construction,
        inputs: &[(S::Cobalt, 0.3), (S::Alumina, 0.7)],
        outputs: &[(S::CobaltBluePigment, 1.0)], byproducts: &[],
        min_temp_c: 1200, pressure_atm: 1.0, catalyst: None, duration_hours: 8.0, cross_recipe_group: None },
    Recipe { id: 1059, name: "Synthetic Ultramarine", category: RecipeCategory::Construction,
        inputs: &[(S::Clay, 0.4), (S::SodaAsh, 0.2), (S::Sulfur, 0.2), (S::Charcoal, 0.1)],
        outputs: &[(S::SyntheticUltramarine, 1.0)], byproducts: &[],
        min_temp_c: 780, pressure_atm: 1.0, catalyst: None, duration_hours: 48.0, cross_recipe_group: None },
    Recipe { id: 1060, name: "Titanium White (Chloride Process)", category: RecipeCategory::Extraction,
        inputs: &[(S::Ilmenite, 1.5), (S::ChlorineGas, 1.0), (S::Carbon, 0.3)],
        outputs: &[(S::TitaniumWhite, 1.0)], byproducts: &[(S::Iron, 0.3), (S::ChlorineGas, 0.8)],
        min_temp_c: 1500, pressure_atm: 1.0, catalyst: None, duration_hours: 2.0, cross_recipe_group: None },
    Recipe { id: 1061, name: "Egyptian Blue (CaCuSi2O6)", category: RecipeCategory::Construction,
        inputs: &[(S::SilicaSand, 0.4), (S::Limestone, 0.2), (S::Copper, 0.2), (S::SodaAsh, 0.1)],
        outputs: &[(S::EgyptianBlue, 1.0)], byproducts: &[(S::CarbonDioxide, 0.1)],
        min_temp_c: 950, pressure_atm: 1.0, catalyst: None, duration_hours: 24.0, cross_recipe_group: None },
    Recipe { id: 1062, name: "Vermilion (HgS Sublimation)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Mercury, 0.85), (S::Sulfur, 0.15)],
        outputs: &[(S::Vermilion, 1.0)], byproducts: &[],
        min_temp_c: 580, pressure_atm: 1.0, catalyst: None, duration_hours: 8.0, cross_recipe_group: None },
    Recipe { id: 1063, name: "Lead White (Dutch Process)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Lead, 0.8), (S::AceticAcid, 0.1), (S::CarbonDioxide, 0.1)],
        outputs: &[(S::LeadWhite, 1.0)], byproducts: &[],
        min_temp_c: 25, pressure_atm: 1.0, catalyst: None, duration_hours: 1440.0, cross_recipe_group: None },
    Recipe { id: 1064, name: "Verdigris (Cu + Acetic Acid)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Copper, 0.7), (S::AceticAcid, 0.3)],
        outputs: &[(S::Verdigris, 1.0)], byproducts: &[],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 720.0, cross_recipe_group: None },
    Recipe { id: 1065, name: "Zinc White (ZnO)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Zinc, 0.8), (S::Oxygen, 0.2)],
        outputs: &[(S::ZincWhite, 1.0)], byproducts: &[],
        min_temp_c: 907, pressure_atm: 1.0, catalyst: None, duration_hours: 0.5, cross_recipe_group: None },

    // ===== WATER TREATMENT =====
    Recipe { id: 1070, name: "Lime Softening", category: RecipeCategory::Refining,
        inputs: &[(S::Water, 100.0), (S::SlakedLite, 0.5)],
        outputs: &[(S::Water, 99.0)], byproducts: &[(S::Limestone, 0.5)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: None },
    Recipe { id: 1071, name: "Reverse Osmosis Desalination", category: RecipeCategory::Refining,
        inputs: &[(S::Water, 3.0)], // seawater
        outputs: &[(S::Water, 1.0)], byproducts: &[(S::Salt, 0.07)],
        min_temp_c: 25, pressure_atm: 70.0, catalyst: None, duration_hours: 0.1, cross_recipe_group: None },
    Recipe { id: 1072, name: "Water Chlorination", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Water, 1000.0), (S::ChlorineGas, 0.002)],
        outputs: &[(S::Water, 1000.0)], byproducts: &[],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.5, cross_recipe_group: None },
    Recipe { id: 1073, name: "Alum Flocculation", category: RecipeCategory::Refining,
        inputs: &[(S::Water, 100.0), (S::AlumCompound, 0.05)],
        outputs: &[(S::Water, 99.0)], byproducts: &[(S::IronHydroxide, 0.5)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: None },

    // ===== ATMOSPHERIC (continued) =====
    Recipe { id: 1074, name: "Ground-Level Ozone (NO2 + UV Smog)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::NitrogenDioxide, 0.5), (S::Oxygen, 0.5)],
        outputs: &[(S::Ozone, 0.67)], byproducts: &[(S::Nitrogen, 0.1)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 6.0, cross_recipe_group: None },
    Recipe { id: 1075, name: "NO + O3 → NO2 (Tropospheric)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Nitrogen, 0.3), (S::Ozone, 0.7)],
        outputs: &[(S::NitrogenDioxide, 0.8)], byproducts: &[(S::Oxygen, 0.2)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.01, cross_recipe_group: None },
    Recipe { id: 1076, name: "Methane Atmospheric Oxidation (CH4 → CO2)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Methane, 0.6), (S::Oxygen, 0.4)],
        outputs: &[(S::CarbonDioxide, 0.7)], byproducts: &[(S::Water, 0.3)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 87600.0, cross_recipe_group: None },
    Recipe { id: 1077, name: "Silicate Weathering (Geological Thermostat)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::SilicaSand, 1.0), (S::CarbonDioxide, 0.3), (S::Water, 0.5)],
        outputs: &[(S::Limestone, 0.6)], byproducts: &[(S::SilicaSand, 0.4)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 87600000.0, cross_recipe_group: None },
    Recipe { id: 1078, name: "Volcanic CO2 Outgassing", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Limestone, 1.0)], outputs: &[(S::CarbonDioxide, 0.5)],
        byproducts: &[(S::SulfurDioxide, 0.1), (S::Steam, 0.3)],
        min_temp_c: 600, pressure_atm: 100.0, catalyst: None, duration_hours: 1.0, cross_recipe_group: None },

    // ===== BIOCHEMISTRY (continued) =====
    Recipe { id: 1079, name: "Anoxygenic Photosynthesis (CO2 + H2S)", category: RecipeCategory::FoodBiological,
        inputs: &[(S::CarbonDioxide, 0.4), (S::Sulfur, 0.3), (S::Water, 0.3)], // H2S as Sulfur placeholder
        outputs: &[(S::Cellulose, 0.4)], byproducts: &[(S::Sulfur, 0.3)],
        min_temp_c: 25, pressure_atm: 1.0, catalyst: None, duration_hours: 12.0, cross_recipe_group: None },
    Recipe { id: 1080, name: "Sulfate Reduction (SO4 → H2S)", category: RecipeCategory::FoodBiological,
        inputs: &[(S::SulfuricAcid, 0.6), (S::Cellulose, 0.4)], // organic electron donor
        outputs: &[(S::Sulfur, 0.5)], byproducts: &[(S::Water, 0.3), (S::CarbonDioxide, 0.2)],
        min_temp_c: 35, pressure_atm: 1.0, catalyst: None, duration_hours: 720.0, cross_recipe_group: None },
    Recipe { id: 1081, name: "Sulfur Oxidation (H2S → H2SO4, Bioleaching)", category: RecipeCategory::FoodBiological,
        inputs: &[(S::Sulfur, 0.4), (S::Oxygen, 0.4), (S::Water, 0.2)],
        outputs: &[(S::SulfuricAcid, 0.8)], byproducts: &[],
        min_temp_c: 30, pressure_atm: 1.0, catalyst: None, duration_hours: 168.0, cross_recipe_group: None },
    Recipe { id: 1082, name: "Acetoclastic Methanogenesis (Acetate → CH4)", category: RecipeCategory::FoodBiological,
        inputs: &[(S::AceticAcid, 1.0)],
        outputs: &[(S::Methane, 0.5), (S::CarbonDioxide, 0.5)], byproducts: &[],
        min_temp_c: 35, pressure_atm: 1.0, catalyst: None, duration_hours: 720.0, cross_recipe_group: None },
    Recipe { id: 1083, name: "Methanotrophy (CH4 + O2 → CO2)", category: RecipeCategory::FoodBiological,
        inputs: &[(S::Methane, 0.5), (S::Oxygen, 0.5)],
        outputs: &[(S::CarbonDioxide, 0.6)], byproducts: &[(S::Water, 0.4)],
        min_temp_c: 25, pressure_atm: 1.0, catalyst: None, duration_hours: 24.0, cross_recipe_group: None },
    Recipe { id: 1084, name: "Aerobic Decomposition (Composting)", category: RecipeCategory::FoodBiological,
        inputs: &[(S::Cellulose, 1.0), (S::Oxygen, 0.5)],
        outputs: &[(S::CarbonDioxide, 0.6)], byproducts: &[(S::Ammonium, 0.1), (S::Water, 0.3)],
        min_temp_c: 55, pressure_atm: 1.0, catalyst: None, duration_hours: 720.0, cross_recipe_group: None },
    Recipe { id: 1085, name: "Anaerobic Decomposition (Organic → CH4)", category: RecipeCategory::FoodBiological,
        inputs: &[(S::Cellulose, 1.0)],
        outputs: &[(S::Methane, 0.4), (S::CarbonDioxide, 0.3)],
        byproducts: &[(S::Sulfur, 0.05), (S::Water, 0.2)], // H2S as Sulfur placeholder
        min_temp_c: 25, pressure_atm: 1.0, catalyst: None, duration_hours: 1440.0, cross_recipe_group: None },
    Recipe { id: 1086, name: "Ammonification (Organic N → NH4)", category: RecipeCategory::FoodBiological,
        inputs: &[(S::Cellulose, 0.8), (S::Water, 0.2)], // organic N placeholder
        outputs: &[(S::Ammonium, 0.6)], byproducts: &[(S::CarbonDioxide, 0.2)],
        min_temp_c: 25, pressure_atm: 1.0, catalyst: None, duration_hours: 168.0, cross_recipe_group: None },

    // ===== PIGMENTS (continued) =====
    Recipe { id: 1087, name: "Naples Yellow (Pb2Sb2O7)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Lead, 0.6), (S::Tin, 0.3), (S::Oxygen, 0.1)], // Tin as Sb placeholder
        outputs: &[(S::NaplesYellow, 1.0)], byproducts: &[],
        min_temp_c: 950, pressure_atm: 1.0, catalyst: None, duration_hours: 8.0, cross_recipe_group: None },
    Recipe { id: 1088, name: "Mars Yellow (Synthetic FeOOH)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Iron, 0.5), (S::SodiumHydroxide, 0.3), (S::Oxygen, 0.2)],
        outputs: &[(S::MarsYellow, 1.0)], byproducts: &[(S::Water, 0.1)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: None },
    Recipe { id: 1089, name: "Mars Red (Synthetic Fe2O3, from Mars Yellow)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::MarsYellow, 1.0)], outputs: &[(S::MarsRed, 0.9)],
        byproducts: &[(S::Water, 0.1)],
        min_temp_c: 500, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: None },
    Recipe { id: 1090, name: "Mars Black (Fe3O4 Magnetite, Reduction)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::MarsRed, 1.0)], outputs: &[(S::MarsBlack, 0.95)],
        byproducts: &[(S::Oxygen, 0.05)],
        min_temp_c: 400, pressure_atm: 1.0, catalyst: None, duration_hours: 6.0, cross_recipe_group: None },

    // ===== WATER TREATMENT (continued) =====
    Recipe { id: 1091, name: "Ozonation (Water Treatment)", category: RecipeCategory::Refining,
        inputs: &[(S::Ozone, 0.01), (S::Water, 100.0)],
        outputs: &[(S::Water, 100.0)], byproducts: &[(S::Oxygen, 0.01)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.5, cross_recipe_group: None },
    Recipe { id: 1092, name: "UV Disinfection", category: RecipeCategory::Refining,
        inputs: &[(S::Water, 100.0)],
        outputs: &[(S::Water, 100.0)], byproducts: &[],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.01, cross_recipe_group: None },
    Recipe { id: 1093, name: "Multi-Stage Flash Desalination", category: RecipeCategory::Refining,
        inputs: &[(S::Water, 10.0)], // seawater
        outputs: &[(S::Water, 3.0)], byproducts: &[(S::Salt, 0.3), (S::Steam, 1.0)],
        min_temp_c: 120, pressure_atm: 2.0, catalyst: None, duration_hours: 1.0, cross_recipe_group: None },
    Recipe { id: 1094, name: "Ion Exchange Softening", category: RecipeCategory::Refining,
        inputs: &[(S::Water, 100.0), (S::Salt, 0.5)], // salt regeneration
        outputs: &[(S::Water, 99.0)], byproducts: &[(S::CalciumChloride, 0.5)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 2.0, cross_recipe_group: None },

    // ===== GEOCHEMISTRY / MATERIALS CYCLING =====
    Recipe { id: 2600, name: "CaCO3 Precipitation (Ocean)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Calcium, 0.4), (S::CarbonDioxide, 0.3), (S::Water, 0.3)],
        outputs: &[(S::Limestone, 0.8)],
        byproducts: &[(S::Water, 0.2)],
        min_temp_c: 15, pressure_atm: 1.0, catalyst: None, duration_hours: 876000.0, cross_recipe_group: None },
    Recipe { id: 2601, name: "Dolomitization (CaCO3→CaMg(CO3)2)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Limestone, 0.7), (S::Magnesium, 0.2), (S::Water, 0.1)],
        outputs: &[(S::Dolomite, 1.0)],
        byproducts: &[],
        min_temp_c: 50, pressure_atm: 100.0, catalyst: None, duration_hours: 87600000.0, cross_recipe_group: None },
    Recipe { id: 2602, name: "Phosphorite Formation (Marine)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::PhosphateRock, 0.3), (S::Calcium, 0.3), (S::Water, 0.4)],
        outputs: &[(S::Phosphorite, 1.0)],
        byproducts: &[],
        min_temp_c: 10, pressure_atm: 50.0, catalyst: None, duration_hours: 87600000.0, cross_recipe_group: None },
    Recipe { id: 2603, name: "Chert/Flint Formation (Biogenic SiO2)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::SilicaSand, 0.8), (S::Water, 0.2)],
        outputs: &[(S::Chert, 1.0)],
        byproducts: &[],
        min_temp_c: 10, pressure_atm: 200.0, catalyst: None, duration_hours: 87600000.0, cross_recipe_group: None },
    Recipe { id: 2604, name: "Coal: Peat→Lignite", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Peat, 1.0)],
        outputs: &[(S::Lignite, 0.7)],
        byproducts: &[(S::Water, 0.2), (S::Methane, 0.1)],
        min_temp_c: 50, pressure_atm: 50.0, catalyst: None, duration_hours: 876000000.0, cross_recipe_group: None },
    Recipe { id: 2605, name: "Coal: Lignite→Bituminous", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Lignite, 1.0)],
        outputs: &[(S::Bituminite, 0.8)],
        byproducts: &[(S::Water, 0.1), (S::Methane, 0.1)],
        min_temp_c: 100, pressure_atm: 300.0, catalyst: None, duration_hours: 876000000.0, cross_recipe_group: None },
    Recipe { id: 2606, name: "Coal: Bituminous→Anthracite", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Bituminite, 1.0)],
        outputs: &[(S::Anthracite, 0.9)],
        byproducts: &[(S::Methane, 0.05), (S::Water, 0.05)],
        min_temp_c: 200, pressure_atm: 1000.0, catalyst: None, duration_hours: 876000000.0, cross_recipe_group: None },
    Recipe { id: 2607, name: "Natural Gas Formation (Deep Catagenesis)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Cellulose, 5.0)], // kerogen placeholder
        outputs: &[(S::NaturalGas, 1.0)],
        byproducts: &[(S::Carbon, 1.0)],
        min_temp_c: 150, pressure_atm: 800.0, catalyst: None, duration_hours: 876000000.0, cross_recipe_group: None },
    Recipe { id: 2608, name: "Petroleum Migration and Trapping", category: RecipeCategory::PhaseChange,
        inputs: &[(S::CrudeOil, 1.0), (S::SilicaSand, 5.0)],
        outputs: &[(S::CrudeOil, 0.9)], // trapped oil
        byproducts: &[(S::NaturalGas, 0.1)],
        min_temp_c: 80, pressure_atm: 200.0, catalyst: None, duration_hours: 87600000.0, cross_recipe_group: None },
    Recipe { id: 2609, name: "Salt Dome Diapirism (Halite Flow)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Salt, 10.0)],
        outputs: &[(S::Salt, 10.0)], // salt dome
        byproducts: &[],
        min_temp_c: 100, pressure_atm: 500.0, catalyst: None, duration_hours: 876000000.0, cross_recipe_group: None },
    Recipe { id: 2610, name: "Evaporite Sequence (Gypsum→Halite→Sylvite)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Water, 100.0), (S::Salt, 3.0), (S::Calcium, 0.5)],
        outputs: &[(S::Gypsum, 0.5), (S::Salt, 2.8), (S::Potassium, 0.2)],
        byproducts: &[],
        min_temp_c: 30, pressure_atm: 1.0, catalyst: None, duration_hours: 87600.0, cross_recipe_group: None },
    Recipe { id: 2611, name: "Laterite Formation (Tropical Weathering)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::FeldsparOre, 1.0), (S::Water, 2.0)],
        outputs: &[(S::Laterite, 0.6)],
        byproducts: &[(S::SilicaSand, 0.3), (S::Water, 1.5)],
        min_temp_c: 25, pressure_atm: 1.0, catalyst: None, duration_hours: 87600000.0, cross_recipe_group: None },
    Recipe { id: 2612, name: "Bauxite Formation (Al-Enriched Laterite)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Laterite, 1.0), (S::Water, 1.0)],
        outputs: &[(S::Bauxite, 0.6)],
        byproducts: &[(S::Hematite, 0.2), (S::Water, 0.8)],
        min_temp_c: 25, pressure_atm: 1.0, catalyst: None, duration_hours: 87600000.0, cross_recipe_group: None },
    Recipe { id: 2613, name: "Saprolite Formation (In-Situ Rock Decay)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::FeldsparOre, 1.0), (S::Water, 1.0), (S::CarbonDioxide, 0.1)],
        outputs: &[(S::Saprolite, 0.8)],
        byproducts: &[(S::Clay, 0.2), (S::Water, 0.5)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 87600000.0, cross_recipe_group: None },
    Recipe { id: 2614, name: "Manganese Nodule Growth (Deep Sea)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Manganese, 0.3), (S::Iron, 0.2), (S::Water, 0.5)],
        outputs: &[(S::ManganeseNodule, 1.0)],
        byproducts: &[],
        min_temp_c: 2, pressure_atm: 400.0, catalyst: None, duration_hours: 876000000.0, cross_recipe_group: None },
    Recipe { id: 2615, name: "Banded Iron Formation (Archean)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Iron, 0.5), (S::Oxygen, 0.3), (S::SilicaSand, 0.2)],
        outputs: &[(S::BandedIronFormation, 1.0)],
        byproducts: &[],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 876000000.0, cross_recipe_group: None },
    Recipe { id: 2616, name: "Phosphogenesis (Upwelling Zones)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::PhosphateRock, 0.3), (S::Water, 0.7)],
        outputs: &[(S::Phosphorite, 0.5)],
        byproducts: &[(S::Water, 0.5)],
        min_temp_c: 5, pressure_atm: 50.0, catalyst: None, duration_hours: 876000.0, cross_recipe_group: None },
    Recipe { id: 2617, name: "Guano→Phosphate Rock", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Guano, 1.0), (S::Water, 0.5)],
        outputs: &[(S::PhosphateRock, 0.6)],
        byproducts: &[(S::Ammonium, 0.2), (S::Water, 0.3)],
        min_temp_c: 25, pressure_atm: 1.0, catalyst: None, duration_hours: 876000.0, cross_recipe_group: None },
    Recipe { id: 2618, name: "Amber Formation (Resin→Copal→Amber)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::NaturalRubber, 1.0)], // tree resin placeholder
        outputs: &[(S::Amber, 0.8)],
        byproducts: &[(S::Methane, 0.1)],
        min_temp_c: 30, pressure_atm: 50.0, catalyst: None, duration_hours: 876000000.0, cross_recipe_group: None },
    Recipe { id: 2619, name: "Petrified Wood (SiO2 Replacement)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::WoodLogs, 1.0), (S::SilicaSand, 0.5), (S::Water, 2.0)],
        outputs: &[(S::PetrifiedWood, 1.0)],
        byproducts: &[(S::Water, 1.5)],
        min_temp_c: 50, pressure_atm: 10.0, catalyst: None, duration_hours: 876000000.0, cross_recipe_group: None },
    Recipe { id: 2620, name: "Fossil Formation (Permineralization)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Calcium, 0.5), (S::SilicaSand, 0.3), (S::Water, 0.2)],
        outputs: &[(S::Fossil, 1.0)],
        byproducts: &[],
        min_temp_c: 20, pressure_atm: 100.0, catalyst: None, duration_hours: 876000000.0, cross_recipe_group: None },
    Recipe { id: 2621, name: "Coral Reef CaCO3 Deposition", category: RecipeCategory::FoodBiological,
        inputs: &[(S::Calcium, 0.4), (S::CarbonDioxide, 0.3), (S::Water, 0.3)],
        outputs: &[(S::CoralReef, 1.0)],
        byproducts: &[],
        min_temp_c: 23, pressure_atm: 1.0, catalyst: None, duration_hours: 87600.0, cross_recipe_group: None },
    Recipe { id: 2622, name: "Pearl Formation (Nacre Deposition)", category: RecipeCategory::FoodBiological,
        inputs: &[(S::Calcium, 0.5), (S::CarbonDioxide, 0.2), (S::Water, 0.3)],
        outputs: &[(S::Pearl, 0.9)],
        byproducts: &[(S::Water, 0.1)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 17520.0, cross_recipe_group: None },
    Recipe { id: 2623, name: "Stromatolite Formation (Cyanobacteria+CaCO3)", category: RecipeCategory::FoodBiological,
        inputs: &[(S::CarbonDioxide, 0.3), (S::Calcium, 0.3), (S::Water, 0.4)],
        outputs: &[(S::Stromatolite, 1.0)],
        byproducts: &[(S::Oxygen, 0.2)],
        min_temp_c: 25, pressure_atm: 1.0, catalyst: None, duration_hours: 876000.0, cross_recipe_group: None },
    Recipe { id: 2624, name: "Biofilm Formation (General)", category: RecipeCategory::FoodBiological,
        inputs: &[(S::Glucose, 0.5), (S::Water, 0.5)],
        outputs: &[(S::Biofilm, 1.0)],
        byproducts: &[],
        min_temp_c: 25, pressure_atm: 1.0, catalyst: None, duration_hours: 48.0, cross_recipe_group: None },
    Recipe { id: 2625, name: "Humus Formation (Organic Decay→Soil)", category: RecipeCategory::FoodBiological,
        inputs: &[(S::Cellulose, 1.0), (S::Water, 0.5)],
        outputs: &[(S::Humus, 0.6)],
        byproducts: &[(S::CarbonDioxide, 0.2), (S::Water, 0.3)],
        min_temp_c: 15, pressure_atm: 1.0, catalyst: None, duration_hours: 8760.0, cross_recipe_group: None },
    Recipe { id: 2626, name: "Peat Accumulation (Waterlogged Plant Matter)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Cellulose, 1.0), (S::Water, 2.0)],
        outputs: &[(S::Peat, 0.5)],
        byproducts: &[(S::Water, 1.5), (S::Methane, 0.1)],
        min_temp_c: 10, pressure_atm: 1.0, catalyst: None, duration_hours: 87600.0, cross_recipe_group: None },
    Recipe { id: 2627, name: "Calcium Oxalate (Kidney Stone Formation)", category: RecipeCategory::FoodBiological,
        inputs: &[(S::Calcium, 0.4), (S::OxalicAcid, 0.4), (S::Water, 0.2)],
        outputs: &[(S::CalciumOxalite, 1.0)],
        byproducts: &[(S::Water, 0.1)],
        min_temp_c: 37, pressure_atm: 1.0, catalyst: None, duration_hours: 8760.0, cross_recipe_group: None },
    Recipe { id: 2628, name: "CaCO3 Scaling (Pipe Deposits)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Calcium, 0.4), (S::CarbonDioxide, 0.3), (S::Water, 0.3)],
        outputs: &[(S::Limestone, 0.8)], // scale
        byproducts: &[(S::Water, 0.2)],
        min_temp_c: 50, pressure_atm: 3.0, catalyst: None, duration_hours: 8760.0, cross_recipe_group: None },
    Recipe { id: 2629, name: "Stalactite/Stalagmite Growth (CaCO3 Drip)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Limestone, 0.5), (S::CarbonDioxide, 0.1), (S::Water, 0.4)],
        outputs: &[(S::Stalactite, 1.0)],
        byproducts: &[(S::CarbonDioxide, 0.05)],
        min_temp_c: 12, pressure_atm: 1.0, catalyst: None, duration_hours: 876000.0, cross_recipe_group: None },
    Recipe { id: 2630, name: "Travertine Deposition (Hot Spring CaCO3)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Calcium, 0.4), (S::CarbonDioxide, 0.2), (S::Water, 0.4)],
        outputs: &[(S::Travertine, 1.0)],
        byproducts: &[(S::CarbonDioxide, 0.1)],
        min_temp_c: 40, pressure_atm: 1.0, catalyst: None, duration_hours: 87600.0, cross_recipe_group: None },
    Recipe { id: 2631, name: "Tufa Formation (Cold Spring CaCO3)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Calcium, 0.4), (S::CarbonDioxide, 0.2), (S::Water, 0.4)],
        outputs: &[(S::Tufa, 1.0)],
        byproducts: &[(S::CarbonDioxide, 0.1)],
        min_temp_c: 10, pressure_atm: 1.0, catalyst: None, duration_hours: 87600.0, cross_recipe_group: None },
    Recipe { id: 2632, name: "Geode Formation (Mineral-Lined Cavity)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::SilicaSand, 0.5), (S::Water, 0.5)],
        outputs: &[(S::Geode, 1.0)],
        byproducts: &[(S::Water, 0.3)],
        min_temp_c: 50, pressure_atm: 10.0, catalyst: None, duration_hours: 876000000.0, cross_recipe_group: None },
    Recipe { id: 2633, name: "Agate Formation (Banded Silica in Cavity)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::SilicaSand, 0.6), (S::Water, 0.3), (S::Iron, 0.1)],
        outputs: &[(S::Agate, 1.0)],
        byproducts: &[(S::Water, 0.2)],
        min_temp_c: 50, pressure_atm: 10.0, catalyst: None, duration_hours: 876000000.0, cross_recipe_group: None },
    Recipe { id: 2634, name: "Desert Varnish (Mn/Fe Oxide Biofilm Coating)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Manganese, 0.2), (S::Iron, 0.2), (S::Clay, 0.3), (S::Water, 0.3)],
        outputs: &[(S::DesertVarnish, 1.0)],
        byproducts: &[],
        min_temp_c: 30, pressure_atm: 1.0, catalyst: None, duration_hours: 876000.0, cross_recipe_group: None },
    Recipe { id: 2635, name: "Patination (Bronze→Green Cu2(OH)2CO3)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::TinBronze, 0.8), (S::CarbonDioxide, 0.1), (S::Water, 0.1)],
        outputs: &[(S::Patina, 0.9)],
        byproducts: &[(S::Tin, 0.1)],
        min_temp_c: 15, pressure_atm: 1.0, catalyst: None, duration_hours: 87600.0, cross_recipe_group: None },
    Recipe { id: 2636, name: "Rust Scale (Fe→FeOOH→Fe2O3 Layers)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Iron, 0.7), (S::Oxygen, 0.2), (S::Water, 0.1)],
        outputs: &[(S::RustScale, 1.0)],
        byproducts: &[],
        min_temp_c: 15, pressure_atm: 1.0, catalyst: None, duration_hours: 8760.0, cross_recipe_group: None },
    Recipe { id: 2637, name: "Saltpeter Efflorescence (KNO3 on Walls)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Nitrate, 0.4), (S::Potassium, 0.3), (S::Water, 0.3)],
        outputs: &[(S::Saltpeter, 0.8)],
        byproducts: &[(S::Water, 0.2)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 8760.0, cross_recipe_group: None },
    Recipe { id: 2638, name: "CaSO4 Scaling (Gypsum in Pipes)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Calcium, 0.3), (S::SulfuricAcid, 0.4), (S::Water, 0.3)],
        outputs: &[(S::Gypsum, 0.8)], // gypsum
        byproducts: &[(S::Water, 0.2)],
        min_temp_c: 50, pressure_atm: 3.0, catalyst: None, duration_hours: 8760.0, cross_recipe_group: None },
    Recipe { id: 2639, name: "Siliceous Sinter (Geyserite from Hot Springs)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::SilicaSand, 0.3), (S::Water, 0.7)],
        outputs: &[(S::Geyserite, 0.8)],
        byproducts: &[(S::Water, 0.5)],
        min_temp_c: 90, pressure_atm: 2.0, catalyst: None, duration_hours: 87600.0, cross_recipe_group: None },
    Recipe { id: 2640, name: "Iron Pan/Hardpan Formation (Cemented Soil)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Iron, 0.3), (S::Clay, 0.4), (S::Water, 0.3)],
        outputs: &[(S::IronPan, 1.0)],
        byproducts: &[],
        min_temp_c: 15, pressure_atm: 1.0, catalyst: None, duration_hours: 876000.0, cross_recipe_group: None },
    Recipe { id: 2641, name: "Calcrete/Caliche (Arid Soil Carbonate)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Calcium, 0.3), (S::CarbonDioxide, 0.2), (S::Clay, 0.3), (S::Water, 0.2)],
        outputs: &[(S::Calcrete, 1.0)],
        byproducts: &[],
        min_temp_c: 25, pressure_atm: 1.0, catalyst: None, duration_hours: 876000.0, cross_recipe_group: None },
];
