#![allow(dead_code)]
use super::types::*;
use super::substance::Substance as S;

pub static PHASE_CHANGE_RECIPES: &[Recipe] = &[
    // ===== WATER =====
    Recipe { id: 700, name: "Ice → Water (Melting)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Water, 1.0)], outputs: &[(S::Water, 1.0)], byproducts: &[],
        min_temp_c: 0, pressure_atm: 1.0, catalyst: None, duration_hours: 0.5, cross_recipe_group: None },
    Recipe { id: 701, name: "Water → Steam (Boiling)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Water, 1.0)], outputs: &[(S::Steam, 1.0)], byproducts: &[],
        min_temp_c: 100, pressure_atm: 1.0, catalyst: None, duration_hours: 0.5, cross_recipe_group: None },
    Recipe { id: 702, name: "Steam → Water (Condensation)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Steam, 1.0)], outputs: &[(S::Water, 1.0)], byproducts: &[],
        min_temp_c: -100, pressure_atm: 1.0, catalyst: None, duration_hours: 0.1, cross_recipe_group: None },
    Recipe { id: 703, name: "Freeze-Drying (Sublimation)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Water, 1.2)], outputs: &[(S::Water, 1.0)], byproducts: &[(S::Water, 0.2)],
        min_temp_c: -40, pressure_atm: 0.01, catalyst: None, duration_hours: 24.0, cross_recipe_group: None },

    // ===== METALS =====
    Recipe { id: 710, name: "Iron Sintering (Powder → Pellets)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Hematite, 1.1)], outputs: &[(S::Hematite, 1.0)], byproducts: &[],
        min_temp_c: 1300, pressure_atm: 1.0, catalyst: None, duration_hours: 2.0, cross_recipe_group: None },
    Recipe { id: 711, name: "Steel Quenching (Hardening)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::HighCarbonSteel, 1.0), (S::Water, 5.0)],
        outputs: &[(S::HighCarbonSteel, 1.0)], byproducts: &[(S::Steam, 4.0)],
        min_temp_c: 800, pressure_atm: 1.0, catalyst: None, duration_hours: 0.01, cross_recipe_group: None },
    Recipe { id: 712, name: "Steel Tempering", category: RecipeCategory::PhaseChange,
        inputs: &[(S::HighCarbonSteel, 1.0)],
        outputs: &[(S::MediumCarbonSteel, 1.0)], byproducts: &[],
        min_temp_c: 300, pressure_atm: 1.0, catalyst: None, duration_hours: 1.0, cross_recipe_group: None },
    Recipe { id: 713, name: "Steel Annealing (Softening)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::HighCarbonSteel, 1.0)],
        outputs: &[(S::LowCarbonSteel, 1.0)], byproducts: &[],
        min_temp_c: 700, pressure_atm: 1.0, catalyst: None, duration_hours: 8.0, cross_recipe_group: None },
    Recipe { id: 714, name: "Copper Annealing", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Copper, 1.0)], outputs: &[(S::Copper, 1.0)], byproducts: &[],
        min_temp_c: 400, pressure_atm: 1.0, catalyst: None, duration_hours: 2.0, cross_recipe_group: None },

    // ===== GLASS =====
    Recipe { id: 720, name: "Glass Annealing (Stress Relief)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Glass, 1.0)], outputs: &[(S::Glass, 1.0)], byproducts: &[],
        min_temp_c: 550, pressure_atm: 1.0, catalyst: None, duration_hours: 12.0, cross_recipe_group: None },
    Recipe { id: 721, name: "Glass Tempering (Safety Glass)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Glass, 1.0)], outputs: &[(S::Glass, 1.0)], byproducts: &[],
        min_temp_c: 620, pressure_atm: 1.0, catalyst: None, duration_hours: 0.1, cross_recipe_group: None },

    // ===== CO2 =====
    Recipe { id: 725, name: "Dry Ice Sublimation", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Carbon, 1.0)], outputs: &[(S::Air, 1.0)], byproducts: &[],
        min_temp_c: -78, pressure_atm: 1.0, catalyst: None, duration_hours: 0.5, cross_recipe_group: None },

    // ===== CRYSTALLIZATION =====
    Recipe { id: 730, name: "Salt Crystallization (from brine)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Water, 5.0)], outputs: &[(S::Salt, 1.0)], byproducts: &[(S::Water, 4.0)],
        min_temp_c: 100, pressure_atm: 1.0, catalyst: None, duration_hours: 6.0, cross_recipe_group: None },
    Recipe { id: 731, name: "Sugar Crystallization", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Water, 3.0)], outputs: &[(S::Sugar, 1.0)], byproducts: &[(S::Water, 2.0)],
        min_temp_c: 70, pressure_atm: 0.3, catalyst: None, duration_hours: 8.0, cross_recipe_group: None },

    // ===== CASTING =====
    Recipe { id: 735, name: "Iron Casting (Melting → Mold)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::CastIron, 1.02)], outputs: &[(S::CastIron, 1.0)], byproducts: &[(S::Slag, 0.02)],
        min_temp_c: 1200, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: None },
    Recipe { id: 736, name: "Bronze Casting", category: RecipeCategory::PhaseChange,
        inputs: &[(S::TinBronze, 1.01)], outputs: &[(S::TinBronze, 1.0)], byproducts: &[],
        min_temp_c: 1000, pressure_atm: 1.0, catalyst: None, duration_hours: 2.0, cross_recipe_group: None },
    Recipe { id: 737, name: "Aluminum Casting", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Aluminum, 1.02)], outputs: &[(S::Aluminum, 1.0)], byproducts: &[(S::Slag, 0.01)],
        min_temp_c: 660, pressure_atm: 1.0, catalyst: None, duration_hours: 2.0, cross_recipe_group: None },
    Recipe { id: 738, name: "Gold Casting", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Gold, 1.0)], outputs: &[(S::Gold, 1.0)], byproducts: &[],
        min_temp_c: 1064, pressure_atm: 1.0, catalyst: None, duration_hours: 1.0, cross_recipe_group: None },

    // ===== DISTILLATION =====
    Recipe { id: 740, name: "Mercury Distillation (Purification)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Mercury, 1.01)], outputs: &[(S::Mercury, 1.0)], byproducts: &[],
        min_temp_c: 357, pressure_atm: 1.0, catalyst: None, duration_hours: 2.0, cross_recipe_group: None },
    Recipe { id: 741, name: "Zinc Distillation (Purification)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Zinc, 1.05)], outputs: &[(S::Zinc, 1.0)], byproducts: &[(S::Lead, 0.02)],
        min_temp_c: 907, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: None },

    // ===== HEAT TREATMENTS =====
    Recipe { id: 2400, name: "Steel Normalizing", category: RecipeCategory::PhaseChange,
        inputs: &[(S::LowCarbonSteel, 1.0)],
        outputs: &[(S::LowCarbonSteel, 1.0)],
        byproducts: &[],
        min_temp_c: 870, pressure_atm: 1.0, catalyst: None, duration_hours: 2.0, cross_recipe_group: None },
    Recipe { id: 2401, name: "Steel Case Carburizing", category: RecipeCategory::PhaseChange,
        inputs: &[(S::LowCarbonSteel, 0.98), (S::Carbon, 0.02)],
        outputs: &[(S::MediumCarbonSteel, 1.0)],
        byproducts: &[],
        min_temp_c: 925, pressure_atm: 1.0, catalyst: None, duration_hours: 8.0, cross_recipe_group: None },
    Recipe { id: 2402, name: "Steel Nitriding", category: RecipeCategory::PhaseChange,
        inputs: &[(S::LowCarbonSteel, 0.99), (S::Nitrogen, 0.01)],
        outputs: &[(S::LowCarbonSteel, 1.0)], // nitrided surface
        byproducts: &[],
        min_temp_c: 520, pressure_atm: 1.0, catalyst: None, duration_hours: 24.0, cross_recipe_group: None },
    Recipe { id: 2403, name: "Steel Austempering", category: RecipeCategory::PhaseChange,
        inputs: &[(S::HighCarbonSteel, 0.95), (S::Salt, 0.05)],
        outputs: &[(S::HighCarbonSteel, 1.0)],
        byproducts: &[],
        min_temp_c: 350, pressure_atm: 1.0, catalyst: None, duration_hours: 2.0, cross_recipe_group: None },
    Recipe { id: 2404, name: "Aluminum T6 Heat Treat", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Duralumin, 1.0)],
        outputs: &[(S::Duralumin, 1.0)],
        byproducts: &[],
        min_temp_c: 530, pressure_atm: 1.0, catalyst: None, duration_hours: 2.0, cross_recipe_group: None },
    Recipe { id: 2405, name: "Age Hardening (Precipitation)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Duralumin, 1.0)],
        outputs: &[(S::Duralumin, 1.0)],
        byproducts: &[],
        min_temp_c: 175, pressure_atm: 1.0, catalyst: None, duration_hours: 12.0, cross_recipe_group: None },

    // ===== CASTING =====
    Recipe { id: 2406, name: "Sand Casting Iron", category: RecipeCategory::PhaseChange,
        inputs: &[(S::CastIron, 1.0), (S::Sand, 0.5)],
        outputs: &[(S::CastIron, 1.0)],
        byproducts: &[(S::Sand, 0.5)],
        min_temp_c: 1450, pressure_atm: 1.0, catalyst: None, duration_hours: 6.0, cross_recipe_group: None },
    Recipe { id: 2407, name: "Investment Casting (Lost Wax)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::LowCarbonSteel, 1.02)],
        outputs: &[(S::LowCarbonSteel, 1.0)],
        byproducts: &[(S::Slag, 0.02)],
        min_temp_c: 1600, pressure_atm: 1.0, catalyst: None, duration_hours: 8.0, cross_recipe_group: None },
    Recipe { id: 2408, name: "Die Casting Aluminum", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Aluminum, 1.02)],
        outputs: &[(S::Aluminum, 1.0)],
        byproducts: &[(S::Slag, 0.01)],
        min_temp_c: 680, pressure_atm: 1.0, catalyst: None, duration_hours: 0.1, cross_recipe_group: None },
    Recipe { id: 2409, name: "Centrifugal Casting", category: RecipeCategory::PhaseChange,
        inputs: &[(S::LowCarbonSteel, 1.02)],
        outputs: &[(S::LowCarbonSteel, 1.0)],
        byproducts: &[(S::Slag, 0.02)],
        min_temp_c: 1550, pressure_atm: 1.0, catalyst: None, duration_hours: 1.0, cross_recipe_group: None },
    Recipe { id: 2410, name: "Continuous Casting Steel", category: RecipeCategory::PhaseChange,
        inputs: &[(S::LowCarbonSteel, 1.01)],
        outputs: &[(S::LowCarbonSteel, 1.0)],
        byproducts: &[(S::Slag, 0.01)],
        min_temp_c: 1550, pressure_atm: 1.0, catalyst: None, duration_hours: 0.5, cross_recipe_group: None },
    Recipe { id: 2411, name: "Lost Foam Casting", category: RecipeCategory::PhaseChange,
        inputs: &[(S::CastIron, 1.0), (S::Polyethylene, 0.05), (S::Sand, 0.5)],
        outputs: &[(S::CastIron, 1.0)],
        byproducts: &[(S::Sand, 0.5)],
        min_temp_c: 1400, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: None },

    // ===== FORGING =====
    Recipe { id: 2412, name: "Open Die Forging", category: RecipeCategory::PhaseChange,
        inputs: &[(S::LowCarbonSteel, 1.05)],
        outputs: &[(S::LowCarbonSteel, 1.0)],
        byproducts: &[(S::Slag, 0.05)],
        min_temp_c: 1200, pressure_atm: 1.0, catalyst: None, duration_hours: 1.0, cross_recipe_group: None },
    Recipe { id: 2413, name: "Closed Die Forging", category: RecipeCategory::PhaseChange,
        inputs: &[(S::LowCarbonSteel, 1.03)],
        outputs: &[(S::LowCarbonSteel, 1.0)],
        byproducts: &[(S::Slag, 0.03)],
        min_temp_c: 1200, pressure_atm: 1.0, catalyst: None, duration_hours: 0.5, cross_recipe_group: None },
    Recipe { id: 2414, name: "Ring Rolling", category: RecipeCategory::PhaseChange,
        inputs: &[(S::LowCarbonSteel, 1.02)],
        outputs: &[(S::LowCarbonSteel, 1.0)],
        byproducts: &[],
        min_temp_c: 1100, pressure_atm: 1.0, catalyst: None, duration_hours: 0.5, cross_recipe_group: None },
    Recipe { id: 2415, name: "Cold Heading Fasteners", category: RecipeCategory::PhaseChange,
        inputs: &[(S::LowCarbonSteel, 1.05)],
        outputs: &[(S::LowCarbonSteel, 1.0)],
        byproducts: &[(S::Slag, 0.05)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.01, cross_recipe_group: None },
    Recipe { id: 2416, name: "Sheet Metal Stamping", category: RecipeCategory::PhaseChange,
        inputs: &[(S::LowCarbonSteel, 1.1)],
        outputs: &[(S::LowCarbonSteel, 1.0)],
        byproducts: &[(S::LowCarbonSteel, 0.1)], // scrap
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.01, cross_recipe_group: None },
    Recipe { id: 2417, name: "Hydroforming", category: RecipeCategory::PhaseChange,
        inputs: &[(S::LowCarbonSteel, 1.0), (S::Water, 0.5)],
        outputs: &[(S::LowCarbonSteel, 1.0)],
        byproducts: &[(S::Water, 0.5)],
        min_temp_c: 20, pressure_atm: 200.0, catalyst: None, duration_hours: 0.05, cross_recipe_group: None },

    // ===== WELDING =====
    Recipe { id: 2418, name: "Arc Welding (SMAW)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::LowCarbonSteel, 1.02)],
        outputs: &[(S::LowCarbonSteel, 1.0)],
        byproducts: &[(S::Slag, 0.02)],
        min_temp_c: 3500, pressure_atm: 1.0, catalyst: None, duration_hours: 0.5, cross_recipe_group: None },
    Recipe { id: 2419, name: "MIG Welding (GMAW)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::LowCarbonSteel, 1.01), (S::Argon, 0.1)],
        outputs: &[(S::LowCarbonSteel, 1.0)],
        byproducts: &[],
        min_temp_c: 2500, pressure_atm: 1.0, catalyst: None, duration_hours: 0.3, cross_recipe_group: None },
    Recipe { id: 2420, name: "TIG Welding (GTAW)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::LowCarbonSteel, 1.01), (S::Argon, 0.1), (S::Tungsten, 0.001)],
        outputs: &[(S::LowCarbonSteel, 1.0)],
        byproducts: &[],
        min_temp_c: 3000, pressure_atm: 1.0, catalyst: None, duration_hours: 0.5, cross_recipe_group: None },
    Recipe { id: 2421, name: "Oxy-Acetylene Welding", category: RecipeCategory::PhaseChange,
        inputs: &[(S::LowCarbonSteel, 1.01), (S::Acetylene, 0.2), (S::Oxygen, 0.2)],
        outputs: &[(S::LowCarbonSteel, 1.0)],
        byproducts: &[(S::CarbonDioxide, 0.3), (S::Water, 0.1)],
        min_temp_c: 3300, pressure_atm: 1.0, catalyst: None, duration_hours: 0.5, cross_recipe_group: None },
    Recipe { id: 2422, name: "Resistance Spot Welding", category: RecipeCategory::PhaseChange,
        inputs: &[(S::LowCarbonSteel, 1.0)],
        outputs: &[(S::LowCarbonSteel, 1.0)],
        byproducts: &[],
        min_temp_c: 1500, pressure_atm: 1.0, catalyst: None, duration_hours: 0.01, cross_recipe_group: None },
    Recipe { id: 2423, name: "Laser Welding", category: RecipeCategory::PhaseChange,
        inputs: &[(S::LowCarbonSteel, 1.0)],
        outputs: &[(S::LowCarbonSteel, 1.0)],
        byproducts: &[],
        min_temp_c: 2500, pressure_atm: 1.0, catalyst: None, duration_hours: 0.1, cross_recipe_group: None },
    Recipe { id: 2424, name: "Brazing", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Copper, 0.50), (S::Silver, 0.30), (S::Brass, 0.20)],
        outputs: &[(S::Brass, 1.0)], // brazed joint placeholder
        byproducts: &[],
        min_temp_c: 800, pressure_atm: 1.0, catalyst: None, duration_hours: 0.5, cross_recipe_group: None },
    Recipe { id: 2425, name: "Forge Welding", category: RecipeCategory::PhaseChange,
        inputs: &[(S::LowCarbonSteel, 1.02)],
        outputs: &[(S::LowCarbonSteel, 1.0)],
        byproducts: &[(S::Slag, 0.02)],
        min_temp_c: 1100, pressure_atm: 1.0, catalyst: None, duration_hours: 0.2, cross_recipe_group: None },

    // ===== SURFACE TREATMENTS =====
    Recipe { id: 2426, name: "Hot-Dip Galvanizing", category: RecipeCategory::PhaseChange,
        inputs: &[(S::LowCarbonSteel, 0.98), (S::Zinc, 0.02)],
        outputs: &[(S::LowCarbonSteel, 1.0)], // galvanized steel placeholder
        byproducts: &[],
        min_temp_c: 450, pressure_atm: 1.0, catalyst: None, duration_hours: 0.1, cross_recipe_group: None },
    Recipe { id: 2427, name: "Sherardizing", category: RecipeCategory::PhaseChange,
        inputs: &[(S::LowCarbonSteel, 0.99), (S::Zinc, 0.01)],
        outputs: &[(S::LowCarbonSteel, 1.0)], // sherardized placeholder
        byproducts: &[],
        min_temp_c: 400, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: None },
    Recipe { id: 2428, name: "Blueing (Gun Finish)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::LowCarbonSteel, 0.99), (S::SodiumHydroxide, 0.01)],
        outputs: &[(S::LowCarbonSteel, 1.0)], // blued steel placeholder
        byproducts: &[],
        min_temp_c: 310, pressure_atm: 1.0, catalyst: None, duration_hours: 0.5, cross_recipe_group: None },
    Recipe { id: 2429, name: "Parkerizing", category: RecipeCategory::PhaseChange,
        inputs: &[(S::LowCarbonSteel, 0.99), (S::PhosphoricAcid, 0.01)],
        outputs: &[(S::LowCarbonSteel, 1.0)], // parkerized placeholder
        byproducts: &[],
        min_temp_c: 90, pressure_atm: 1.0, catalyst: None, duration_hours: 0.3, cross_recipe_group: None },

    // ===== POLYMER PROCESSING =====
    Recipe { id: 2430, name: "Injection Molding", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Polyethylene, 1.05)],
        outputs: &[(S::Polyethylene, 1.0)],
        byproducts: &[(S::Polyethylene, 0.05)], // sprue/runner scrap
        min_temp_c: 250, pressure_atm: 100.0, catalyst: None, duration_hours: 0.01, cross_recipe_group: None },
    Recipe { id: 2431, name: "Blow Molding Bottles", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Polyethylene, 1.02)],
        outputs: &[(S::Polyethylene, 1.0)],
        byproducts: &[(S::Polyethylene, 0.02)], // trim scrap
        min_temp_c: 100, pressure_atm: 1.0, catalyst: None, duration_hours: 0.01, cross_recipe_group: None },
];
