#![allow(dead_code)]
use super::types::*;
use super::substance::Substance as S;

pub static ALLOY_RECIPES: &[Recipe] = &[
    // ===== STEELS =====
    Recipe { id: 200, name: "Low Carbon Steel (BOF)", category: RecipeCategory::Alloying,
        inputs: &[(S::PigIron, 0.75), (S::WroughtIron, 0.25), (S::Oxygen, 0.02)],
        outputs: &[(S::LowCarbonSteel, 1.0)],
        byproducts: &[(S::Slag, 0.1)],
        min_temp_c: 1650, pressure_atm: 1.0, catalyst: None, duration_hours: 0.5, cross_recipe_group: None },
    Recipe { id: 201, name: "Medium Carbon Steel", category: RecipeCategory::Alloying,
        inputs: &[(S::PigIron, 0.8), (S::Iron, 0.2), (S::Carbon, 0.005)],
        outputs: &[(S::MediumCarbonSteel, 1.0)],
        byproducts: &[(S::Slag, 0.05)],
        min_temp_c: 1650, pressure_atm: 1.0, catalyst: None, duration_hours: 0.5, cross_recipe_group: None },
    Recipe { id: 202, name: "High Carbon Steel (Crucible)", category: RecipeCategory::Alloying,
        inputs: &[(S::WroughtIron, 0.9), (S::Carbon, 0.01), (S::Charcoal, 0.1)],
        outputs: &[(S::HighCarbonSteel, 1.0)],
        byproducts: &[],
        min_temp_c: 1500, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: None },
    Recipe { id: 203, name: "Stainless Steel 304", category: RecipeCategory::Alloying,
        inputs: &[(S::Iron, 0.72), (S::Chromium, 0.18), (S::Nickel, 0.08), (S::Carbon, 0.001)],
        outputs: &[(S::StainlessSteel304, 1.0)],
        byproducts: &[(S::Slag, 0.02)],
        min_temp_c: 1500, pressure_atm: 1.0, catalyst: None, duration_hours: 1.0, cross_recipe_group: None },
    Recipe { id: 204, name: "Stainless Steel 316", category: RecipeCategory::Alloying,
        inputs: &[(S::Iron, 0.65), (S::Chromium, 0.17), (S::Nickel, 0.12), (S::Molybdenum, 0.025)],
        outputs: &[(S::StainlessSteel316, 1.0)],
        byproducts: &[(S::Slag, 0.02)],
        min_temp_c: 1500, pressure_atm: 1.0, catalyst: None, duration_hours: 1.0, cross_recipe_group: None },
    Recipe { id: 205, name: "Cast Iron", category: RecipeCategory::Alloying,
        inputs: &[(S::PigIron, 0.95), (S::Silicon, 0.03), (S::Carbon, 0.04)],
        outputs: &[(S::CastIron, 1.0)],
        byproducts: &[],
        min_temp_c: 1200, pressure_atm: 1.0, catalyst: None, duration_hours: 2.0, cross_recipe_group: None },
    Recipe { id: 206, name: "Tool Steel M2 (HSS)", category: RecipeCategory::Alloying,
        inputs: &[(S::Iron, 0.80), (S::Tungsten, 0.06), (S::Molybdenum, 0.05), (S::Chromium, 0.04), (S::Vanadium, 0.02)],
        outputs: &[(S::ToolSteel, 1.0)],
        byproducts: &[],
        min_temp_c: 1500, pressure_atm: 1.0, catalyst: None, duration_hours: 2.0, cross_recipe_group: None },

    // ===== COPPER ALLOYS =====
    Recipe { id: 210, name: "Tin Bronze", category: RecipeCategory::Alloying,
        inputs: &[(S::Copper, 0.88), (S::Tin, 0.12)],
        outputs: &[(S::TinBronze, 1.0)],
        byproducts: &[],
        min_temp_c: 1000, pressure_atm: 1.0, catalyst: None, duration_hours: 1.0, cross_recipe_group: None },
    Recipe { id: 211, name: "Phosphor Bronze", category: RecipeCategory::Alloying,
        inputs: &[(S::Copper, 0.948), (S::Tin, 0.05), (S::Phosphorus, 0.002)],
        outputs: &[(S::PhosphorBronze, 1.0)],
        byproducts: &[],
        min_temp_c: 1000, pressure_atm: 1.0, catalyst: None, duration_hours: 1.0, cross_recipe_group: None },
    Recipe { id: 212, name: "Aluminum Bronze", category: RecipeCategory::Alloying,
        inputs: &[(S::Copper, 0.90), (S::Aluminum, 0.10)],
        outputs: &[(S::AluminumBronze, 1.0)],
        byproducts: &[],
        min_temp_c: 1050, pressure_atm: 1.0, catalyst: None, duration_hours: 1.0, cross_recipe_group: None },
    Recipe { id: 213, name: "Brass (Yellow)", category: RecipeCategory::Alloying,
        inputs: &[(S::Copper, 0.67), (S::Zinc, 0.33)],
        outputs: &[(S::Brass, 1.0)],
        byproducts: &[],
        min_temp_c: 950, pressure_atm: 1.0, catalyst: None, duration_hours: 1.0, cross_recipe_group: None },
    Recipe { id: 214, name: "Cupronickel 70/30", category: RecipeCategory::Alloying,
        inputs: &[(S::Copper, 0.70), (S::Nickel, 0.30)],
        outputs: &[(S::CuproNickel, 1.0)],
        byproducts: &[],
        min_temp_c: 1250, pressure_atm: 1.0, catalyst: None, duration_hours: 1.0, cross_recipe_group: None },

    // ===== ALUMINUM ALLOYS =====
    Recipe { id: 220, name: "Duralumin (2024)", category: RecipeCategory::Alloying,
        inputs: &[(S::Aluminum, 0.93), (S::Copper, 0.045), (S::Magnesium, 0.015), (S::Manganese, 0.006)],
        outputs: &[(S::Duralumin, 1.0)],
        byproducts: &[],
        min_temp_c: 660, pressure_atm: 1.0, catalyst: None, duration_hours: 1.0, cross_recipe_group: None },

    // ===== NICKEL ALLOYS =====
    Recipe { id: 230, name: "Inconel 625", category: RecipeCategory::Alloying,
        inputs: &[(S::Nickel, 0.58), (S::Chromium, 0.215), (S::Molybdenum, 0.09), (S::Iron, 0.05)],
        outputs: &[(S::Inconel, 1.0)],
        byproducts: &[],
        min_temp_c: 1350, pressure_atm: 1.0, catalyst: None, duration_hours: 2.0, cross_recipe_group: None },
    Recipe { id: 231, name: "Monel 400", category: RecipeCategory::Alloying,
        inputs: &[(S::Nickel, 0.63), (S::Copper, 0.31), (S::Iron, 0.025)],
        outputs: &[(S::Monel, 1.0)],
        byproducts: &[],
        min_temp_c: 1350, pressure_atm: 1.0, catalyst: None, duration_hours: 2.0, cross_recipe_group: None },
    Recipe { id: 232, name: "Nichrome 80/20", category: RecipeCategory::Alloying,
        inputs: &[(S::Nickel, 0.80), (S::Chromium, 0.20)],
        outputs: &[(S::Nichrome, 1.0)],
        byproducts: &[],
        min_temp_c: 1400, pressure_atm: 1.0, catalyst: None, duration_hours: 1.0, cross_recipe_group: None },

    // ===== TITANIUM ALLOYS =====
    Recipe { id: 240, name: "Ti-6Al-4V", category: RecipeCategory::Alloying,
        inputs: &[(S::Titanium, 0.90), (S::Aluminum, 0.06), (S::Vanadium, 0.04)],
        outputs: &[(S::TiAlloy, 1.0)],
        byproducts: &[],
        min_temp_c: 1650, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: None },

    // ===== PRECIOUS =====
    Recipe { id: 250, name: "Sterling Silver", category: RecipeCategory::Alloying,
        inputs: &[(S::Silver, 0.925), (S::Copper, 0.075)],
        outputs: &[(S::SterlingSilver, 1.0)],
        byproducts: &[],
        min_temp_c: 900, pressure_atm: 1.0, catalyst: None, duration_hours: 0.5, cross_recipe_group: None },
    Recipe { id: 251, name: "Electrum", category: RecipeCategory::Alloying,
        inputs: &[(S::Gold, 0.75), (S::Silver, 0.25)],
        outputs: &[(S::Electrum, 1.0)],
        byproducts: &[],
        min_temp_c: 1000, pressure_atm: 1.0, catalyst: None, duration_hours: 0.5, cross_recipe_group: None },

    // ===== OTHER =====
    Recipe { id: 260, name: "Solder (63/37 Sn-Pb)", category: RecipeCategory::Alloying,
        inputs: &[(S::Tin, 0.63), (S::Lead, 0.37)],
        outputs: &[(S::Solder, 1.0)],
        byproducts: &[],
        min_temp_c: 190, pressure_atm: 1.0, catalyst: None, duration_hours: 0.2, cross_recipe_group: None },
    Recipe { id: 261, name: "Pewter", category: RecipeCategory::Alloying,
        inputs: &[(S::Tin, 0.92), (S::Copper, 0.04), (S::Nickel, 0.04)],
        outputs: &[(S::Pewter, 1.0)],
        byproducts: &[],
        min_temp_c: 240, pressure_atm: 1.0, catalyst: None, duration_hours: 0.5, cross_recipe_group: None },
    Recipe { id: 262, name: "Ferrochrome", category: RecipeCategory::Alloying,
        inputs: &[(S::Chromium, 0.55), (S::Iron, 0.38), (S::Carbon, 0.07)],
        outputs: &[(S::Ferrochrome, 1.0)],
        byproducts: &[],
        min_temp_c: 1600, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: None },
    Recipe { id: 263, name: "Ferromanganese", category: RecipeCategory::Alloying,
        inputs: &[(S::Manganese, 0.76), (S::Iron, 0.17), (S::Carbon, 0.07)],
        outputs: &[(S::Ferromanganese, 1.0)],
        byproducts: &[],
        min_temp_c: 1500, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: None },
    Recipe { id: 264, name: "Tungsten Carbide", category: RecipeCategory::Alloying,
        inputs: &[(S::Tungsten, 0.85), (S::Carbon, 0.06), (S::Cobalt, 0.09)],
        outputs: &[(S::TungstenCarbide, 1.0)],
        byproducts: &[],
        min_temp_c: 1500, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: None },
];
