#![allow(dead_code)]
use super::types::*;
use super::substance::Substance as S;

const CRG_BREAD: u32 = 300;
const CRG_LEATHER: u32 = 301;
const CRG_PAPER: u32 = 302;
const CRG_SALT: u32 = 303;

pub static BIOLOGICAL_RECIPES: &[Recipe] = &[
    // ===== BREAD (2 paths) =====
    Recipe { id: 600, name: "Yeasted Bread", category: RecipeCategory::FoodBiological,
        inputs: &[(S::Flour, 1.0), (S::Water, 0.65), (S::Yeast, 0.01), (S::Salt, 0.02)],
        outputs: &[(S::Bread, 1.3)],
        byproducts: &[],
        min_temp_c: 230, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: Some(CRG_BREAD) },
    Recipe { id: 601, name: "Sourdough Bread", category: RecipeCategory::FoodBiological,
        inputs: &[(S::Flour, 1.0), (S::Water, 0.70), (S::StarterCulture, 0.2), (S::Salt, 0.02)],
        outputs: &[(S::Bread, 1.3)],
        byproducts: &[],
        min_temp_c: 245, pressure_atm: 1.0, catalyst: None, duration_hours: 24.0, cross_recipe_group: Some(CRG_BREAD) },

    // ===== BEER + WINE + SPIRITS =====
    Recipe { id: 605, name: "Beer Brewing (All-Grain)", category: RecipeCategory::FoodBiological,
        inputs: &[(S::Flour, 5.0), (S::Water, 20.0), (S::Yeast, 0.01)],
        outputs: &[(S::Beer, 20.0)],
        byproducts: &[],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 336.0, cross_recipe_group: None },
    Recipe { id: 606, name: "Wine Making", category: RecipeCategory::FoodBiological,
        inputs: &[(S::Sugar, 3.0), (S::Water, 7.0), (S::Yeast, 0.005)],
        outputs: &[(S::Wine, 10.0)],
        byproducts: &[],
        min_temp_c: 22, pressure_atm: 1.0, catalyst: None, duration_hours: 672.0, cross_recipe_group: None },
    Recipe { id: 607, name: "Distilled Spirits", category: RecipeCategory::Refining,
        inputs: &[(S::Beer, 10.0)],
        outputs: &[(S::Spirits, 1.5)],
        byproducts: &[(S::Water, 8.0)],
        min_temp_c: 78, pressure_atm: 1.0, catalyst: None, duration_hours: 6.0, cross_recipe_group: None },

    // ===== DAIRY =====
    Recipe { id: 610, name: "Cheese Making (Hard)", category: RecipeCategory::FoodBiological,
        inputs: &[(S::Water, 10.0), (S::RennetEnzyme, 0.001), (S::StarterCulture, 0.01), (S::Salt, 0.02)],
        outputs: &[(S::Cheese, 1.0)],
        byproducts: &[(S::Water, 8.5)],
        min_temp_c: 38, pressure_atm: 1.0, catalyst: None, duration_hours: 2160.0, cross_recipe_group: None },
    Recipe { id: 611, name: "Butter Churning", category: RecipeCategory::FoodBiological,
        inputs: &[(S::Water, 2.0)],
        outputs: &[(S::Butter, 0.8)],
        byproducts: &[(S::Water, 1.0)],
        min_temp_c: 12, pressure_atm: 1.0, catalyst: None, duration_hours: 0.5, cross_recipe_group: None },
    Recipe { id: 612, name: "Yogurt", category: RecipeCategory::FoodBiological,
        inputs: &[(S::Water, 1.0), (S::StarterCulture, 0.02)],
        outputs: &[(S::Yogurt, 1.0)],
        byproducts: &[],
        min_temp_c: 44, pressure_atm: 1.0, catalyst: None, duration_hours: 6.0, cross_recipe_group: None },

    // ===== SUGAR + SALT + VINEGAR =====
    Recipe { id: 620, name: "Sugar Refining (Cane)", category: RecipeCategory::Refining,
        inputs: &[(S::Water, 10.0)],
        outputs: &[(S::Sugar, 1.0)],
        byproducts: &[(S::Water, 6.0)],
        min_temp_c: 80, pressure_atm: 1.0, catalyst: None, duration_hours: 12.0, cross_recipe_group: None },
    Recipe { id: 621, name: "Salt (Solar Evaporation)", category: RecipeCategory::FoodBiological,
        inputs: &[(S::Water, 30.0)],
        outputs: &[(S::Salt, 1.0)],
        byproducts: &[],
        min_temp_c: 25, pressure_atm: 1.0, catalyst: None, duration_hours: 2160.0, cross_recipe_group: Some(CRG_SALT) },
    Recipe { id: 622, name: "Salt (Rock Mining)", category: RecipeCategory::Extraction,
        inputs: &[(S::Limestone, 2.0)],
        outputs: &[(S::Salt, 1.0)],
        byproducts: &[(S::Gravel, 1.0)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 8.0, cross_recipe_group: Some(CRG_SALT) },
    Recipe { id: 623, name: "Vinegar (Acetic Fermentation)", category: RecipeCategory::FoodBiological,
        inputs: &[(S::Wine, 1.0), (S::Air, 0.5)],
        outputs: &[(S::Vinegar, 1.0)],
        byproducts: &[],
        min_temp_c: 28, pressure_atm: 1.0, catalyst: None, duration_hours: 2160.0, cross_recipe_group: None },

    // ===== PRESERVATION =====
    Recipe { id: 630, name: "Dried Meat (Jerky)", category: RecipeCategory::FoodBiological,
        inputs: &[(S::Water, 5.0), (S::Salt, 0.1)],
        outputs: &[(S::DriedMeat, 2.0)],
        byproducts: &[(S::Water, 3.0)],
        min_temp_c: 65, pressure_atm: 1.0, catalyst: None, duration_hours: 8.0, cross_recipe_group: None },
    Recipe { id: 631, name: "Pickling (Lacto-Fermentation)", category: RecipeCategory::FoodBiological,
        inputs: &[(S::Water, 5.0), (S::Salt, 0.15)],
        outputs: &[(S::Pickles, 5.0)],
        byproducts: &[],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 672.0, cross_recipe_group: None },
    Recipe { id: 632, name: "Fish Sauce", category: RecipeCategory::FoodBiological,
        inputs: &[(S::Water, 5.0), (S::Salt, 1.0)],
        outputs: &[(S::FishSauce, 3.0)],
        byproducts: &[],
        min_temp_c: 35, pressure_atm: 1.0, catalyst: None, duration_hours: 2160.0, cross_recipe_group: None },
    Recipe { id: 633, name: "Soy Sauce", category: RecipeCategory::FoodBiological,
        inputs: &[(S::Flour, 2.0), (S::Salt, 0.5), (S::Water, 5.0)],
        outputs: &[(S::SoySauce, 3.0)],
        byproducts: &[],
        min_temp_c: 25, pressure_atm: 1.0, catalyst: None, duration_hours: 8760.0, cross_recipe_group: None },

    // ===== OLIVE OIL =====
    Recipe { id: 640, name: "Olive Oil (Cold Press)", category: RecipeCategory::FoodBiological,
        inputs: &[(S::Water, 6.0)],
        outputs: &[(S::OliveOil, 1.0)],
        byproducts: &[(S::StrawFiber, 4.0)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 2.0, cross_recipe_group: None },

    // ===== TEXTILES =====
    Recipe { id: 650, name: "Cotton Fabric", category: RecipeCategory::Manufacturing,
        inputs: &[(S::CottonFiber, 1.1)],
        outputs: &[(S::CottonFiber, 1.0)],
        byproducts: &[(S::StrawFiber, 0.1)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 8.0, cross_recipe_group: None },
    Recipe { id: 651, name: "Wool Processing", category: RecipeCategory::Manufacturing,
        inputs: &[(S::WoolFiber, 1.5), (S::Water, 2.0)],
        outputs: &[(S::WoolFiber, 1.0)],
        byproducts: &[(S::Water, 1.5)],
        min_temp_c: 55, pressure_atm: 1.0, catalyst: None, duration_hours: 12.0, cross_recipe_group: None },
    Recipe { id: 652, name: "Silk Reeling", category: RecipeCategory::Manufacturing,
        inputs: &[(S::Water, 5.0)],
        outputs: &[(S::SilkFiber, 0.5)],
        byproducts: &[(S::Water, 4.0)],
        min_temp_c: 100, pressure_atm: 1.0, catalyst: None, duration_hours: 12.0, cross_recipe_group: None },
    Recipe { id: 653, name: "Linen Processing", category: RecipeCategory::Manufacturing,
        inputs: &[(S::LinenFiber, 2.0), (S::Water, 5.0)],
        outputs: &[(S::LinenFiber, 1.0)],
        byproducts: &[(S::Water, 5.0)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 336.0, cross_recipe_group: None },
    Recipe { id: 654, name: "Nylon Fiber Spinning", category: RecipeCategory::Manufacturing,
        inputs: &[(S::NylonResin, 1.0)],
        outputs: &[(S::NylonFiber, 0.95)],
        byproducts: &[],
        min_temp_c: 270, pressure_atm: 1.0, catalyst: None, duration_hours: 1.0, cross_recipe_group: None },

    // ===== LEATHER (2 paths) =====
    Recipe { id: 660, name: "Vegetable Tanned Leather", category: RecipeCategory::FoodBiological,
        inputs: &[(S::Water, 2.0), (S::Tannin, 0.5)],
        outputs: &[(S::LeatherProduct, 1.0)],
        byproducts: &[(S::Water, 1.0)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 1440.0, cross_recipe_group: Some(CRG_LEATHER) },
    Recipe { id: 661, name: "Chrome Tanned Leather", category: RecipeCategory::FoodBiological,
        inputs: &[(S::Water, 2.0), (S::Chromium, 0.05), (S::SulfuricAcid, 0.02)],
        outputs: &[(S::LeatherProduct, 1.0)],
        byproducts: &[(S::Water, 1.0)],
        min_temp_c: 30, pressure_atm: 1.0, catalyst: None, duration_hours: 48.0, cross_recipe_group: Some(CRG_LEATHER) },

    // ===== PAPER (2 paths) =====
    Recipe { id: 665, name: "Paper (Rag Method)", category: RecipeCategory::Manufacturing,
        inputs: &[(S::CottonFiber, 1.0), (S::Water, 5.0)],
        outputs: &[(S::PaperProduct, 1.0)],
        byproducts: &[(S::Water, 4.5)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 24.0, cross_recipe_group: Some(CRG_PAPER) },
    Recipe { id: 666, name: "Paper (Kraft/Wood Pulp)", category: RecipeCategory::Manufacturing,
        inputs: &[(S::WoodChips, 2.2), (S::SodiumHydroxide, 0.2), (S::Water, 5.0)],
        outputs: &[(S::PaperProduct, 1.0)],
        byproducts: &[(S::Water, 4.0)],
        min_temp_c: 170, pressure_atm: 8.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: Some(CRG_PAPER) },

    // ===== DYES =====
    Recipe { id: 670, name: "Indigo Dye (Natural)", category: RecipeCategory::FoodBiological,
        inputs: &[(S::Water, 10.0)],
        outputs: &[(S::IndigoDye, 0.3)],
        byproducts: &[(S::Water, 9.0)],
        min_temp_c: 25, pressure_atm: 1.0, catalyst: None, duration_hours: 48.0, cross_recipe_group: None },
    Recipe { id: 671, name: "Lye from Wood Ash", category: RecipeCategory::FoodBiological,
        inputs: &[(S::Charcoal, 2.0), (S::Water, 5.0)],
        outputs: &[(S::LyeSolution, 1.0)],
        byproducts: &[(S::Water, 4.0)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 24.0, cross_recipe_group: None },
    Recipe { id: 672, name: "Alum Production", category: RecipeCategory::FoodBiological,
        inputs: &[(S::Clay, 1.0), (S::SulfuricAcid, 0.5)],
        outputs: &[(S::AlumCompound, 1.0)],
        byproducts: &[(S::Water, 0.3)],
        min_temp_c: 600, pressure_atm: 1.0, catalyst: None, duration_hours: 12.0, cross_recipe_group: None },

    // ===== COMPOSTING =====
    Recipe { id: 675, name: "Composting", category: RecipeCategory::FoodBiological,
        inputs: &[(S::StrawFiber, 0.7), (S::Water, 1.0)],
        outputs: &[(S::Sand, 0.5)],
        byproducts: &[(S::Water, 0.5)],
        min_temp_c: 55, pressure_atm: 1.0, catalyst: None, duration_hours: 1344.0, cross_recipe_group: None },
];
