#![allow(dead_code)]
use super::types::*;
use super::substance::Substance as S;

const CRG_SULFURIC_ACID: u32 = 100;
const CRG_HYDROGEN: u32 = 11;
const CRG_ETHANOL: u32 = 102;
const CRG_SOAP: u32 = 103;

pub static CHEMISTRY_RECIPES: &[Recipe] = &[
    // ===== MAJOR INDUSTRIAL PROCESSES =====
    Recipe { id: 300, name: "Haber-Bosch (Ammonia)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Nitrogen, 0.82), (S::HydrogenGas, 0.18)],
        outputs: &[(S::Ammonia, 1.0)],
        byproducts: &[],
        min_temp_c: 450, pressure_atm: 200.0, catalyst: Some(S::Iron), duration_hours: 0.5,
        cross_recipe_group: None },
    Recipe { id: 301, name: "Contact Process (Sulfuric Acid from S)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Sulfur, 0.33), (S::Oxygen, 0.49), (S::Water, 0.18)],
        outputs: &[(S::SulfuricAcid, 1.0)],
        byproducts: &[],
        min_temp_c: 450, pressure_atm: 2.0, catalyst: Some(S::Vanadium), duration_hours: 2.0,
        cross_recipe_group: Some(CRG_SULFURIC_ACID) },
    Recipe { id: 302, name: "Sulfuric Acid from Pyrite Roast Gas", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::PyriteOre, 1.0), (S::Oxygen, 0.5), (S::Water, 0.2)],
        outputs: &[(S::SulfuricAcid, 0.8)],
        byproducts: &[(S::Hematite, 0.5)],
        min_temp_c: 450, pressure_atm: 2.0, catalyst: Some(S::Vanadium), duration_hours: 4.0,
        cross_recipe_group: Some(CRG_SULFURIC_ACID) },
    Recipe { id: 303, name: "Ostwald Process (Nitric Acid)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Ammonia, 0.26), (S::Oxygen, 0.61), (S::Water, 0.13)],
        outputs: &[(S::NitricAcid, 1.0)],
        byproducts: &[],
        min_temp_c: 900, pressure_atm: 8.0, catalyst: Some(S::Platinum), duration_hours: 1.0,
        cross_recipe_group: None },
    Recipe { id: 304, name: "Solvay Process (Soda Ash)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Salt, 1.2), (S::Limestone, 1.0), (S::Ammonia, 0.01)],
        outputs: &[(S::SodaAsh, 1.0)],
        byproducts: &[(S::Calcium, 0.5)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 12.0,
        cross_recipe_group: None },
    Recipe { id: 305, name: "Chloralkali (NaOH + Cl2)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Salt, 1.2), (S::Water, 0.4)],
        outputs: &[(S::SodiumHydroxide, 0.8), (S::ChlorineGas, 0.7), (S::HydrogenGas, 0.02)],
        byproducts: &[],
        min_temp_c: 80, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0,
        cross_recipe_group: None },
    Recipe { id: 306, name: "Fischer-Tropsch (Syngas → Fuel)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::SynGas, 2.5)],
        outputs: &[(S::Diesel, 1.0)],
        byproducts: &[(S::Water, 0.8)],
        min_temp_c: 220, pressure_atm: 25.0, catalyst: Some(S::Cobalt), duration_hours: 8.0,
        cross_recipe_group: None },
    Recipe { id: 307, name: "Steam Methane Reforming (Syngas)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::NaturalGas, 0.6), (S::Steam, 0.4)],
        outputs: &[(S::SynGas, 1.0)],
        byproducts: &[],
        min_temp_c: 850, pressure_atm: 25.0, catalyst: Some(S::Nickel), duration_hours: 1.0,
        cross_recipe_group: None },

    // ===== HYDROGEN (3 paths) =====
    Recipe { id: 310, name: "Water Electrolysis (Hydrogen)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Water, 9.0)],
        outputs: &[(S::HydrogenGas, 1.0), (S::Oxygen, 8.0)],
        byproducts: &[],
        min_temp_c: 70, pressure_atm: 1.0, catalyst: None, duration_hours: 2.0,
        cross_recipe_group: Some(CRG_HYDROGEN) },
    Recipe { id: 311, name: "Steam Reforming (Hydrogen)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::NaturalGas, 3.0), (S::Steam, 6.0)],
        outputs: &[(S::HydrogenGas, 1.0)],
        byproducts: &[(S::Carbon, 2.5)],
        min_temp_c: 850, pressure_atm: 25.0, catalyst: Some(S::Nickel), duration_hours: 1.0,
        cross_recipe_group: Some(CRG_HYDROGEN) },

    // ===== POLYMERS =====
    Recipe { id: 320, name: "Polyethylene (LDPE)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::NaturalGas, 1.2)],
        outputs: &[(S::Polyethylene, 1.0)],
        byproducts: &[],
        min_temp_c: 200, pressure_atm: 2000.0, catalyst: None, duration_hours: 2.0,
        cross_recipe_group: None },
    Recipe { id: 321, name: "Nylon 6,6", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::CrudeOil, 2.0), (S::Ammonia, 0.3)],
        outputs: &[(S::NylonResin, 1.0)],
        byproducts: &[(S::Water, 0.5)],
        min_temp_c: 280, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0,
        cross_recipe_group: None },
    Recipe { id: 322, name: "PVC", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::CrudeOil, 0.6), (S::ChlorineGas, 0.4)],
        outputs: &[(S::PVC, 1.0)],
        byproducts: &[],
        min_temp_c: 55, pressure_atm: 1.0, catalyst: None, duration_hours: 6.0,
        cross_recipe_group: None },
    Recipe { id: 323, name: "Synthetic Rubber (SBR)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::CrudeOil, 1.5), (S::Sulfur, 0.05)],
        outputs: &[(S::SyntheticRubber, 1.0)],
        byproducts: &[],
        min_temp_c: 50, pressure_atm: 1.0, catalyst: None, duration_hours: 8.0,
        cross_recipe_group: None },

    // ===== EXPLOSIVES =====
    Recipe { id: 330, name: "Gunpowder", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Salt, 0.75), (S::Charcoal, 0.15), (S::Sulfur, 0.10)],
        outputs: &[(S::Gunpowder, 1.0)],
        byproducts: &[],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 2.0,
        cross_recipe_group: None },
    Recipe { id: 331, name: "Nitroglycerin", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Glycerol, 0.4), (S::NitricAcid, 0.5), (S::SulfuricAcid, 0.3)],
        outputs: &[(S::Nitroglycerin, 1.0)],
        byproducts: &[(S::Water, 0.2)],
        min_temp_c: 5, pressure_atm: 1.0, catalyst: None, duration_hours: 1.0,
        cross_recipe_group: None },
    Recipe { id: 332, name: "Dynamite", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Nitroglycerin, 0.75), (S::DiatomaceousEarth, 0.25)],
        outputs: &[(S::Dynamite, 1.0)],
        byproducts: &[],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.5,
        cross_recipe_group: None },
    Recipe { id: 333, name: "TNT", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Toluene, 0.4), (S::NitricAcid, 0.4), (S::SulfuricAcid, 0.3)],
        outputs: &[(S::TNT, 1.0)],
        byproducts: &[(S::Water, 0.2)],
        min_temp_c: 80, pressure_atm: 1.0, catalyst: None, duration_hours: 6.0,
        cross_recipe_group: None },
    Recipe { id: 334, name: "Ammonium Nitrate", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Ammonia, 0.21), (S::NitricAcid, 0.79)],
        outputs: &[(S::AmmoniumNitrate, 1.0)],
        byproducts: &[],
        min_temp_c: 50, pressure_atm: 1.0, catalyst: None, duration_hours: 1.0,
        cross_recipe_group: None },
    Recipe { id: 335, name: "Urea", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Ammonia, 0.57), (S::Carbon, 0.20)],
        outputs: &[(S::Urea, 1.0)],
        byproducts: &[(S::Water, 0.3)],
        min_temp_c: 180, pressure_atm: 200.0, catalyst: None, duration_hours: 2.0,
        cross_recipe_group: None },

    // ===== OTHER CHEMICALS =====
    Recipe { id: 340, name: "Calcium Carbide", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Quicklite, 0.9), (S::Coke, 0.6)],
        outputs: &[(S::CalciumCarbide, 1.0)],
        byproducts: &[],
        min_temp_c: 2000, pressure_atm: 1.0, catalyst: None, duration_hours: 2.0,
        cross_recipe_group: None },
    Recipe { id: 341, name: "Acetylene from Carbide", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::CalciumCarbide, 1.0), (S::Water, 0.6)],
        outputs: &[(S::Acetylene, 0.4)],
        byproducts: &[(S::SlakedLite, 1.2)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.1,
        cross_recipe_group: None },
    Recipe { id: 342, name: "Bleach (Sodium Hypochlorite)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::ChlorineGas, 0.5), (S::SodiumHydroxide, 0.6)],
        outputs: &[(S::BleachSolution, 1.0)],
        byproducts: &[(S::Salt, 0.08)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.2,
        cross_recipe_group: None },
    Recipe { id: 343, name: "Phosphoric Acid (Wet Process)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::PhosphateRock, 1.5), (S::SulfuricAcid, 1.5)],
        outputs: &[(S::PhosphoricAcid, 1.0)],
        byproducts: &[(S::Calcium, 1.0)],
        min_temp_c: 80, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0,
        cross_recipe_group: None },
    Recipe { id: 344, name: "Hydrochloric Acid", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::ChlorineGas, 0.7), (S::HydrogenGas, 0.03)],
        outputs: &[(S::HydrochloricAcid, 1.0)],
        byproducts: &[],
        min_temp_c: 200, pressure_atm: 1.0, catalyst: None, duration_hours: 0.5,
        cross_recipe_group: None },
    Recipe { id: 345, name: "Hydrogen Peroxide", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::HydrogenGas, 0.06), (S::Oxygen, 0.94)],
        outputs: &[(S::HydrogenPeroxide, 1.0)],
        byproducts: &[],
        min_temp_c: 40, pressure_atm: 3.0, catalyst: Some(S::Nickel), duration_hours: 4.0,
        cross_recipe_group: None },
    Recipe { id: 346, name: "Formaldehyde", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Methanol, 0.9), (S::Oxygen, 0.1)],
        outputs: &[(S::Formaldehyde, 1.0)],
        byproducts: &[(S::Water, 0.2)],
        min_temp_c: 600, pressure_atm: 1.0, catalyst: Some(S::Silver), duration_hours: 0.5,
        cross_recipe_group: None },

    // ===== SOAP (2 paths) =====
    Recipe { id: 350, name: "Soap (Cold Process)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::OliveOil, 0.8), (S::SodiumHydroxide, 0.12), (S::Water, 0.2)],
        outputs: &[(S::SoapProduct, 1.0)],
        byproducts: &[(S::Glycerol, 0.1)],
        min_temp_c: 40, pressure_atm: 1.0, catalyst: None, duration_hours: 1008.0,
        cross_recipe_group: Some(CRG_SOAP) },
    Recipe { id: 351, name: "Soap (Hot Process)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::OliveOil, 0.8), (S::SodiumHydroxide, 0.12), (S::Water, 0.2)],
        outputs: &[(S::SoapProduct, 1.0)],
        byproducts: &[(S::Glycerol, 0.1)],
        min_temp_c: 75, pressure_atm: 1.0, catalyst: None, duration_hours: 3.0,
        cross_recipe_group: Some(CRG_SOAP) },

    // ===== VULCANIZATION =====
    Recipe { id: 355, name: "Rubber Vulcanization", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::NaturalRubber, 0.95), (S::Sulfur, 0.03), (S::Zinc, 0.02)],
        outputs: &[(S::VulcanizedRubber, 1.0)],
        byproducts: &[],
        min_temp_c: 150, pressure_atm: 3.0, catalyst: None, duration_hours: 0.5,
        cross_recipe_group: None },

    // ===== MORE POLYMERS =====
    Recipe { id: 360, name: "Polyester (PET)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::CrudeOil, 1.5)],
        outputs: &[(S::PolyesterFiber, 1.0)],
        byproducts: &[(S::Water, 0.3)],
        min_temp_c: 280, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: None },
    Recipe { id: 361, name: "Polypropylene", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::CrudeOil, 1.3)],
        outputs: &[(S::Polyethylene, 1.0)], // PP placeholder
        byproducts: &[],
        min_temp_c: 70, pressure_atm: 30.0, catalyst: Some(S::Titanium), duration_hours: 3.0, cross_recipe_group: None },
    Recipe { id: 362, name: "Polystyrene", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Benzene, 0.6), (S::CrudeOil, 0.5)],
        outputs: &[(S::Polyethylene, 1.0)], // PS placeholder
        byproducts: &[],
        min_temp_c: 120, pressure_atm: 1.0, catalyst: None, duration_hours: 6.0, cross_recipe_group: None },
    Recipe { id: 363, name: "Acrylic Fiber", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::CrudeOil, 1.2), (S::Ammonia, 0.2)],
        outputs: &[(S::NylonFiber, 1.0)], // acrylic placeholder
        byproducts: &[],
        min_temp_c: 55, pressure_atm: 1.0, catalyst: None, duration_hours: 8.0, cross_recipe_group: None },

    // ===== PHARMACEUTICAL =====
    Recipe { id: 370, name: "Aspirin Synthesis", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::CrudeOil, 0.5), (S::SulfuricAcid, 0.1)],
        outputs: &[(S::SoapProduct, 0.9)], // aspirin placeholder
        byproducts: &[(S::Water, 0.1)],
        min_temp_c: 90, pressure_atm: 1.0, catalyst: Some(S::PhosphoricAcid), duration_hours: 0.5, cross_recipe_group: None },
    Recipe { id: 371, name: "Penicillin Fermentation", category: RecipeCategory::FoodBiological,
        inputs: &[(S::Sugar, 2.0), (S::Water, 10.0)],
        outputs: &[(S::SoapProduct, 0.04)], // penicillin placeholder
        byproducts: &[(S::Water, 10.0)],
        min_temp_c: 26, pressure_atm: 1.0, catalyst: None, duration_hours: 168.0, cross_recipe_group: None },

    // ===== SEMICONDUCTOR =====
    Recipe { id: 375, name: "Trichlorosilane (for Siemens)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Silicon, 1.0), (S::HydrochloricAcid, 3.5)],
        outputs: &[(S::TitaniumTetrachloride, 1.0)], // SiHCl3 placeholder
        byproducts: &[(S::HydrogenGas, 0.1)],
        min_temp_c: 320, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: None },

    // ===== WATER TREATMENT =====
    Recipe { id: 380, name: "Potable Water (Chlorination)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Water, 1000.0), (S::ChlorineGas, 0.002)],
        outputs: &[(S::Water, 1000.0)],
        byproducts: &[],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.5, cross_recipe_group: None },
    Recipe { id: 381, name: "Distilled Water", category: RecipeCategory::Refining,
        inputs: &[(S::Water, 1.2)],
        outputs: &[(S::Water, 1.0)],
        byproducts: &[(S::Salt, 0.04)],
        min_temp_c: 100, pressure_atm: 1.0, catalyst: None, duration_hours: 2.0, cross_recipe_group: None },

    // ===== METHANOL =====
    Recipe { id: 385, name: "Methanol from Syngas", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::SynGas, 1.5)],
        outputs: &[(S::Methanol, 1.0)],
        byproducts: &[(S::Water, 0.3)],
        min_temp_c: 250, pressure_atm: 80.0, catalyst: Some(S::Copper), duration_hours: 2.0, cross_recipe_group: None },

    // ===== ACETONE =====
    Recipe { id: 386, name: "Acetone (Cumene Process)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Benzene, 0.5), (S::CrudeOil, 0.5)],
        outputs: &[(S::Acetone, 0.4)],
        byproducts: &[(S::SoapProduct, 0.6)], // phenol byproduct
        min_temp_c: 90, pressure_atm: 1.0, catalyst: Some(S::SulfuricAcid), duration_hours: 3.0, cross_recipe_group: None },

    // ===== TOLUENE =====
    Recipe { id: 387, name: "Toluene (Catalytic Reforming)", category: RecipeCategory::Refining,
        inputs: &[(S::CrudeOil, 1.5)],
        outputs: &[(S::Toluene, 1.0)],
        byproducts: &[(S::HydrogenGas, 0.05)],
        min_temp_c: 500, pressure_atm: 25.0, catalyst: Some(S::Platinum), duration_hours: 2.0, cross_recipe_group: None },

    // ===== BENZENE =====
    Recipe { id: 388, name: "Benzene (Catalytic Reforming)", category: RecipeCategory::Refining,
        inputs: &[(S::CrudeOil, 1.5)],
        outputs: &[(S::Benzene, 1.0)],
        byproducts: &[(S::HydrogenGas, 0.05)],
        min_temp_c: 500, pressure_atm: 25.0, catalyst: Some(S::Platinum), duration_hours: 2.0, cross_recipe_group: None },

    // ===== GLYCEROL =====
    Recipe { id: 389, name: "Glycerol (from Biodiesel)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::OliveOil, 1.0), (S::Methanol, 0.15)],
        outputs: &[(S::Biodiesel, 1.0), (S::Glycerol, 0.1)],
        byproducts: &[],
        min_temp_c: 55, pressure_atm: 1.0, catalyst: Some(S::SodiumHydroxide), duration_hours: 2.0, cross_recipe_group: None },

    // ===== SALTPETER =====
    Recipe { id: 390, name: "Saltpeter (Niter Bed)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::StrawFiber, 5.0), (S::Water, 10.0), (S::Charcoal, 1.0)],
        outputs: &[(S::Salt, 0.5)], // KNO3 placeholder
        byproducts: &[(S::Water, 8.0)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 8760.0, cross_recipe_group: None },

    // ===== ESSENTIAL OIL =====
    Recipe { id: 391, name: "Essential Oil (Steam Distillation)", category: RecipeCategory::Refining,
        inputs: &[(S::StrawFiber, 50.0), (S::Steam, 20.0)],
        outputs: &[(S::OliveOil, 1.0)], // essential oil placeholder
        byproducts: &[(S::Water, 60.0)],
        min_temp_c: 100, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: None },

    // ===== SMOKELESS POWDER =====
    Recipe { id: 392, name: "Smokeless Powder (Nitrocellulose)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::CottonFiber, 0.5), (S::NitricAcid, 1.0), (S::SulfuricAcid, 1.0)],
        outputs: &[(S::Gunpowder, 0.8)], // smokeless powder placeholder
        byproducts: &[(S::Water, 1.0)],
        min_temp_c: 30, pressure_atm: 1.0, catalyst: None, duration_hours: 2.0, cross_recipe_group: None },

    // ===== PHOTOGRAPHIC =====
    Recipe { id: 393, name: "Silver Nitrate", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Silver, 0.63), (S::NitricAcid, 0.37)],
        outputs: &[(S::Silver, 1.0)], // AgNO3 placeholder
        byproducts: &[(S::Water, 0.1)],
        min_temp_c: 70, pressure_atm: 1.0, catalyst: None, duration_hours: 1.0, cross_recipe_group: None },
];
