#![allow(dead_code)]
use super::types::*;
use super::substance::Substance as S;

pub static FUEL_RECIPES: &[Recipe] = &[
    Recipe { id: 500, name: "Charcoal (Wood Pyrolysis)", category: RecipeCategory::FuelProcessing,
        inputs: &[(S::WoodLogs, 5.0)],
        outputs: &[(S::Charcoal, 1.0)],
        byproducts: &[(S::Water, 1.5), (S::Methanol, 0.1)],
        min_temp_c: 450, pressure_atm: 1.0, catalyst: None, duration_hours: 72.0, cross_recipe_group: None },
    Recipe { id: 501, name: "Coke (Coal Coking)", category: RecipeCategory::FuelProcessing,
        inputs: &[(S::Carbon, 1.3)],
        outputs: &[(S::Coke, 1.0)],
        byproducts: &[(S::Toluene, 0.03), (S::Ammonia, 0.01), (S::Benzene, 0.02)],
        min_temp_c: 1100, pressure_atm: 1.0, catalyst: None, duration_hours: 24.0, cross_recipe_group: None },
    Recipe { id: 502, name: "Petroleum Fractional Distillation", category: RecipeCategory::Refining,
        inputs: &[(S::CrudeOil, 1.0)],
        outputs: &[(S::Gasoline, 0.25), (S::Kerosene, 0.12), (S::Diesel, 0.25), (S::FuelOil, 0.15), (S::Bitumen, 0.08)],
        byproducts: &[(S::NaturalGas, 0.05)],
        min_temp_c: 400, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: None },
    Recipe { id: 503, name: "Biodiesel (Transesterification)", category: RecipeCategory::FuelProcessing,
        inputs: &[(S::OliveOil, 1.0), (S::Methanol, 0.15), (S::SodiumHydroxide, 0.01)],
        outputs: &[(S::Biodiesel, 1.0)],
        byproducts: &[(S::Glycerol, 0.1)],
        min_temp_c: 55, pressure_atm: 1.0, catalyst: None, duration_hours: 2.0, cross_recipe_group: None },
    Recipe { id: 504, name: "Ethanol Fermentation (Grain)", category: RecipeCategory::FuelProcessing,
        inputs: &[(S::Flour, 2.0), (S::Water, 3.0), (S::Yeast, 0.01)],
        outputs: &[(S::Ethanol, 1.0)],
        byproducts: &[],
        min_temp_c: 30, pressure_atm: 1.0, catalyst: None, duration_hours: 72.0, cross_recipe_group: None },
    Recipe { id: 505, name: "Biogas (Anaerobic Digestion)", category: RecipeCategory::FuelProcessing,
        inputs: &[(S::StrawFiber, 1.0), (S::Water, 2.0)],
        outputs: &[(S::Biogas, 0.5)],
        byproducts: &[],
        min_temp_c: 37, pressure_atm: 1.0, catalyst: None, duration_hours: 720.0, cross_recipe_group: None },
    Recipe { id: 506, name: "Activated Carbon", category: RecipeCategory::FuelProcessing,
        inputs: &[(S::Charcoal, 1.0), (S::Steam, 1.0)],
        outputs: &[(S::ActivatedCarbon, 0.6)],
        byproducts: &[],
        min_temp_c: 1000, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: None },
    Recipe { id: 507, name: "Liquid Oxygen (Cryogenic)", category: RecipeCategory::Refining,
        inputs: &[(S::Air, 5.0)],
        outputs: &[(S::LiquidOxygen, 1.0)],
        byproducts: &[(S::Nitrogen, 3.8)],
        min_temp_c: -183, pressure_atm: 1.0, catalyst: None, duration_hours: 2.0, cross_recipe_group: None },
    Recipe { id: 508, name: "Liquid Hydrogen (Cryogenic)", category: RecipeCategory::Refining,
        inputs: &[(S::HydrogenGas, 1.0)],
        outputs: &[(S::LiquidHydrogen, 1.0)],
        byproducts: &[],
        min_temp_c: -253, pressure_atm: 1.0, catalyst: None, duration_hours: 2.0, cross_recipe_group: None },

    // ===== MORE FUEL =====
    Recipe { id: 510, name: "Catalytic Cracking (Heavy → Gasoline)", category: RecipeCategory::Refining,
        inputs: &[(S::FuelOil, 1.0)],
        outputs: &[(S::Gasoline, 0.55), (S::NaturalGas, 0.15)],
        byproducts: &[(S::Coke, 0.05)],
        min_temp_c: 500, pressure_atm: 2.0, catalyst: Some(S::Silicon), duration_hours: 0.1, cross_recipe_group: None },
    Recipe { id: 511, name: "Hydrocracking", category: RecipeCategory::Refining,
        inputs: &[(S::FuelOil, 1.0), (S::HydrogenGas, 0.03)],
        outputs: &[(S::Diesel, 0.6), (S::Kerosene, 0.25)],
        byproducts: &[(S::NaturalGas, 0.05)],
        min_temp_c: 400, pressure_atm: 150.0, catalyst: Some(S::Nickel), duration_hours: 0.5, cross_recipe_group: None },
    Recipe { id: 512, name: "Ethanol from Sugar", category: RecipeCategory::FuelProcessing,
        inputs: &[(S::Sugar, 1.8), (S::Water, 3.0), (S::Yeast, 0.01)],
        outputs: &[(S::Ethanol, 1.0)],
        byproducts: &[],
        min_temp_c: 30, pressure_atm: 1.0, catalyst: None, duration_hours: 48.0, cross_recipe_group: None },
    Recipe { id: 513, name: "Wood Gas (Gasification)", category: RecipeCategory::FuelProcessing,
        inputs: &[(S::WoodChips, 3.0), (S::Air, 2.0)],
        outputs: &[(S::SynGas, 1.0)],
        byproducts: &[(S::Charcoal, 0.3)],
        min_temp_c: 900, pressure_atm: 1.0, catalyst: None, duration_hours: 1.0, cross_recipe_group: None },
    Recipe { id: 514, name: "Coal Gasification", category: RecipeCategory::FuelProcessing,
        inputs: &[(S::Carbon, 2.0), (S::Steam, 1.0), (S::Oxygen, 0.5)],
        outputs: &[(S::SynGas, 1.5)],
        byproducts: &[(S::Slag, 0.3)],
        min_temp_c: 1200, pressure_atm: 30.0, catalyst: None, duration_hours: 2.0, cross_recipe_group: None },
    Recipe { id: 515, name: "Solid Rocket Propellant APCP", category: RecipeCategory::FuelProcessing,
        inputs: &[(S::AmmoniumNitrate, 0.70), (S::Aluminum, 0.16), (S::NaturalRubber, 0.12)],
        outputs: &[(S::NaturalRubber, 1.0)], // APCP placeholder
        byproducts: &[],
        min_temp_c: 60, pressure_atm: 1.0, catalyst: None, duration_hours: 120.0, cross_recipe_group: None },
    Recipe { id: 516, name: "Methanol from Wood (Historical)", category: RecipeCategory::FuelProcessing,
        inputs: &[(S::WoodLogs, 10.0)],
        outputs: &[(S::Methanol, 0.3), (S::Charcoal, 2.0)],
        byproducts: &[(S::Water, 3.0)],
        min_temp_c: 450, pressure_atm: 1.0, catalyst: None, duration_hours: 72.0, cross_recipe_group: None },
    Recipe { id: 517, name: "Peat Briquettes", category: RecipeCategory::FuelProcessing,
        inputs: &[(S::StrawFiber, 3.0), (S::Water, 1.0)],
        outputs: &[(S::Charcoal, 1.0)], // peat placeholder
        byproducts: &[(S::Water, 2.0)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 2160.0, cross_recipe_group: None },
];
