#![allow(dead_code)]
use super::types::*;
use super::substance::Substance as S;

pub static INORGANIC_RECIPES: &[Recipe] = &[
    // ===== ACID-BASE NEUTRALIZATION =====
    Recipe { id: 900, name: "HCl + NaOH → NaCl", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::HydrochloricAcid, 0.55), (S::SodiumHydroxide, 0.45)],
        outputs: &[(S::SodiumChloride, 0.88)], byproducts: &[(S::Water, 0.12)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.01, cross_recipe_group: None },
    Recipe { id: 901, name: "H2SO4 + CaCO3 → Gypsum", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::SulfuricAcid, 0.50), (S::Limestone, 0.50)],
        outputs: &[(S::ite, 0.80)], byproducts: &[(S::Water, 0.10), (S::CarbonDioxide, 0.10)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.5, cross_recipe_group: None },
    Recipe { id: 902, name: "HCl + NaHCO3 → NaCl + CO2", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::HydrochloricAcid, 0.4), (S::SodaAsh, 0.6)],
        outputs: &[(S::SodiumChloride, 0.6)], byproducts: &[(S::Water, 0.2), (S::CarbonDioxide, 0.2)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.01, cross_recipe_group: None },
    Recipe { id: 903, name: "HNO3 + KOH → KNO3 (Saltpeter)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::NitricAcid, 0.55), (S::SodiumHydroxide, 0.45)],
        outputs: &[(S::PotassiumNitrate, 0.90)], byproducts: &[(S::Water, 0.10)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.01, cross_recipe_group: None },
    Recipe { id: 904, name: "2HCl + Ca(OH)2 → CaCl2", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::HydrochloricAcid, 0.55), (S::SlakedLite, 0.45)],
        outputs: &[(S::CalciumChloride, 0.85)], byproducts: &[(S::Water, 0.15)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.01, cross_recipe_group: None },

    // ===== PRECIPITATION =====
    Recipe { id: 910, name: "BaCl2 + Na2SO4 → BaSO4 (White)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::CalciumChloride, 0.5), (S::SodiumSulfate, 0.5)],
        outputs: &[(S::BariumSulfate, 0.8)], byproducts: &[(S::SodiumChloride, 0.2)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.01, cross_recipe_group: None },
    Recipe { id: 911, name: "AgNO3 + NaCl → AgCl (Photography)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Silver, 0.6), (S::NitricAcid, 0.1), (S::SodiumChloride, 0.3)],
        outputs: &[(S::SilverChloride, 0.9)], byproducts: &[],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.01, cross_recipe_group: None },
    Recipe { id: 912, name: "FeCl3 + NaOH → Fe(OH)3 (Water Treatment)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Iron, 0.3), (S::HydrochloricAcid, 0.3), (S::SodiumHydroxide, 0.4)],
        outputs: &[(S::IronHydroxide, 0.8)], byproducts: &[(S::SodiumChloride, 0.2)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.01, cross_recipe_group: None },
    Recipe { id: 913, name: "Pb(NO3)2 + KI → PbI2 (Golden Rain)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Lead, 0.5), (S::NitricAcid, 0.2), (S::Salt, 0.3)],
        outputs: &[(S::LeadIodide, 0.9)], byproducts: &[(S::PotassiumNitrate, 0.1)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.01, cross_recipe_group: None },

    // ===== REDOX =====
    Recipe { id: 920, name: "Thermite (Fe2O3 + Al)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Hematite, 0.7), (S::Aluminum, 0.3)],
        outputs: &[(S::Iron, 0.5)], byproducts: &[(S::Alumina, 0.5)],
        min_temp_c: 2500, pressure_atm: 1.0, catalyst: None, duration_hours: 0.001, cross_recipe_group: None },
    Recipe { id: 921, name: "H2O2 Decomposition", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::HydrogenPeroxide, 1.0)], outputs: &[(S::Water, 0.53), (S::Oxygen, 0.47)],
        byproducts: &[],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: Some(S::Manganese), duration_hours: 0.01, cross_recipe_group: None },
    Recipe { id: 922, name: "Sodium + Water (Explosive)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Sodium, 0.5), (S::Water, 0.5)], outputs: &[(S::SodiumHydroxide, 0.85)],
        byproducts: &[(S::HydrogenGas, 0.02)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.001, cross_recipe_group: None },
    Recipe { id: 923, name: "Magnesium Burning", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Magnesium, 0.6), (S::Oxygen, 0.4)], outputs: &[(S::MagnesiumOxide, 1.0)],
        byproducts: &[],
        min_temp_c: 473, pressure_atm: 1.0, catalyst: None, duration_hours: 0.001, cross_recipe_group: None },
    Recipe { id: 924, name: "Iron Displacement (Fe + CuSO4)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Iron, 0.5), (S::Copper, 0.5)],
        outputs: &[(S::Copper, 0.55)], byproducts: &[(S::Iron, 0.45)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 2.0, cross_recipe_group: None },
    Recipe { id: 925, name: "Iron Rusting", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Iron, 0.7), (S::Oxygen, 0.2), (S::Water, 0.1)],
        outputs: &[(S::IronHydroxide, 1.0)], byproducts: &[],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 720.0, cross_recipe_group: None },

    // ===== COMPLEXATION =====
    Recipe { id: 930, name: "Prussian Blue Synthesis", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Iron, 0.4), (S::HydrochloricAcid, 0.3), (S::SodiumCyanide, 0.3)],
        outputs: &[(S::PrussianBlue, 1.0)], byproducts: &[(S::SodiumChloride, 0.1)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.1, cross_recipe_group: None },
];
