#![allow(dead_code)]
use super::types::*;
use super::substance::Substance as S;

pub static INORGANIC_RECIPES: &[Recipe] = &[
    // ===== ACID-BASE NEUTRALIZATION =====
    Recipe { id: 900, name: "HCl + NaOH → NaCl", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::HydrochloricAcid, 0.55), (S::SodiumHydroxide, 0.45)],
        outputs: &[(S::SodiumChloride, 0.88)], byproducts: &[(S::Water, 0.12)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.01, cross_recipe_group: None },
    Recipe { id: 901, name: "H2SO4 + CaCO3 → Gypsum", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::SulfuricAcid, 0.50), (S::Limestone, 0.50)],
        outputs: &[(S::ite, 0.80)], byproducts: &[(S::Water, 0.10), (S::CarbonDioxide, 0.10)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.5, cross_recipe_group: None },
    Recipe { id: 902, name: "HCl + NaHCO3 → NaCl + CO2", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::HydrochloricAcid, 0.4), (S::SodaAsh, 0.6)],
        outputs: &[(S::SodiumChloride, 0.6)], byproducts: &[(S::Water, 0.2), (S::CarbonDioxide, 0.2)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.01, cross_recipe_group: None },
    Recipe { id: 903, name: "HNO3 + KOH → KNO3 (Saltpeter)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::NitricAcid, 0.55), (S::SodiumHydroxide, 0.45)],
        outputs: &[(S::PotassiumNitrate, 0.90)], byproducts: &[(S::Water, 0.10)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.01, cross_recipe_group: None },
    Recipe { id: 904, name: "2HCl + Ca(OH)2 → CaCl2", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::HydrochloricAcid, 0.55), (S::SlakedLite, 0.45)],
        outputs: &[(S::CalciumChloride, 0.85)], byproducts: &[(S::Water, 0.15)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.01, cross_recipe_group: None },

    // ===== PRECIPITATION =====
    Recipe { id: 910, name: "BaCl2 + Na2SO4 → BaSO4 (White)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::CalciumChloride, 0.5), (S::SodiumSulfate, 0.5)],
        outputs: &[(S::BariumSulfate, 0.8)], byproducts: &[(S::SodiumChloride, 0.2)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.01, cross_recipe_group: None },
    Recipe { id: 911, name: "AgNO3 + NaCl → AgCl (Photography)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Silver, 0.6), (S::NitricAcid, 0.1), (S::SodiumChloride, 0.3)],
        outputs: &[(S::SilverChloride, 0.9)], byproducts: &[],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.01, cross_recipe_group: None },
    Recipe { id: 912, name: "FeCl3 + NaOH → Fe(OH)3 (Water Treatment)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Iron, 0.3), (S::HydrochloricAcid, 0.3), (S::SodiumHydroxide, 0.4)],
        outputs: &[(S::IronHydroxide, 0.8)], byproducts: &[(S::SodiumChloride, 0.2)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.01, cross_recipe_group: None },
    Recipe { id: 913, name: "Pb(NO3)2 + KI → PbI2 (Golden Rain)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Lead, 0.5), (S::NitricAcid, 0.2), (S::Salt, 0.3)],
        outputs: &[(S::LeadIodide, 0.9)], byproducts: &[(S::PotassiumNitrate, 0.1)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.01, cross_recipe_group: None },

    // ===== REDOX =====
    Recipe { id: 920, name: "Thermite (Fe2O3 + Al)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Hematite, 0.7), (S::Aluminum, 0.3)],
        outputs: &[(S::Iron, 0.5)], byproducts: &[(S::Alumina, 0.5)],
        min_temp_c: 2500, pressure_atm: 1.0, catalyst: None, duration_hours: 0.001, cross_recipe_group: None },
    Recipe { id: 921, name: "H2O2 Decomposition", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::HydrogenPeroxide, 1.0)], outputs: &[(S::Water, 0.53), (S::Oxygen, 0.47)],
        byproducts: &[],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: Some(S::Manganese), duration_hours: 0.01, cross_recipe_group: None },
    Recipe { id: 922, name: "Sodium + Water (Explosive)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Sodium, 0.5), (S::Water, 0.5)], outputs: &[(S::SodiumHydroxide, 0.85)],
        byproducts: &[(S::HydrogenGas, 0.02)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.001, cross_recipe_group: None },
    Recipe { id: 923, name: "Magnesium Burning", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Magnesium, 0.6), (S::Oxygen, 0.4)], outputs: &[(S::MagnesiumOxide, 1.0)],
        byproducts: &[],
        min_temp_c: 473, pressure_atm: 1.0, catalyst: None, duration_hours: 0.001, cross_recipe_group: None },
    Recipe { id: 924, name: "Iron Displacement (Fe + CuSO4)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Iron, 0.5), (S::Copper, 0.5)],
        outputs: &[(S::Copper, 0.55)], byproducts: &[(S::Iron, 0.45)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 2.0, cross_recipe_group: None },
    Recipe { id: 925, name: "Iron Rusting", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Iron, 0.7), (S::Oxygen, 0.2), (S::Water, 0.1)],
        outputs: &[(S::IronHydroxide, 1.0)], byproducts: &[],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 720.0, cross_recipe_group: None },

    // ===== COMPLEXATION =====
    Recipe { id: 930, name: "Prussian Blue Synthesis", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Iron, 0.4), (S::HydrochloricAcid, 0.3), (S::SodiumCyanide, 0.3)],
        outputs: &[(S::PrussianBlue, 1.0)], byproducts: &[(S::SodiumChloride, 0.1)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.1, cross_recipe_group: None },

    // ===== ACID-BASE NEUTRALIZATION (Extended) =====
    Recipe { id: 931, name: "H3PO4 + 3NaOH → Na3PO4 (Trisodium Phosphate)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::PhosphoricAcid, 0.45), (S::SodiumHydroxide, 0.55)],
        outputs: &[(S::SodiumSulfate, 0.88)], byproducts: &[(S::Water, 0.12)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.01, cross_recipe_group: None },
    Recipe { id: 932, name: "2HNO3 + Ca(OH)2 → Ca(NO3)2 (Calcium Nitrate)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::NitricAcid, 0.55), (S::SlakedLite, 0.45)],
        outputs: &[(S::CalciumChloride, 0.88)], byproducts: &[(S::Water, 0.12)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.01, cross_recipe_group: None },
    Recipe { id: 933, name: "H2SO4 + 2KOH → K2SO4 (Potassium Sulfate Fertilizer)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::SulfuricAcid, 0.50), (S::SodiumHydroxide, 0.50)],
        outputs: &[(S::SodiumSulfate, 0.88)], byproducts: &[(S::Water, 0.12)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.01, cross_recipe_group: None },
    Recipe { id: 934, name: "3HCl + Al(OH)3 → AlCl3 (Antacid Reaction)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::HydrochloricAcid, 0.55), (S::Alumina, 0.45)],
        outputs: &[(S::AlumCompound, 0.85)], byproducts: &[(S::Water, 0.15)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.01, cross_recipe_group: None },
    Recipe { id: 935, name: "2HCl + Mg(OH)2 → MgCl2 (Milk of Magnesia)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::HydrochloricAcid, 0.50), (S::MagnesiumHydroxide, 0.50)],
        outputs: &[(S::CalciumChloride, 0.85)], byproducts: &[(S::Water, 0.15)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.01, cross_recipe_group: None },
    Recipe { id: 936, name: "CO2 + 2NaOH → Na2CO3 (CO2 Scrubbing)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::CarbonDioxide, 0.40), (S::SodiumHydroxide, 0.60)],
        outputs: &[(S::SodaAsh, 0.88)], byproducts: &[(S::Water, 0.12)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.5, cross_recipe_group: None },

    // ===== PRECIPITATION (Extended) =====
    Recipe { id: 937, name: "CuSO4 + 2NaOH → Cu(OH)2 (Blue Precipitate)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Copper, 0.3), (S::SulfuricAcid, 0.2), (S::SodiumHydroxide, 0.5)],
        outputs: &[(S::CopperHydroxide, 0.80)], byproducts: &[(S::SodiumSulfate, 0.20)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.01, cross_recipe_group: None },
    Recipe { id: 938, name: "FeSO4 + 2NaOH → Fe(OH)2 (Green Precipitate)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Iron, 0.3), (S::SulfuricAcid, 0.2), (S::SodiumHydroxide, 0.5)],
        outputs: &[(S::IronHydroxide, 0.80)], byproducts: &[(S::SodiumSulfate, 0.20)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.01, cross_recipe_group: None },
    Recipe { id: 939, name: "MgCl2 + 2NaOH → Mg(OH)2 (Dow Process)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::CalciumChloride, 0.4), (S::SodiumHydroxide, 0.6)],
        outputs: &[(S::MagnesiumHydroxide, 0.80)], byproducts: &[(S::SodiumChloride, 0.20)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.01, cross_recipe_group: None },
    Recipe { id: 940, name: "2AgNO3 + Na2CrO4 → Ag2CrO4 (Mohr Titration)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Silver, 0.5), (S::NitricAcid, 0.2), (S::SodiumSulfate, 0.3)],
        outputs: &[(S::SilverChloride, 0.85)], byproducts: &[(S::PotassiumNitrate, 0.15)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.01, cross_recipe_group: None },
    Recipe { id: 941, name: "ZnSO4 + Na2S → ZnS (Phosphorescent Precipitate)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Zinc, 0.4), (S::SulfuricAcid, 0.2), (S::SodiumSulfate, 0.4)],
        outputs: &[(S::Sphalerite, 0.85)], byproducts: &[(S::SodiumSulfate, 0.15)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.01, cross_recipe_group: None },

    // ===== REDOX (Extended) =====
    Recipe { id: 942, name: "KMnO4 + Oxalic Acid (Self-Indicating Titration)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Manganese, 0.4), (S::SulfuricAcid, 0.3), (S::AceticAcid, 0.3)],
        outputs: &[(S::CarbonDioxide, 0.50)], byproducts: &[(S::Water, 0.30), (S::Manganese, 0.20)],
        min_temp_c: 70, pressure_atm: 1.0, catalyst: None, duration_hours: 0.1, cross_recipe_group: None },
    Recipe { id: 943, name: "KMnO4 + FeSO4 (Iron Determination)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Manganese, 0.3), (S::Iron, 0.3), (S::SulfuricAcid, 0.4)],
        outputs: &[(S::IronHydroxide, 0.60)], byproducts: &[(S::Manganese, 0.20), (S::Water, 0.20)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.1, cross_recipe_group: None },
    Recipe { id: 944, name: "K2Cr2O7 + FeSO4 (Breathalyzer Reaction)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Chromium, 0.3), (S::Iron, 0.3), (S::SulfuricAcid, 0.4)],
        outputs: &[(S::IronHydroxide, 0.60)], byproducts: &[(S::ChromeGreen, 0.20), (S::Water, 0.20)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.1, cross_recipe_group: None },
    Recipe { id: 945, name: "Cu + conc HNO3 → Cu(NO3)2 + NO2 (Brown Gas)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Copper, 0.50), (S::NitricAcid, 0.50)],
        outputs: &[(S::CopperHydroxide, 0.60)], byproducts: &[(S::NitrogenDioxide, 0.25), (S::Water, 0.15)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.5, cross_recipe_group: None },
    Recipe { id: 946, name: "Zn + 2HCl → ZnCl2 + H2 (Metal-Acid)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Zinc, 0.50), (S::HydrochloricAcid, 0.50)],
        outputs: &[(S::CalciumChloride, 0.85)], byproducts: &[(S::HydrogenGas, 0.15)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.5, cross_recipe_group: None },
    Recipe { id: 947, name: "Fe Wool + O2 → Fe3O4 (Magnetite)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Iron, 0.70), (S::Oxygen, 0.30)],
        outputs: &[(S::Magnetite, 1.0)], byproducts: &[],
        min_temp_c: 473, pressure_atm: 1.0, catalyst: None, duration_hours: 0.01, cross_recipe_group: None },
    Recipe { id: 948, name: "Cl2 + 2NaOH → NaCl + NaOCl (Bleach)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::ChlorineGas, 0.40), (S::SodiumHydroxide, 0.60)],
        outputs: &[(S::BleachSolution, 0.50), (S::SodiumChloride, 0.40)], byproducts: &[(S::Water, 0.10)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.1, cross_recipe_group: None },

    // ===== COMPLEXATION (Extended) =====
    Recipe { id: 1200, name: "Cu2+ + 4NH3 → [Cu(NH3)4]2+ (Schweizer's Reagent)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Copper, 0.30), (S::Ammonia, 0.70)],
        outputs: &[(S::CopperHydroxide, 0.90)], byproducts: &[(S::Water, 0.10)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.1, cross_recipe_group: None },
    Recipe { id: 1201, name: "Fe3+ + SCN- → [Fe(SCN)]2+ (Blood-Red, Le Chatelier)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Iron, 0.40), (S::SodiumCyanide, 0.60)],
        outputs: &[(S::IronHydroxide, 0.90)], byproducts: &[(S::SodiumChloride, 0.10)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.01, cross_recipe_group: None },
    Recipe { id: 1202, name: "Ag+ + 2NH3 → [Ag(NH3)2]+ (Tollens Reagent)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Silver, 0.40), (S::Ammonia, 0.60)],
        outputs: &[(S::SilverChloride, 0.90)], byproducts: &[(S::Water, 0.10)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.01, cross_recipe_group: None },
    Recipe { id: 1203, name: "EDTA + Ca2+ Chelation (Water Hardness Titration)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::AceticAcid, 0.50), (S::Calcium, 0.50)],
        outputs: &[(S::CalciumChloride, 0.90)], byproducts: &[(S::Water, 0.10)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.1, cross_recipe_group: None },
    Recipe { id: 1204, name: "Ni2+ + Dimethylglyoxime → Scarlet Precipitate (Ni Test)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Nickel, 0.40), (S::Ammonia, 0.30), (S::Ethanol, 0.30)],
        outputs: &[(S::IronOxideRed, 0.90)], byproducts: &[(S::Water, 0.10)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.1, cross_recipe_group: None },
    Recipe { id: 1205, name: "CoCl2 Hydration/Dehydration (Humidity Indicator)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Cobalt, 0.40), (S::HydrochloricAcid, 0.30), (S::Water, 0.30)],
        outputs: &[(S::CobaltBluePigment, 0.90)], byproducts: &[(S::Water, 0.10)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.5, cross_recipe_group: None },

    // ===== COORDINATION / INORGANIC CHEMISTRY =====
    Recipe { id: 2550, name: "Ligand Exchange (Aqua→Chloro Complex)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Cobalt, 0.4), (S::HydrochloricAcid, 0.4), (S::Water, 0.2)],
        outputs: &[(S::CobaltBluePigment, 0.9)], // CoCl4 placeholder
        byproducts: &[(S::Water, 0.1)],
        min_temp_c: 60, pressure_atm: 1.0, catalyst: None, duration_hours: 0.5, cross_recipe_group: None },
    Recipe { id: 2551, name: "Trans Effect in Pt Complexes (Cisplatin Synthesis)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Platinum, 0.6), (S::ChlorineGas, 0.2), (S::Ammonia, 0.2)],
        outputs: &[(S::Platinum, 0.95)], // cis-[PtCl2(NH3)2] placeholder
        byproducts: &[(S::HydrochloricAcid, 0.05)],
        min_temp_c: 60, pressure_atm: 1.0, catalyst: None, duration_hours: 12.0, cross_recipe_group: None },
    Recipe { id: 2552, name: "Crystal Field Splitting (Octahedral Complex)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Chromium, 0.4), (S::Ammonia, 0.6)],
        outputs: &[(S::ChromeGreen, 0.9)], // [Cr(NH3)6]3+ placeholder
        byproducts: &[(S::Water, 0.1)],
        min_temp_c: 60, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: None },
    Recipe { id: 2553, name: "Jahn-Teller Distortion (Cu2+ Complex)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Copper, 0.4), (S::Ammonia, 0.4), (S::Water, 0.2)],
        outputs: &[(S::CopperHydroxide, 0.9)], // [Cu(NH3)4(H2O)2]2+ placeholder
        byproducts: &[(S::Water, 0.1)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.5, cross_recipe_group: None },
    Recipe { id: 2554, name: "Fenton Reaction (Fe2++H2O2→OH Radical)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Iron, 0.3), (S::HydrogenPeroxide, 0.5), (S::Water, 0.2)],
        outputs: &[(S::HydroxylRadical, 0.5)],
        byproducts: &[(S::IronHydroxide, 0.3), (S::Water, 0.2)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.1, cross_recipe_group: None },
    Recipe { id: 2555, name: "Photo-Fenton Reaction (Fe3++H2O2+UV)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Iron, 0.2), (S::HydrogenPeroxide, 0.5), (S::Water, 0.3)],
        outputs: &[(S::HydroxylRadical, 0.6)],
        byproducts: &[(S::IronHydroxide, 0.2), (S::Oxygen, 0.2)],
        min_temp_c: 25, pressure_atm: 1.0, catalyst: None, duration_hours: 2.0, cross_recipe_group: None },
    Recipe { id: 2556, name: "KMnO4 Cold Dilute (Alkene→Diol)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Manganese, 0.3), (S::Ethylene, 0.4), (S::Water, 0.3)],
        outputs: &[(S::Diol, 0.7)],
        byproducts: &[(S::ManganeseNodule, 0.2), (S::SodiumHydroxide, 0.1)],
        min_temp_c: 0, pressure_atm: 1.0, catalyst: None, duration_hours: 1.0, cross_recipe_group: None },
    Recipe { id: 2557, name: "KMnO4 Hot Acidic (Alkene Cleavage)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Manganese, 0.3), (S::Ethylene, 0.3), (S::SulfuricAcid, 0.4)],
        outputs: &[(S::AceticAcid, 0.5)],
        byproducts: &[(S::Manganese, 0.2), (S::CarbonDioxide, 0.2), (S::Water, 0.1)],
        min_temp_c: 80, pressure_atm: 1.0, catalyst: None, duration_hours: 2.0, cross_recipe_group: None },
    Recipe { id: 2558, name: "Chromate-Dichromate Equilibrium (pH Dependent)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Chromium, 0.5), (S::SodiumHydroxide, 0.3), (S::SulfuricAcid, 0.2)],
        outputs: &[(S::ChromeYellow, 0.8)], // chromate/dichromate placeholder
        byproducts: &[(S::Water, 0.2)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.01, cross_recipe_group: None },
    Recipe { id: 2559, name: "Aluminum Anodization (Oxide Layer Growth)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Aluminum, 0.9), (S::SulfuricAcid, 0.1)],
        outputs: &[(S::Alumina, 0.95)], // anodized layer
        byproducts: &[(S::HydrogenGas, 0.05)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 1.0, cross_recipe_group: None },
    Recipe { id: 2560, name: "Copper Patina Formation (Cu→Cu2(OH)2CO3)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Copper, 0.7), (S::CarbonDioxide, 0.1), (S::Water, 0.2)],
        outputs: &[(S::Patina, 1.0)],
        byproducts: &[],
        min_temp_c: 15, pressure_atm: 1.0, catalyst: None, duration_hours: 87600.0, cross_recipe_group: None },
    Recipe { id: 2561, name: "Silver Tarnish (Ag→Ag2S)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Silver, 0.87), (S::Sulfur, 0.13)],
        outputs: &[(S::SilverSulfide, 1.0)],
        byproducts: &[],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 8760.0, cross_recipe_group: None },
    Recipe { id: 2562, name: "Iron Passivation (Conc HNO3)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Iron, 0.8), (S::NitricAcid, 0.2)],
        outputs: &[(S::Hematite, 0.9)], // Fe2O3 passive layer
        byproducts: &[(S::NitrogenDioxide, 0.1)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.5, cross_recipe_group: None },
    Recipe { id: 2563, name: "Tin Pest (White→Grey Tin below 13C)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Tin, 1.0)],
        outputs: &[(S::Tin, 0.95)], // grey tin placeholder
        byproducts: &[],
        min_temp_c: -40, pressure_atm: 1.0, catalyst: None, duration_hours: 8760.0, cross_recipe_group: None },
    Recipe { id: 2564, name: "Cement Hydration (C3S+Water→CSH Gel)", category: RecipeCategory::Construction,
        inputs: &[(S::PortlandCite, 0.7), (S::Water, 0.3)],
        outputs: &[(S::CementGel, 1.0)],
        byproducts: &[(S::SlakedLite, 0.1)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 672.0, cross_recipe_group: None },
    Recipe { id: 2565, name: "Concrete Carbonation (Ca(OH)2+CO2→CaCO3)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::SlakedLite, 0.7), (S::CarbonDioxide, 0.3)],
        outputs: &[(S::Limestone, 0.9)],
        byproducts: &[(S::Water, 0.1)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 87600.0, cross_recipe_group: None },
    Recipe { id: 2566, name: "Zeolite Synthesis (Hydrothermal)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::SilicaSand, 0.4), (S::Alumina, 0.3), (S::SodiumHydroxide, 0.3)],
        outputs: &[(S::Zeolite, 1.0)],
        byproducts: &[(S::Water, 0.2)],
        min_temp_c: 150, pressure_atm: 5.0, catalyst: None, duration_hours: 48.0, cross_recipe_group: None },
    Recipe { id: 2567, name: "Silica Gel Synthesis (Na2SiO3+HCl)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::SilicaSand, 0.5), (S::SodiumHydroxide, 0.3), (S::HydrochloricAcid, 0.2)],
        outputs: &[(S::SilicaGel, 0.8)],
        byproducts: &[(S::SodiumChloride, 0.2)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 12.0, cross_recipe_group: None },
    Recipe { id: 2568, name: "Calcium Phosphate Synthesis (Bone Mineral)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Calcium, 0.4), (S::PhosphoricAcid, 0.5), (S::SodiumHydroxide, 0.1)],
        outputs: &[(S::Hydroxyapatite, 0.9)],
        byproducts: &[(S::Water, 0.1)],
        min_temp_c: 80, pressure_atm: 1.0, catalyst: None, duration_hours: 24.0, cross_recipe_group: None },
    Recipe { id: 2569, name: "Sodium Silicate (Water Glass, SiO2+NaOH)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::SilicaSand, 0.6), (S::SodiumHydroxide, 0.4)],
        outputs: &[(S::WaterGlass, 1.0)],
        byproducts: &[(S::Water, 0.1)],
        min_temp_c: 1100, pressure_atm: 1.0, catalyst: None, duration_hours: 2.0, cross_recipe_group: None },
    Recipe { id: 2570, name: "Potash from Wood Ash Leaching", category: RecipeCategory::Extraction,
        inputs: &[(S::Charcoal, 1.0), (S::Water, 5.0)],
        outputs: &[(S::Potash, 0.3)],
        byproducts: &[(S::Water, 4.5)],
        min_temp_c: 80, pressure_atm: 1.0, catalyst: None, duration_hours: 6.0, cross_recipe_group: None },
    Recipe { id: 2571, name: "Borax from Borate Ores", category: RecipeCategory::Extraction,
        inputs: &[(S::Sand, 2.0), (S::Water, 5.0)], // borate ore placeholder
        outputs: &[(S::Borax, 0.5)],
        byproducts: &[(S::Clay, 1.0), (S::Water, 4.0)],
        min_temp_c: 80, pressure_atm: 1.0, catalyst: None, duration_hours: 8.0, cross_recipe_group: None },
    Recipe { id: 2572, name: "Alum from Bauxite", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Bauxite, 1.0), (S::SulfuricAcid, 0.8), (S::Water, 2.0)],
        outputs: &[(S::AlumCompound, 0.8)],
        byproducts: &[(S::IronHydroxide, 0.3), (S::Water, 1.5)],
        min_temp_c: 80, pressure_atm: 1.0, catalyst: None, duration_hours: 6.0, cross_recipe_group: None },
    Recipe { id: 2573, name: "Sodium Bicarbonate from Solvay Byproduct", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::SodaAsh, 0.5), (S::CarbonDioxide, 0.3), (S::Water, 0.2)],
        outputs: &[(S::SodaAsh, 0.8)], // NaHCO3 as SodaAsh placeholder
        byproducts: &[],
        min_temp_c: 20, pressure_atm: 3.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: None },
    Recipe { id: 2574, name: "Calcium Hypochlorite (Bleaching Powder)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::SlakedLite, 0.5), (S::ChlorineGas, 0.5)],
        outputs: &[(S::CalciumHypochlorite, 1.0)],
        byproducts: &[],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 1.0, cross_recipe_group: None },
    Recipe { id: 2575, name: "Copper Sulfate (Blue Vitriol) Crystallization", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Copper, 0.4), (S::SulfuricAcid, 0.4), (S::Oxygen, 0.2)],
        outputs: &[(S::CopperSulfate, 1.0)],
        byproducts: &[(S::Water, 0.1)],
        min_temp_c: 60, pressure_atm: 1.0, catalyst: None, duration_hours: 8.0, cross_recipe_group: None },
    Recipe { id: 2576, name: "Iron Sulfate (Green Vitriol/Copperas)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Iron, 0.4), (S::SulfuricAcid, 0.5), (S::Water, 0.1)],
        outputs: &[(S::IronSulfate, 1.0)],
        byproducts: &[(S::HydrogenGas, 0.05)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: None },
    Recipe { id: 2577, name: "Zinc Sulfate from Zinc+H2SO4", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Zinc, 0.4), (S::SulfuricAcid, 0.5), (S::Water, 0.1)],
        outputs: &[(S::ZincSulfate, 1.0)],
        byproducts: &[(S::HydrogenGas, 0.05)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 2.0, cross_recipe_group: None },
    Recipe { id: 2578, name: "Chrome Alum (from K2Cr2O7 Reduction)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Chromium, 0.3), (S::SulfuricAcid, 0.5), (S::Ethanol, 0.2)],
        outputs: &[(S::ChromeAlum, 0.9)],
        byproducts: &[(S::Water, 0.1)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 24.0, cross_recipe_group: None },
    Recipe { id: 2579, name: "Ammonium Dichromate Volcano Reaction", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Chromium, 0.5), (S::AmmoniumNitrate, 0.5)],
        outputs: &[(S::ChromeGreen, 0.6)],
        byproducts: &[(S::Nitrogen, 0.1), (S::Water, 0.2), (S::Steam, 0.1)],
        min_temp_c: 200, pressure_atm: 1.0, catalyst: None, duration_hours: 0.01, cross_recipe_group: None },
    Recipe { id: 2580, name: "Sodium Thiosulfate (Na2SO3+S)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::SodaAsh, 0.5), (S::Sulfur, 0.3), (S::SulfuricAcid, 0.2)],
        outputs: &[(S::SodiumThiosulfate, 0.9)],
        byproducts: &[(S::Water, 0.1)],
        min_temp_c: 80, pressure_atm: 1.0, catalyst: None, duration_hours: 2.0, cross_recipe_group: None },
    Recipe { id: 2581, name: "Potassium Permanganate (MnO2+KOH+O2)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Manganese, 0.5), (S::SodiumHydroxide, 0.3), (S::Oxygen, 0.2)],
        outputs: &[(S::Manganese, 0.9)], // KMnO4 placeholder
        byproducts: &[(S::Water, 0.1)],
        min_temp_c: 300, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: None },
    Recipe { id: 2582, name: "Hydrogen Sulfide from FeS+HCl", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::PyriteOre, 0.5), (S::HydrochloricAcid, 0.5)],
        outputs: &[(S::Sulfur, 0.4)], // H2S placeholder
        byproducts: &[(S::Iron, 0.3), (S::CalciumChloride, 0.3)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.5, cross_recipe_group: None },
    Recipe { id: 2583, name: "Silicon Tetrafluoride (SiO2+HF)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::SilicaSand, 0.5), (S::HydrochloricAcid, 0.5)], // HF placeholder
        outputs: &[(S::SiliconTetrafluoride, 0.8)],
        byproducts: &[(S::Water, 0.2)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 1.0, cross_recipe_group: None },
    Recipe { id: 2584, name: "Phosphine from Ca3P2+H2O", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::PhosphateRock, 0.6), (S::Water, 0.4)],
        outputs: &[(S::Phosphine, 0.5)],
        byproducts: &[(S::SlakedLite, 0.5)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.5, cross_recipe_group: None },
    Recipe { id: 2585, name: "Arsine from Arsenide+Acid", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Zinc, 0.5), (S::HydrochloricAcid, 0.5)], // arsenide placeholder
        outputs: &[(S::Arsine, 0.4)],
        byproducts: &[(S::CalciumChloride, 0.4), (S::HydrogenGas, 0.2)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.5, cross_recipe_group: None },
    Recipe { id: 2586, name: "Diborane from NaBH4+BF3", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Sodium, 0.3), (S::Borax, 0.5), (S::DiethylEther, 0.2)],
        outputs: &[(S::Diborane, 0.7)],
        byproducts: &[(S::SodiumChloride, 0.3)],
        min_temp_c: 0, pressure_atm: 1.0, catalyst: None, duration_hours: 2.0, cross_recipe_group: None },
    Recipe { id: 2587, name: "Titanium Isopropoxide (for Sol-Gel)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::TitaniumTetrachloride, 0.5), (S::Isopropanol, 0.5)],
        outputs: &[(S::TitaniumIsopropoxide, 0.8)],
        byproducts: &[(S::HydrochloricAcid, 0.2)],
        min_temp_c: 80, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: None },
    Recipe { id: 2588, name: "Aluminum Isopropoxide (for Meerwein-Ponndorf)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Aluminum, 0.3), (S::Isopropanol, 0.6), (S::Mercury, 0.1)],
        outputs: &[(S::AluminumIsopropoxide, 0.8)],
        byproducts: &[(S::HydrogenGas, 0.1), (S::Mercury, 0.1)],
        min_temp_c: 80, pressure_atm: 1.0, catalyst: None, duration_hours: 8.0, cross_recipe_group: None },
    Recipe { id: 2589, name: "Ferrocene Synthesis (FeCl2+2Cp)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Iron, 0.3), (S::HydrochloricAcid, 0.2), (S::Sodium, 0.2), (S::CrudeOil, 0.3)],
        outputs: &[(S::Ferrocene, 0.8)],
        byproducts: &[(S::SodiumChloride, 0.2)],
        min_temp_c: 25, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: None },
];
