#![allow(dead_code)]
use super::types::*;
use super::substance::Substance as S;

pub static NATURAL_RECIPES: &[Recipe] = &[
    // ===== WEATHERING =====
    Recipe { id: 1000, name: "Feldspar Weathering → Kaolinite", category: RecipeCategory::PhaseChange,
        inputs: &[(S::FeldsparOre, 1.0), (S::Water, 0.5), (S::CarbonDioxide, 0.1)],
        outputs: &[(S::Clay, 0.6)], byproducts: &[(S::Sand, 0.3)],
        min_temp_c: 15, pressure_atm: 1.0, catalyst: None, duration_hours: 87600000.0, cross_recipe_group: None },
    Recipe { id: 1001, name: "Olivine Weathering (CO2 Capture)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Sand, 1.0), (S::CarbonDioxide, 0.5), (S::Water, 0.5)], // olivine as Sand placeholder
        outputs: &[(S::Magnesium, 0.3)], byproducts: &[(S::Sand, 0.5)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 87600000.0, cross_recipe_group: None },
    Recipe { id: 1002, name: "Calcite Dissolution (Cave Formation)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Limestone, 1.0), (S::CarbonDioxide, 0.1), (S::Water, 1.0)],
        outputs: &[(S::CalciumChloride, 0.8)], byproducts: &[(S::Water, 0.5)],
        min_temp_c: 10, pressure_atm: 1.0, catalyst: None, duration_hours: 876000.0, cross_recipe_group: None },
    Recipe { id: 1003, name: "Pyrite Oxidation (Acid Mine Drainage)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::PyriteOre, 1.0), (S::Oxygen, 0.5), (S::Water, 0.5)],
        outputs: &[(S::IronHydroxide, 0.5), (S::SulfuricAcid, 0.4)], byproducts: &[],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 8760.0, cross_recipe_group: None },

    // ===== METAMORPHIC =====
    Recipe { id: 1010, name: "Limestone → Marble", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Limestone, 1.0)], outputs: &[(S::Marble, 1.0)], byproducts: &[],
        min_temp_c: 400, pressure_atm: 2000.0, catalyst: None, duration_hours: 87600000.0, cross_recipe_group: None },
    Recipe { id: 1011, name: "Shale → Slate", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Clay, 1.0)], outputs: &[(S::Slate, 1.0)], byproducts: &[(S::Water, 0.05)],
        min_temp_c: 250, pressure_atm: 1500.0, catalyst: None, duration_hours: 87600000.0, cross_recipe_group: None },
    Recipe { id: 1012, name: "Sandstone → Quartzite", category: RecipeCategory::PhaseChange,
        inputs: &[(S::SilicaSand, 1.0)], outputs: &[(S::Quartzite, 1.0)], byproducts: &[],
        min_temp_c: 400, pressure_atm: 3000.0, catalyst: None, duration_hours: 87600000.0, cross_recipe_group: None },
    Recipe { id: 1013, name: "Serpentinization (Olivine + Water)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Sand, 1.0), (S::Water, 0.5)], // olivine placeholder
        outputs: &[(S::SerpentineMinite, 0.8), (S::HydrogenGas, 0.02)],
        byproducts: &[(S::Magnetite, 0.1)],
        min_temp_c: 300, pressure_atm: 500.0, catalyst: None, duration_hours: 876000.0, cross_recipe_group: None },

    // ===== HYDROTHERMAL =====
    Recipe { id: 1020, name: "Black Smoker Pyrite", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Iron, 0.5), (S::Sulfur, 0.5), (S::Water, 5.0)],
        outputs: &[(S::PyriteOre, 1.0)], byproducts: &[],
        min_temp_c: 350, pressure_atm: 300.0, catalyst: None, duration_hours: 8760.0, cross_recipe_group: None },
    Recipe { id: 1021, name: "Hydrothermal Gold Deposition", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Water, 1000.0), (S::Sulfur, 0.01)],
        outputs: &[(S::Gold, 0.001)], byproducts: &[(S::SilicaSand, 0.5)],
        min_temp_c: 300, pressure_atm: 200.0, catalyst: None, duration_hours: 876000.0, cross_recipe_group: None },
    Recipe { id: 1022, name: "Silica Sinter (Hot Spring)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Water, 100.0), (S::SilicaSand, 0.4)], // dissolved silica
        outputs: &[(S::SilicaSand, 1.0)], byproducts: &[(S::Water, 99.0)],
        min_temp_c: 90, pressure_atm: 1.0, catalyst: None, duration_hours: 87600.0, cross_recipe_group: None },

    // ===== DIAGENESIS =====
    Recipe { id: 1025, name: "Kerogen → Crude Oil (Catagenesis)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Cellulose, 10.0)], // kerogen placeholder
        outputs: &[(S::CrudeOil, 1.0)], byproducts: &[(S::NaturalGas, 0.3), (S::Carbon, 0.5)],
        min_temp_c: 100, pressure_atm: 500.0, catalyst: None, duration_hours: 876000000.0, cross_recipe_group: None },

    // ===== ATMOSPHERIC =====
    Recipe { id: 1030, name: "Ozone Formation (UV)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Oxygen, 1.0)], outputs: &[(S::Ozone, 0.67)], byproducts: &[],
        min_temp_c: -60, pressure_atm: 0.001, catalyst: None, duration_hours: 0.001, cross_recipe_group: None },
    Recipe { id: 1031, name: "Acid Rain (SO2 → H2SO4)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::SulfurDioxide, 0.6), (S::Water, 0.3), (S::Oxygen, 0.1)],
        outputs: &[(S::SulfuricAcid, 1.0)], byproducts: &[],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 168.0, cross_recipe_group: None },
    Recipe { id: 1032, name: "Ocean CO2 Dissolution", category: RecipeCategory::PhaseChange,
        inputs: &[(S::CarbonDioxide, 0.1), (S::Water, 10.0)],
        outputs: &[(S::Water, 10.0)], byproducts: &[], // acidified water
        min_temp_c: 10, pressure_atm: 1.0, catalyst: None, duration_hours: 8760.0, cross_recipe_group: None },

    // ===== BIOCHEMISTRY =====
    Recipe { id: 1040, name: "Oxygenic Photosynthesis", category: RecipeCategory::FoodBiological,
        inputs: &[(S::CarbonDioxide, 0.44), (S::Water, 0.36)],
        outputs: &[(S::Glucose, 0.48), (S::Oxygen, 0.32)], byproducts: &[],
        min_temp_c: 25, pressure_atm: 1.0, catalyst: None, duration_hours: 12.0, cross_recipe_group: None },
    Recipe { id: 1041, name: "Aerobic Respiration", category: RecipeCategory::FoodBiological,
        inputs: &[(S::Glucose, 0.48), (S::Oxygen, 0.32)],
        outputs: &[(S::CarbonDioxide, 0.44), (S::Water, 0.36)], byproducts: &[],
        min_temp_c: 37, pressure_atm: 1.0, catalyst: None, duration_hours: 0.01, cross_recipe_group: None },
    Recipe { id: 1042, name: "Lactic Acid Fermentation", category: RecipeCategory::FoodBiological,
        inputs: &[(S::Glucose, 1.0)], outputs: &[(S::LacticAcid, 1.0)], byproducts: &[],
        min_temp_c: 37, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: None },
    Recipe { id: 1043, name: "Nitrogen Fixation (Biological)", category: RecipeCategory::FoodBiological,
        inputs: &[(S::Nitrogen, 0.82), (S::HydrogenGas, 0.18)],
        outputs: &[(S::Ammonium, 1.0)], byproducts: &[],
        min_temp_c: 25, pressure_atm: 1.0, catalyst: None, duration_hours: 720.0, cross_recipe_group: None },
    Recipe { id: 1044, name: "Methanogenesis (CO2 Reduction)", category: RecipeCategory::FoodBiological,
        inputs: &[(S::CarbonDioxide, 0.6), (S::HydrogenGas, 0.4)],
        outputs: &[(S::Methane, 0.6)], byproducts: &[(S::Water, 0.4)],
        min_temp_c: 35, pressure_atm: 1.0, catalyst: None, duration_hours: 720.0, cross_recipe_group: None },

    // ===== PIGMENTS =====
    Recipe { id: 1050, name: "Yellow Ochre → Red Ochre (Calcination)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::YellowOchre, 1.0)], outputs: &[(S::RedOchre, 0.9)], byproducts: &[(S::Water, 0.1)],
        min_temp_c: 300, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: None },
    Recipe { id: 1051, name: "Raw Umber → Burnt Umber", category: RecipeCategory::PhaseChange,
        inputs: &[(S::RawUmber, 1.0)], outputs: &[(S::BurntUmber, 0.95)], byproducts: &[(S::Water, 0.05)],
        min_temp_c: 400, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: None },
    Recipe { id: 1052, name: "Raw Sienna → Burnt Sienna", category: RecipeCategory::PhaseChange,
        inputs: &[(S::RawSienna, 1.0)], outputs: &[(S::BurntSienna, 0.95)], byproducts: &[(S::Water, 0.05)],
        min_temp_c: 400, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: None },
    Recipe { id: 1053, name: "Carbon Black (Lamp Soot)", category: RecipeCategory::FuelProcessing,
        inputs: &[(S::CrudeOil, 1.5)], outputs: &[(S::CarbonBlack, 1.0)], byproducts: &[(S::CarbonDioxide, 0.3)],
        min_temp_c: 300, pressure_atm: 1.0, catalyst: None, duration_hours: 2.0, cross_recipe_group: None },
    Recipe { id: 1054, name: "Bone Black (Calcined Bones)", category: RecipeCategory::PhaseChange,
        inputs: &[(S::Calcium, 1.0)], // bones placeholder
        outputs: &[(S::BoneBlack, 0.8)], byproducts: &[(S::CarbonDioxide, 0.2)],
        min_temp_c: 450, pressure_atm: 1.0, catalyst: None, duration_hours: 6.0, cross_recipe_group: None },
    Recipe { id: 1055, name: "Chrome Yellow (PbCrO4)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Lead, 0.6), (S::Chromium, 0.2), (S::NitricAcid, 0.2)],
        outputs: &[(S::ChromeYellow, 1.0)], byproducts: &[(S::PotassiumNitrate, 0.1)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.5, cross_recipe_group: None },
    Recipe { id: 1056, name: "Chrome Green (Cr2O3)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Chromium, 0.5), (S::Sulfur, 0.3), (S::SodiumHydroxide, 0.2)],
        outputs: &[(S::ChromeGreen, 1.0)], byproducts: &[(S::SodiumSulfate, 0.2)],
        min_temp_c: 500, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: None },
    Recipe { id: 1057, name: "Cadmium Yellow (CdS)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Zinc, 0.5), (S::Sulfur, 0.5)], // Cd placeholder as Zinc
        outputs: &[(S::CadmiumYellow, 1.0)], byproducts: &[],
        min_temp_c: 300, pressure_atm: 1.0, catalyst: None, duration_hours: 2.0, cross_recipe_group: None },
    Recipe { id: 1058, name: "Cobalt Blue (CoAl2O4)", category: RecipeCategory::Construction,
        inputs: &[(S::Cobalt, 0.3), (S::Alumina, 0.7)],
        outputs: &[(S::CobaltBluePigment, 1.0)], byproducts: &[],
        min_temp_c: 1200, pressure_atm: 1.0, catalyst: None, duration_hours: 8.0, cross_recipe_group: None },
    Recipe { id: 1059, name: "Synthetic Ultramarine", category: RecipeCategory::Construction,
        inputs: &[(S::Clay, 0.4), (S::SodaAsh, 0.2), (S::Sulfur, 0.2), (S::Charcoal, 0.1)],
        outputs: &[(S::SyntheticUltramarine, 1.0)], byproducts: &[],
        min_temp_c: 780, pressure_atm: 1.0, catalyst: None, duration_hours: 48.0, cross_recipe_group: None },
    Recipe { id: 1060, name: "Titanium White (Chloride Process)", category: RecipeCategory::Extraction,
        inputs: &[(S::Ilmenite, 1.5), (S::ChlorineGas, 1.0), (S::Carbon, 0.3)],
        outputs: &[(S::TitaniumWhite, 1.0)], byproducts: &[(S::Iron, 0.3), (S::ChlorineGas, 0.8)],
        min_temp_c: 1500, pressure_atm: 1.0, catalyst: None, duration_hours: 2.0, cross_recipe_group: None },
    Recipe { id: 1061, name: "Egyptian Blue (CaCuSi2O6)", category: RecipeCategory::Construction,
        inputs: &[(S::SilicaSand, 0.4), (S::Limestone, 0.2), (S::Copper, 0.2), (S::SodaAsh, 0.1)],
        outputs: &[(S::EgyptianBlue, 1.0)], byproducts: &[(S::CarbonDioxide, 0.1)],
        min_temp_c: 950, pressure_atm: 1.0, catalyst: None, duration_hours: 24.0, cross_recipe_group: None },
    Recipe { id: 1062, name: "Vermilion (HgS Sublimation)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Mercury, 0.85), (S::Sulfur, 0.15)],
        outputs: &[(S::Vermilion, 1.0)], byproducts: &[],
        min_temp_c: 580, pressure_atm: 1.0, catalyst: None, duration_hours: 8.0, cross_recipe_group: None },
    Recipe { id: 1063, name: "Lead White (Dutch Process)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Lead, 0.8), (S::AceticAcid, 0.1), (S::CarbonDioxide, 0.1)],
        outputs: &[(S::LeadWhite, 1.0)], byproducts: &[],
        min_temp_c: 25, pressure_atm: 1.0, catalyst: None, duration_hours: 1440.0, cross_recipe_group: None },
    Recipe { id: 1064, name: "Verdigris (Cu + Acetic Acid)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Copper, 0.7), (S::AceticAcid, 0.3)],
        outputs: &[(S::Verdigris, 1.0)], byproducts: &[],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 720.0, cross_recipe_group: None },
    Recipe { id: 1065, name: "Zinc White (ZnO)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Zinc, 0.8), (S::Oxygen, 0.2)],
        outputs: &[(S::ZincWhite, 1.0)], byproducts: &[],
        min_temp_c: 907, pressure_atm: 1.0, catalyst: None, duration_hours: 0.5, cross_recipe_group: None },

    // ===== WATER TREATMENT =====
    Recipe { id: 1070, name: "Lime Softening", category: RecipeCategory::Refining,
        inputs: &[(S::Water, 100.0), (S::SlakedLite, 0.5)],
        outputs: &[(S::Water, 99.0)], byproducts: &[(S::Limestone, 0.5)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: None },
    Recipe { id: 1071, name: "Reverse Osmosis Desalination", category: RecipeCategory::Refining,
        inputs: &[(S::Water, 3.0)], // seawater
        outputs: &[(S::Water, 1.0)], byproducts: &[(S::Salt, 0.07)],
        min_temp_c: 25, pressure_atm: 70.0, catalyst: None, duration_hours: 0.1, cross_recipe_group: None },
    Recipe { id: 1072, name: "Water Chlorination", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Water, 1000.0), (S::ChlorineGas, 0.002)],
        outputs: &[(S::Water, 1000.0)], byproducts: &[],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.5, cross_recipe_group: None },
    Recipe { id: 1073, name: "Alum Flocculation", category: RecipeCategory::Refining,
        inputs: &[(S::Water, 100.0), (S::AlumCompound, 0.05)],
        outputs: &[(S::Water, 99.0)], byproducts: &[(S::IronHydroxide, 0.5)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: None },
];
