#![allow(dead_code)]
use super::types::*;
use super::substance::Substance as S;

pub static ORGANIC_RECIPES: &[Recipe] = &[
    // ===== HYDROCARBONS =====
    Recipe { id: 800, name: "Steam Cracking (Ethylene)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::CrudeOil, 1.5)], outputs: &[(S::Ethylene, 0.3), (S::Propylene, 0.15)],
        byproducts: &[(S::Butadiene, 0.05), (S::Benzene, 0.05), (S::HydrogenGas, 0.02)],
        min_temp_c: 850, pressure_atm: 2.0, catalyst: None, duration_hours: 0.01, cross_recipe_group: None },
    Recipe { id: 801, name: "Catalytic Reforming (BTX)", category: RecipeCategory::Refining,
        inputs: &[(S::CrudeOil, 1.5)], outputs: &[(S::Benzene, 0.3), (S::Toluene, 0.25), (S::Xylene, 0.2)],
        byproducts: &[(S::HydrogenGas, 0.05)],
        min_temp_c: 500, pressure_atm: 25.0, catalyst: Some(S::Platinum), duration_hours: 0.5, cross_recipe_group: None },
    Recipe { id: 802, name: "Acetylene from Carbide", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::CalciumCarbide, 1.0), (S::Water, 0.6)], outputs: &[(S::Acetylene, 0.4)],
        byproducts: &[(S::SlakedLite, 1.2)],
        min_temp_c: 20, pressure_atm: 1.0, catalyst: None, duration_hours: 0.1, cross_recipe_group: None },

    // ===== ALCOHOLS =====
    Recipe { id: 810, name: "Methanol from Syngas", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::SynGas, 1.5)], outputs: &[(S::Methanol, 1.0)], byproducts: &[(S::Water, 0.3)],
        min_temp_c: 250, pressure_atm: 80.0, catalyst: Some(S::Copper), duration_hours: 2.0, cross_recipe_group: None },
    Recipe { id: 811, name: "Ethanol from Ethylene Hydration", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Ethylene, 0.6), (S::Water, 0.4)], outputs: &[(S::Ethanol, 1.0)], byproducts: &[],
        min_temp_c: 300, pressure_atm: 70.0, catalyst: Some(S::PhosphoricAcid), duration_hours: 1.0, cross_recipe_group: None },
    Recipe { id: 812, name: "Isopropanol from Propylene", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Propylene, 0.7), (S::Water, 0.3)], outputs: &[(S::Isopropanol, 1.0)], byproducts: &[],
        min_temp_c: 250, pressure_atm: 25.0, catalyst: Some(S::SulfuricAcid), duration_hours: 1.0, cross_recipe_group: None },
    Recipe { id: 813, name: "Butanol ABE Fermentation", category: RecipeCategory::FoodBiological,
        inputs: &[(S::Glucose, 2.0), (S::Water, 5.0)], outputs: &[(S::Butanol, 0.6), (S::Acetone, 0.3), (S::Ethanol, 0.1)],
        byproducts: &[(S::CarbonDioxide, 1.0)],
        min_temp_c: 35, pressure_atm: 1.0, catalyst: None, duration_hours: 72.0, cross_recipe_group: None },
    Recipe { id: 814, name: "Ethylene Glycol from Ethylene Oxide", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::EthyleneOxide, 0.7), (S::Water, 0.3)], outputs: &[(S::EthyleneGlycol, 1.0)], byproducts: &[],
        min_temp_c: 200, pressure_atm: 15.0, catalyst: None, duration_hours: 0.5, cross_recipe_group: None },

    // ===== ALDEHYDES AND KETONES =====
    Recipe { id: 820, name: "Formaldehyde (Methanol Oxidation)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Methanol, 0.9), (S::Oxygen, 0.1)], outputs: &[(S::Formaldehyde, 1.0)],
        byproducts: &[(S::Water, 0.2)],
        min_temp_c: 600, pressure_atm: 1.0, catalyst: Some(S::Silver), duration_hours: 0.1, cross_recipe_group: None },
    Recipe { id: 821, name: "Acetaldehyde (Wacker Process)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Ethylene, 0.6), (S::Oxygen, 0.4)], outputs: &[(S::Acetaldehyde, 1.0)],
        byproducts: &[(S::Water, 0.2)],
        min_temp_c: 130, pressure_atm: 4.0, catalyst: Some(S::Copper), duration_hours: 1.0, cross_recipe_group: None },
    Recipe { id: 822, name: "Acetone (Cumene Process)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Benzene, 0.5), (S::Propylene, 0.5)], outputs: &[(S::Acetone, 0.4), (S::Phenol, 0.6)],
        byproducts: &[],
        min_temp_c: 90, pressure_atm: 1.0, catalyst: Some(S::SulfuricAcid), duration_hours: 3.0, cross_recipe_group: None },

    // ===== CARBOXYLIC ACIDS =====
    Recipe { id: 830, name: "Acetic Acid (Monsanto Process)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Methanol, 0.5), (S::SynGas, 0.5)], outputs: &[(S::AceticAcid, 1.0)], byproducts: &[],
        min_temp_c: 180, pressure_atm: 40.0, catalyst: Some(S::Platinum), duration_hours: 1.0, cross_recipe_group: None },
    Recipe { id: 831, name: "Citric Acid Fermentation", category: RecipeCategory::FoodBiological,
        inputs: &[(S::Sugar, 1.5), (S::Water, 3.0)], outputs: &[(S::CitricAcid, 1.0)], byproducts: &[],
        min_temp_c: 30, pressure_atm: 1.0, catalyst: None, duration_hours: 168.0, cross_recipe_group: None },
    Recipe { id: 832, name: "Adipic Acid (Cyclohexane Oxidation)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Benzene, 0.8), (S::NitricAcid, 0.5)], outputs: &[(S::AdipicAcid, 1.0)],
        byproducts: &[(S::Water, 0.3)],
        min_temp_c: 160, pressure_atm: 10.0, catalyst: Some(S::Cobalt), duration_hours: 2.0, cross_recipe_group: None },
    Recipe { id: 833, name: "Terephthalic Acid (PX Oxidation)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Xylene, 0.8), (S::Oxygen, 0.3)], outputs: &[(S::TerephthalicAcid, 1.0)],
        byproducts: &[(S::Water, 0.2)],
        min_temp_c: 200, pressure_atm: 20.0, catalyst: Some(S::Cobalt), duration_hours: 4.0, cross_recipe_group: None },

    // ===== ESTERS =====
    Recipe { id: 840, name: "Ethyl Acetate (Fischer Esterification)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Ethanol, 0.5), (S::AceticAcid, 0.5)], outputs: &[(S::EthylAcetate, 0.9)],
        byproducts: &[(S::Water, 0.1)],
        min_temp_c: 80, pressure_atm: 1.0, catalyst: Some(S::SulfuricAcid), duration_hours: 4.0, cross_recipe_group: None },

    // ===== AMINES AND N-COMPOUNDS =====
    Recipe { id: 850, name: "Aniline (Bechamp Reduction)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Benzene, 0.6), (S::NitricAcid, 0.3), (S::Iron, 0.2)],
        outputs: &[(S::Aniline, 1.0)], byproducts: &[(S::Water, 0.3)],
        min_temp_c: 100, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: None },
    Recipe { id: 851, name: "Caprolactam (for Nylon-6)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Benzene, 0.8), (S::Ammonia, 0.2)], outputs: &[(S::Caprolactam, 1.0)],
        byproducts: &[(S::Ammonium, 0.5)],
        min_temp_c: 130, pressure_atm: 1.0, catalyst: Some(S::SulfuricAcid), duration_hours: 6.0, cross_recipe_group: None },
    Recipe { id: 852, name: "Acrylonitrile (Sohio Process)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Propylene, 0.4), (S::Ammonia, 0.15), (S::Oxygen, 0.45)],
        outputs: &[(S::Acrylonitrile, 1.0)], byproducts: &[(S::Water, 0.3)],
        min_temp_c: 450, pressure_atm: 2.0, catalyst: Some(S::Molybdenum), duration_hours: 0.1, cross_recipe_group: None },
    Recipe { id: 853, name: "Hydrogen Cyanide (Andrussow)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Methane, 0.2), (S::Ammonia, 0.2), (S::Oxygen, 0.6)],
        outputs: &[(S::HydrogenCyanide, 1.0)], byproducts: &[(S::Water, 0.5)],
        min_temp_c: 1100, pressure_atm: 1.0, catalyst: Some(S::Platinum), duration_hours: 0.01, cross_recipe_group: None },
    Recipe { id: 854, name: "Melamine from Urea", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Urea, 1.5)], outputs: &[(S::Melamine, 1.0)],
        byproducts: &[(S::Ammonia, 0.3), (S::CarbonDioxide, 0.2)],
        min_temp_c: 400, pressure_atm: 10.0, catalyst: None, duration_hours: 1.0, cross_recipe_group: None },

    // ===== ETHERS AND EPOXIDES =====
    Recipe { id: 860, name: "Diethyl Ether (Ethanol Dehydration)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Ethanol, 1.0)], outputs: &[(S::DiethylEther, 0.7)], byproducts: &[(S::Water, 0.3)],
        min_temp_c: 140, pressure_atm: 1.0, catalyst: Some(S::SulfuricAcid), duration_hours: 2.0, cross_recipe_group: None },
    Recipe { id: 861, name: "Ethylene Oxide", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Ethylene, 0.6), (S::Oxygen, 0.4)], outputs: &[(S::EthyleneOxide, 1.0)], byproducts: &[],
        min_temp_c: 270, pressure_atm: 20.0, catalyst: Some(S::Silver), duration_hours: 0.1, cross_recipe_group: None },

    // ===== HALOGENATED =====
    Recipe { id: 870, name: "Vinyl Chloride Monomer", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Ethylene, 0.45), (S::ChlorineGas, 0.55)], outputs: &[(S::VinylChloride, 1.0)],
        byproducts: &[(S::HydrochloricAcid, 0.3)],
        min_temp_c: 500, pressure_atm: 1.0, catalyst: None, duration_hours: 0.1, cross_recipe_group: None },
    Recipe { id: 871, name: "Chloroform (Methane Chlorination)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Methane, 0.15), (S::ChlorineGas, 0.85)], outputs: &[(S::Chloroform, 1.0)],
        byproducts: &[(S::HydrochloricAcid, 0.3)],
        min_temp_c: 400, pressure_atm: 1.0, catalyst: None, duration_hours: 0.5, cross_recipe_group: None },

    // ===== POLYMERS FROM MONOMERS =====
    Recipe { id: 880, name: "Polystyrene", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Styrene, 1.0)], outputs: &[(S::Polyethylene, 1.0)], byproducts: &[],
        min_temp_c: 120, pressure_atm: 1.0, catalyst: None, duration_hours: 6.0, cross_recipe_group: None },
    Recipe { id: 881, name: "PET (Polyester)", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::EthyleneGlycol, 0.35), (S::TerephthalicAcid, 0.65)],
        outputs: &[(S::PolyesterFiber, 1.0)], byproducts: &[(S::Water, 0.15)],
        min_temp_c: 280, pressure_atm: 1.0, catalyst: None, duration_hours: 4.0, cross_recipe_group: None },
    Recipe { id: 882, name: "Nylon-6 from Caprolactam", category: RecipeCategory::ChemicalSynthesis,
        inputs: &[(S::Caprolactam, 1.0), (S::Water, 0.05)], outputs: &[(S::NylonResin, 1.0)], byproducts: &[],
        min_temp_c: 260, pressure_atm: 1.0, catalyst: None, duration_hours: 12.0, cross_recipe_group: None },
];
